### ISSUE TITLE
Move beacon API definitions to protobuf

### ISSUE THREAD

**Issue by crschnick** [xpipe-io/xpipe#1]
Right now, the Json API definitions are Jacksonized value classes through Lombok. To easily expand API support to other languages, it would be easier to have these definitions in something like protobuf.

**Comment by valentimarco** [comment]
i would like to implement this transition!

**Comment by valentimarco** [comment]
Ok, i confuse the beacon with the API.... Is too large for a first issue ;(

**Comment by crschnick** [comment]
This is now not needed anymore as the API will be reworked completely
