### ISSUE TITLE
Window sizes not scaling properly on 200% in Windows.

### ISSUE THREAD

**Issue by nevotheless** [xpipe-io/xpipe#100]
![grafik](https://github.com/xpipe-io/xpipe/assets/779797/33aeff1d-e348-4994-9a90-bd485c65a202)
![grafik](https://github.com/xpipe-io/xpipe/assets/779797/b61a3ae8-ba35-47ae-be06-4c8321da6bb6)
![grafik](https://github.com/xpipe-io/xpipe/assets/779797/84b3f015-d52e-440c-a6dc-8ae5d9c540c3)

basically the title, whenever i try to edit or create a connection the windows are way to huge. 
I'm using the recommended scaling size of 200% for my resolution / dpi.
![grafik](https://github.com/xpipe-io/xpipe/assets/779797/04afed46-58f5-4be6-8ac1-23a76179f798)

**Comment by crschnick** [comment]
Oh, that is weird. Let me see what went wrong here.

Have to see how to reproduce this as my Windows 10 scaling only goes to 175% max.

**Comment by crschnick** [comment]
This is fixed with 110a84d and will be released in the next 1.7.9 update soon

**Comment by crschnick** [comment]
So I published at test build for 1.7.9 here: https://github.com/xpipe-io/xpipe-ptb

Once I'm convinced that it doesn't break things, it will be released as a full release. I want to make sure that everything works with the window clamping even on more complex monitor setups first.

**Comment by nevotheless** [comment]
![image](https://github.com/xpipe-io/xpipe/assets/779797/bfb122a5-c876-4907-b9d2-e44088f67c2e)

The Welcome Dialog still behaves like it but the ones i posted in the issue work better now. 
![image](https://github.com/xpipe-io/xpipe/assets/779797/b523ffc9-3fa7-4d35-9e44-4c2d96c0e694)
![image](https://github.com/xpipe-io/xpipe/assets/779797/fdfb73dd-3bbf-46ba-b191-b5309a51c383)

Works for me 😄

**Comment by crschnick** [comment]
Oh, it seems like I forgot some other windows, that should be fixed quickly.
