### ISSUE TITLE
Can't install XPipe.

### ISSUE THREAD

**Issue by theromorph** [xpipe-io/xpipe#101]
Hola.

I couldn't install the application
- On my work-server Windows Server 2016 without elevation of user rigts. With user rights elevation instalation goes well.
- On my work-station Windows 10 22H2 in any case - with or without user rigts elevation

Any thoughts?

**Comment by crschnick** [comment]
How are you installing it? Manually downloaded msi, script, or package manager?

**Comment by crschnick** [comment]
Closing this issue as inactive
