### ISSUE TITLE
Feature Request: add "cancel" button to all dialogs

### ISSUE THREAD

**Issue by muescha** [xpipe-io/xpipe#110]
Feature Request:
- add "cancel" button to all dialogs
- should react to ESC 

Current State:
- dialog only cloasable with the mouse
- no ESC
- no CMD+W (macOS)

**Comment by crschnick** [comment]
That can easily be added. Should the cmd+w also apply to the main window? And are there any other shortcuts that I'm missing (I'm not really a mac user)

**Comment by crschnick** [comment]
This feature is now released

**Comment by crschnick** [comment]
Closing this for now, feel free to reopen if something does not work as expected

**Comment by muescha** [comment]
thx :)

**Comment by muescha** [comment]
in this ESC/cmd+w in dialogs it is not working on this places:
- New + click on subcategory
- `...`/`Edit` and `Edit icon`: Add connections / Add connection
