### ISSUE TITLE
Improve insights window for all connection types

### ISSUE THREAD

**Issue by PhilJbt** [xpipe-io/xpipe#112]
The `Insights` window appears blank in the `Add Connection` window.

- XPipe Desktop 1.7.11 (Portable)
- Windws 10 Family 22H2 (19045.3803)

![bug](https://github.com/xpipe-io/xpipe/assets/22506952/d739a375-bf16-4439-8eee-3ecb654841ac)

**Comment by crschnick** [comment]
Does that happen for every connection type or just some? I might have forgotten about a few connection types

**Comment by PhilJbt** [comment]
I don't know what should be displayed in this window, nor the others in fact, but this screenshot has been taken from the `Remote Host` one.

This is what I get on the `Shell Environment` one:
![shell](https://github.com/xpipe-io/xpipe/assets/22506952/793122a3-f567-40fc-ac86-04d6a477ef28)

**Comment by crschnick** [comment]
Oh I see. The purpose of this window is to show what will be executed to establish the remote connection. This is primarily useful for things like SSH so you can debug by yourself any issues when the command does not work as expected.

The contents of that window should be continually updated when you change the connection information, e.g. this is how it looks like for me in one of my shell environments
![image](https://github.com/xpipe-io/xpipe/assets/72509152/512e2a4c-08a3-4724-9f97-7d24b6480c67)

Honestly the insights window has not gotten a lot of love recently, so I will add it to my todo list to improve it.

**Comment by PhilJbt** [comment]
Understood. Maybe the button should be disabled/grayed if its tooltip has nothing to display?

**Comment by crschnick** [comment]
Yes, plus I can also improve the text for most connection types.

**Comment by crschnick** [comment]
This is now released

**Comment by PhilJbt** [comment]
The `Insights` button appears only when populated, as expected !
