### ISSUE TITLE
Feature Request - Show a loader animation icon

### ISSUE THREAD

**Issue by PhilJbt** [xpipe-io/xpipe#114]
Since run a connection can take several seconds, add a loader animation would be appreciated (especially as the one-click opening instead of a double-click opening surprised me).

[startup.webm](https://github.com/xpipe-io/xpipe/assets/22506952/5f4c41cc-0ee5-4a79-bec6-a724a06b4401)

It could be a loader:

![loading](https://github.com/xpipe-io/xpipe/assets/22506952/eddb3e7f-385b-456e-ba41-8471a8d13137)

Or an effect applied on the whole line:

(![](https://raw.githubusercontent.com/zalog/placeholder-loading/develop/docs/imgs/placeholder-loading-demo-1.gif))

**Comment by crschnick** [comment]
Hmm, that takes quite a long time. How long does it take if you connect to it manually, also that long? There will be a few small performance improvements in the next update for the loading time though.

But yeah, adding a loading animation somewhere should be possible.

**Comment by PhilJbt** [comment]
My terminal takes less than 2s to be displayed outside from Xpipe.

**Comment by crschnick** [comment]
Hmm, we can see whether the startup time improves with the next update

**Comment by crschnick** [comment]
Oh yeah I forgot to mention here that the startup improvement has been delayed a bit last minute because there were some problems with it and I wanted to push out the update. It's definitely in the pipeline, just need to fix a few small things before releasing it.

**Comment by PhilJbt** [comment]
1.7.16 fixed the delay.

**Comment by crschnick** [comment]
That is great but also sucks that this issue was so prevalent because of a non-sensical reason. I still plan to show better loading animations across the board, it just takes a while to properly implement.

**Comment by crschnick** [comment]
This is now properly resolved through the new terminal launcher in xpipe 8
