### ISSUE TITLE
java.lang.IllegalArgumentException: Directory  is not absolute

### ISSUE THREAD

**Issue by n3ur0n268** [xpipe-io/xpipe#115]
Hello,

I'am using the Xpipe portable version 1.7.11 and I encountered this error :

java.lang.IllegalArgumentException: Directory  is not absolute
at io.xpipe.app.browser.FileSystemHelper.resolveDirectoryPath(FileSystemHelper.java:83)
at io.xpipe.app.browser.OpenFileSystemModel.cdSyncOrRetry(OpenFileSystemModel.java:184)
at io.xpipe.app.browser.BrowserNavBar.lambda$createSimple$3(BrowserNavBar.java:52)
at io.xpipe.app.util.BooleanScope.executeExclusive(BooleanScope.java:17)
at io.xpipe.app.browser.BrowserNavBar.lambda$createSimple$4(BrowserNavBar.java:51)
at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$1(ThreadHelper.java:40)
at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)
at java.lang.VirtualThread.run(VirtualThread.java:309)

It appears when I want to use the browser on my local machine. I cannot access to my local machine.

**Comment by crschnick** [comment]
Does that happen for every path that you input into the navigation bar?

Also, what OS is this?

**Comment by n3ur0n268** [comment]
OS : Windows 10
Yes it's happen even I just use "C:\"

**Comment by crschnick** [comment]
That is very odd. I, and many other users, use Windows 10 so that shouldn't be an issue. The absolute check it's just a very rudimentary check to not feed malformed paths into the shell and should not fail for "C:\": https://github.com/xpipe-io/xpipex/blob/998ffddd61c88999c1055c8e491f2cec8e6a5a6c/core/src/main/java/io/xpipe/core/store/FileNames.java#L111

Does that also happen after a restart? And are there maybe some special characters that somehow ended up in the navigation bar? 

What happens if you input a variable instead like this:
![image](https://github.com/xpipe-io/xpipe/assets/72509152/b0cd4a46-2467-4269-bd37-0aa579fff6b7)

**Comment by n3ur0n268** [comment]
Yes even a restart, it happens. I think no special characters ended up in the navigation bar. Even using variable it doesn't work.
![image](https://github.com/xpipe-io/xpipe/assets/92572924/13181b59-c47a-45af-9424-d244b18fc7c2)

**Comment by crschnick** [comment]
Hmm also the roots don't show up there, so I think there is a more general problem. What system language are you using? I had some weird issues with cmd and languages before

**Comment by n3ur0n268** [comment]
The system language is French.

**Comment by n3ur0n268** [comment]
I just changed in English, restart and that doesn't work either.

**Comment by crschnick** [comment]
If you clicked on `search for connections automatically`, it should also have added a local PowerShell instance somewhere. Can you try whether that works? If it does, we can narrow it down to cmd.

I'm currently trying to set up french user account on my PC. There's usually a little bit more involved than just the display language, e.g. codepages and other stuff.

**Comment by crschnick** [comment]
Alright, I'm not able to reproduce this on a proper french setup, so it must be something else.

You can try launching xpipe in debug mode under Settings -> Troubleshoot -> Launch in debug mode and see what the output is when you enter a path

**Comment by n3ur0n268** [comment]
Yes I think it is restriction on this machine because I clicked on "search for connections" and it had an error from Policy :

_Process did not start up properly and had to be killed:
Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by 
a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective._

Otherwise, I tried on other machine in French when I have the full administrator access and It work well.

**Comment by n3ur0n268** [comment]
Yes it is really because I have restriction on this machine. I will try this app on the other one. This app seems to be very useful ! I think we can close this issue.

**Comment by crschnick** [comment]
That is good to know, I haven't really evaluated the effects of powershell being blocked from executing arbitrary scripts, this might cause that problem. I can add that to my to do list
