### ISSUE TITLE
[Feature Request] More SFTP GUI Features

### ISSUE THREAD

**Issue by rainrdx** [xpipe-io/xpipe#116]
Hi,

Wanna say thank you so much for working on this project. This is already my main server management tool and we will work on implementing this in my company next year. I am providing ideas of some nice to have features. Nothing I can't do with a filezilla or someother SFTP tools, but would be nice to do that under one roof:

1. Progress bar/tracking of file uploading and downloading. would love to know which file(s) is being uploaded, downloaded, and at what percentage, speed, and ETA.
2. Confirmations on conflicting files: options to choose whether I want to overwrite, skip, or rename, etc.

Thank you!

**Comment by crschnick** [comment]
Alright, I can add that to my todo list

**Comment by crschnick** [comment]
Your suggestions have now been implemented in 1.8 and are available for testing: https://github.com/xpipe-io/xpipe-ptb

**Comment by rainrdx** [comment]
Wow thank you will give it a try today or tomorrow

**Comment by rainrdx** [comment]
Hmmm interesting. Drag files to drop files to transfer does not do anything on windows...

**Comment by crschnick** [comment]
Hmm everything works fine for me, can you provide more details on how it does not work exactly?

**Comment by rainrdx** [comment]
Hmm sorry I just got around to try it out and seems that it does work this time. Weird but let's assume this is resolved and probably user error thank you

**Comment by crschnick** [comment]
This is now released. I found a few bugs that might be related to your issue and fixed them

**Comment by rainrdx** [comment]
Thank you and just got this. This is fabulous!
