### ISSUE TITLE
It is required that your private key files are NOT accessible by others. This private key will be ignored.

### ISSUE THREAD

**Issue by Gisy** [xpipe-io/xpipe#117]
1. I could not use the private key from an smb share
2. When loading from local drive, the key ist not accepted due to permission problems
I am running xpipe on windows 11, so it is quite difficult to set the right permissions?

**Comment by crschnick** [comment]
That is an OpenSSH thing, it always complains about the permissions even on Windows. If you are not able to put the key file somewhere into your user directory, I think you can still somehow fix this by going to Properties -> Security and changing permissions for other users in the windows explorer.

**Comment by crschnick** [comment]
On further thought, if you can't modify any permissions on the smb share somehow and don't want to copy it yourself to you user directory, xpipe could in theory perform the task of copying it somewhere inaccessible for other users and delete the copy when it is no longer needed.

Sadly you can't disable the permissions check in OpenSSH, so you have to perform a workaround

**Comment by Gisy** [comment]
Thanks for the answer! I copied the private key to my homefolder on windows and it works.
But it would be helpful if xpipe could handle to private key by its own like tabby does :)

**Comment by crschnick** [comment]
If you want, you can try whether the latest PTB can fix your original issue: https://github.com/xpipe-io/xpipe-ptb. I added an option to automatically adapt file permissions when OpenSSH complains. However I'm not entirely sure whether that will work for everyone as Windows permissions are weird.

**Comment by Gisy** [comment]
Hello!
I tried the ptb version but couldnt connect with the private key from the network path.
It always asks for my password which i disabled.
It works as before from the local path c:\users.....

**Comment by crschnick** [comment]
hmm, are you sure that password authentication is disabled? If the ssh server falls back to asking for a password, then it can't really be completely disabled. The fix that implemented only works if there is no fallback authentication method. You can also try to connect to you server manually in a terminal to see whether also ask you for the password.

You are not using a gateway/jump server here right?

**Comment by Gisy** [comment]
Oh, i disabled it in XPipe :)
Now i disabled it in the linux system. When i try to connect via ssh it immediately breaks the connection:  Permission denied (publickey).
Now the pw request in XPipe is also gone.
With XPipe and network path to the private key:

io.xpipe.core.process.ProcessOutputException: Process returned exit code 1:
FEHLER: Der derzeit angemeldet Benutzer verfügt nicht über Besitzrechte für
        die Datei (oder den Ordner) "X:\certs\myown_ssh_key".

XPipe cant fix the permission because i am not the owner of the file.
I wonder how this is solved in tabby....

**Comment by crschnick** [comment]
Well Tabby can just do their own stuff as they are not dependent on the openssh client implementation.

The last option I can think of would be to add another possible action to copy the key into the user ssh directory if the user wants to do that.

**Comment by Gisy** [comment]
Thanx for your great work!!
I found another issue.
When i mounted a truecrypt volume in windows, it will not shown up in the location requester when looking for keyfiles.

**Comment by crschnick** [comment]
I think this can be closed as there is either the option to attempt to modify the permissions or the information that you should move the keyfile somewhere in you user directory.

It is not perfect but the best that we can do with OpenSSH.

About the volume issue, I tried it briefly but could not see any problems. Feel free to open another issue with a little bit more information, then I can look into it.
