### ISSUE TITLE
[Feature Request} a crontab gui for executing commands an remote systems would be super nice

### ISSUE THREAD

**Issue by markusglaetzner** [xpipe-io/xpipe#119]
It would be super if x-pipe offers the option to regularly execute commands on remote systems, like the remote crontab. There are several web based crontab apps and this in x-pipe would be fantastic.

**Comment by crschnick** [comment]
So to clarify, are we talking about a cron-based solution like for example this https://github.com/cronkeep/cronkeep or an implementation that kind of works like cron but does not actually require cron, e.g. the ability to periodically run scripts automatically on a remote system while xpipe is running?

**Comment by markusglaetzner** [comment]
Hi, I mean the possibility to start scripts or commands to special times. On the other side, xpipe actually executes commands in a localy opening shell. Please don't missunderstand me - xpipe is really great, but I am thinking what would be perfect for homelab environments. A headless, web based app with the features of xpipe (ideally as a docker), with only one integrated web based terminal and an implementation of crontab, so that all tasks could be executed without my client. That would be perfect :-) In smaller steps, it would be super to execute commands to specific times.

**Comment by crschnick** [comment]
Ok I we'll see what I can do with running commands at special times.

About the headless web app of XPipe, that is already being tracked in #86 and is definitely possible but requires some effort. So in the long term I can see that happening, but it's going to take a while. There are several hurdles to take first before I can effectively implement a web interface as the application was not originally designed for that.

**Comment by markusglaetzner** [comment]
You are totally right, xpipe is an app for the local client I am working with and the app is great like it is! The ability to periodically run scripts automatically on a remote system would be cool in a docker-version. A terminal suddenly popping up on my client would be rather annoying or irritating. So forget my query regarding crontab. A Docker image with webinterfase would be great, but I would not see this as a feature request for this app because this seems not the concept. I would see it as a separate version or app (for example "xpipe-web").

**Comment by crschnick** [comment]
Well that depends, we can also run scripts periodically in the background without a terminal window, it would work similar to SSH tunnels do now in xpipe.

I don't think it would be a separate version or app, most of the groundwork is already there to run xpipe as a background process plus there is also a socket interface available, so a web interface would be possible to add. It is just other things that would need to be adapted for it to work properly.

If you're interested, you can just watch #86 to get notified about any progress there

**Comment by markusglaetzner** [comment]
Great , thanks and well done :-)

**Comment by crschnick** [comment]
I guess we can close this then. Once there is a web version in the future, something like this can be opened again
