### ISSUE TITLE
[Feature Request]   Option to add additional editors 

### ISSUE THREAD

**Issue by dwilliam62** [xpipe-io/xpipe#123]
I use Astro NEOVIM as my main editor.    It would be nice to be able to use that with your tool. 

I'm sure others would like to use EMACS,  sublime or some other editor

**Comment by crschnick** [comment]
For now, there is already the Custom Editor option where you can supply your own command.

I will see what I can do for more text editors

**Comment by dwilliam62** [comment]
Duh!  Thanks!    I will use that.

**Comment by dwilliam62** [comment]
I was able to add NVIM, though I need to start a terminal then call /usr/bin/nvim.   

As is you can only have one custom editor.    Would be helpful if you could add them to the list instead.    Actually what would be more amazing is the option to set the editor per connection profile.    Then if not changed in the connection profile use the default.

**Comment by crschnick** [comment]
I guess that sounds like a good idea. What would be the use case for having a certain editor per connection profile set? I was under the assumption that people would always use the same general purpose editor for most tasks, and if they want to open a file with a specific application, you can just use the `Open` button in the file browser to open it with the default application on your system for that file type.

**Comment by dwilliam62** [comment]
yeah   when I wrote it  I was thinking it could set the editor in that
session.   Not the system that Xpipe is running on.    Close this one
please   I didn't think it threw all the way
