### ISSUE TITLE
[Feature Request]   Add copy or clone function to make adding systems easier  Especially with clusters

### ISSUE THREAD

**Issue by dwilliam62** [xpipe-io/xpipe#124]
I have a home lab with some old PCs in a Proxmox cluster.    Having to add in them one at a time isn't efficient 

I would love to make one, clone it, then I just have to edit the IP address or hostname.    Especially true when adding in the VMs

**Comment by crschnick** [comment]
Alright, that will be added in the next update

**Comment by crschnick** [comment]
You can try it out if you want in the latest PTB build: https://github.com/xpipe-io/xpipe-ptb/releases/tag/1.7.12-3 
That one should also contain improved keyboard support for your other issue

**Comment by dwilliam62** [comment]
Thank you for this!!   Omg What a time saver!!!!   I don't know if you call it  a bug or not.  When you clone it, you need to manually run the scan to detect shells, etc on that new host.   The button is there on the right so not a big deal 

![image](https://github.com/xpipe-io/xpipe/assets/129223418/8d9d9d48-16c5-4c09-8505-f4db665f7b5b)

**Comment by crschnick** [comment]
I thought that since you would change the connection details anyways, we cant simply copy all information from the previous system as that might change here on another system. E.g. you might have different shells installed or other things

**Comment by dwilliam62** [comment]
yup I agree,  hence not really a bug.   Was more thinking the next step of
rescan wasn't in your face obvious.   in my environment i have 3x proxmox
and two backup servers  so being able to clone them is super nice

For example, the expand > arrow is grayed out.  If you click on it, in that
state could it either run, or prompt  you to run the scan?

Since you are adding it, it's pretty natural that the next step, like when
you add in a new one, is scan the host.

**Comment by crschnick** [comment]
This feature is now released. I will think about better ways to run the scan though

**Comment by dwilliam62** [comment]
Thanks!
