### ISSUE TITLE
[Feature Request]   In pull down menus for Password authentication allow use of keyboard to select option

### ISSUE THREAD

**Issue by dwilliam62** [xpipe-io/xpipe#125]
I use Hyprland most of the time, so I am very keyboard centric. :)    When selecting the Password options I have to use the mouse to select them.  I am already in the field I should be able to type the first letters and select it that way   It's faster and easier to do compared to having to take hand off keyboard, move the mouse, click, move to select the option.  

![image](https://github.com/xpipe-io/xpipe/assets/129223418/571db3ba-cc11-4ce1-9e15-38ae0df43aff)

**Comment by crschnick** [comment]
For now I made it possible to navigate the menu with the arrow keys and enter. I can also think about typing the first few letters of an option as well.

**Comment by dwilliam62** [comment]
thank you that is an improvement!
