### ISSUE TITLE
Symbols semantics

### ISSUE THREAD

**Issue by ennerf** [xpipe-io/xpipe#13]
I don't remember where to find a good reference/guideline, but the symbols you're currently using don't match the semantics I'd expect, i.e., I'd expect to get expanding information when clicking on the `right-arrow` on the left, and be able to re-order items when pressing the `bars` on the right.

![image](https://user-images.githubusercontent.com/5491587/229474117-6897c475-bf6b-439f-a5f0-267450dedf92.png)

If I remember right, the left symbol should be a [`circle`](https://fontawesome.com/icons/circle) (list item without action), and the right one should be an [`ellipsis-vertical`](https://fontawesome.com/icons/ellipsis-vertical) (additional settings/information).

**Comment by crschnick** [comment]
That's a good point, these icons were chosen without much thought. The right icon should symbolize a hamburger menu, but I can see a resemblance to these reorder icons. I can easily replace the arrows but have to look for some compromise for the hamburger as the vertical ellipsis looks fairly small.
How does this look:

![image](https://user-images.githubusercontent.com/72509152/229508830-2ebf849b-c95f-4392-944c-3a63a638b0e3.png)

**Comment by crschnick** [comment]
I think the gear icon would work fine size-wise:

![image](https://user-images.githubusercontent.com/72509152/229534682-a3717aa2-ee2a-4fa3-b659-f0a56ed7c9c7.png)
