### ISSUE TITLE
Support of import in .ssh/config file.

### ISSUE THREAD

**Issue by AirMarty** [xpipe-io/xpipe#137]
Hi,
thank you for your project ! :+1: 
I dont know if its more a feature than an issue but is seems that import command in **~/.ssh/config** file is not supported by x-pipe during "auto discover connections".

Or may be I do it wrong ?

Thank you for your answer,
RMA

**Comment by crschnick** [comment]
Yeah that it's correct, but I can add that. You have more connections stored in other config files that are imported from there?

**Comment by AirMarty** [comment]
Yep, I used to add **Include** statement (cf. : https://man7.org/linux/man-pages/man5/ssh_config.5.html ) in order to limit lines of my config file. And yes I use many as I want based mainly on envionment type (production, development, sanbox, etc.) and/or place in infrastructure (external or internal).

I hope my answer will help.
RMA

**Comment by crschnick** [comment]
Alright, I will add that.

I just have to take care about transitive and circular includes, because such an include chain can become quite complex in theory.

**Comment by AirMarty** [comment]
Nice :+1: 

With no doubt I have other questions/requirements ; I will open new issue but not too fast and not to give you too much work ;)

**Comment by crschnick** [comment]
Feels free to share your questions/requirements, that allows me to prioritize them early on rather than later

**Comment by crschnick** [comment]
Alright, the latest PTB build supports include statements plus allows adding arbitrary ssh convict files in addition to the system ones. You can try it out if you want: https://github.com/xpipe-io/xpipe-ptb. Ideally you can stress test it with many files, nested includes, etc.

**Comment by AirMarty** [comment]
Hi, thanks, I will test it ASAP !

**Comment by crschnick** [comment]
This feature is now released

**Comment by klsx0** [comment]
Hello,
Thanks for the new feature, it doesn't work if we set wildcard file in the include.

_.ssh/config_ 
`Include ./config.d/*.config`

Thank you for you answer.

**Comment by crschnick** [comment]
Hmm I see, I think as of right now it only supports wildcard files without extension. So `Include ./config.d/*` should work assuming that there are no non-config files in there

**Comment by klsx0** [comment]
I've checked without extension and indeed it works well ! Thanks you a lot !

**Comment by crschnick** [comment]
This is now fixed in the latest release, it should accept wildcards with file extensions as well.

**Comment by klsx0** [comment]
Thanks a lot !
