### ISSUE TITLE
Support SSH Jump as gateway?

### ISSUE THREAD

**Issue by dragon2611** [xpipe-io/xpipe#140]
Recent versions of OpenSSH support doing a jump (Providing it's not disabled on the machine you want to jump from) the command is in the format ssh -J user@jumpbox user@target

This is handy because it allows you to use key based authentication using the local SSH agent, I think the way Xpipe uses gateways means it's trying to use the SSH agent on the gateway rather than the local machine (I get an error java.lang.IllegalStateException: Unable to fetch agent identities:) if I try to use another SSH target as a gateway.

**Comment by crschnick** [comment]
Yeah this is correct, it looks for the agent on the gateway.

It has a little bit to do with how exactly it will open the connection, which is different from jump hosts. Maybe I can add support for that somehow.

For now, if you want to use jump hosts properly, you can create host entries in the OpenSSH config file on your system and import that into xpipe. That will give you the desired behavior.

**Comment by CharlesGodwin** [comment]
@crschnick You mention "importing config file into x-pipe.  How do you do that with the Windows Client? TIA

**Comment by crschnick** [comment]
In the current release version (1.7.12), you can add any host entries into your user ssh config located at `<User Home>\.ssh\config`. If you then go to `search automatically` in xpipe and select the local machine, it should give you the ability to import from the ssh config.

In the next release, this behavior will be changed to also support adding arbitrary ssh config files manually. This is already available in https://github.com/xpipe-io/xpipe-ptb

**Comment by crschnick** [comment]
So I thought about an implementation for that. I think the most straightforward way right now would be to give the option to enable agent forwarding instead of reworking how jump servers work.

Would that be enough?

**Comment by crschnick** [comment]
Now with support for custom SSH connections released, I think this issue can be closed. You can now specify any jump setup via the SSH config options in xpipe. That also solves the question of how to handle agent forwarding as the user can enable or disable that themselves.
