### ISSUE TITLE
XPipe creates new windows instead of tabs

### ISSUE THREAD

**Issue by Gufderald** [xpipe-io/xpipe#142]
Hi! I'm using Arch with Hyprland window manager (which uses Wayland), and Kitty for terminal emulator. My problem is that XPipe is opening new connections in new windows instead of tabs (while setting "Prefer to open new tabs")is enabled). What can I do to fix that?

**Comment by crschnick** [comment]
That is a limitation of kitty. At least last time I checked the kitty CLI did not support opening new tabs, only new windows.

**Comment by SosthenG** [comment]
Hi! I have the same issue with gnome terminal, which definitely supports new tab. 
The "prefer to open new tabs" option is enabled but everytime I open a connection it opens a new window.
I'm using latest XPipe Desktop 1.7.13 on PopOS! 22.04 (Gnome 42.5) with Gnome Terminal 3.44.0

**Comment by crschnick** [comment]
For gnome terminal it might be possible that I just forgot to pass that option. I can fix that the next release.

You can for now select `Custom` and enter the command `gnome-terminal --tab -- $CMD`, that should open it in a new tab.

**Comment by SosthenG** [comment]
`gnome-terminal --tab -- $CMD` does not work either, still opening in a new window.

**Comment by crschnick** [comment]
I just followed the help output:

```
gnome-terminal --help-terminal
Usage:
  gnome-terminal [OPTION…] [-- COMMAND …]

Options to open new windows or terminal tabs; more than one of these may be specified:
  --window                        Open a new window containing a tab with the default profile
  --tab                           Open a new tab in the last-opened window with the default profile
```

I'm not an expert for gnome terminal, so I've no idea how that is handled internally. You can try to experiment maybe with the profiles with `--profile` to achieve that. If you somehow figure out how to open new tabs from the CLI, let me know and I can implement that.

**Comment by SosthenG** [comment]
Running `gnome-terminal --tab` in the terminal does open a new tab, but using the same thing as a custom terminal command in XPipe config does not work.

**Comment by crschnick** [comment]
Yeah I observed that too, I guess gnome terminal can perform some internal logic when executing that command from gnome terminal itself. To properly replicate that, you have to execute that in any other terminal that is not gnome terminal.

**Comment by SosthenG** [comment]
Yeah you're right I tried with another terminal and it also opens a new window.
Don't think there is a solution for that, looks like it's how it works (see https://askubuntu.com/a/1000203). You might be able to achieve this by keeping a reference to the latest terminal XPipe opened and open a tab from that but that seems complicated for a simple thing like this...

Any simple terminal to recommand in the meantime that supports new tabs and that I can use with XPipe?

Thanks for your help.

**Comment by crschnick** [comment]
I think https://github.com/gnome-terminator/terminator comes pretty close and supports tabs.

**Comment by ndom91** [comment]
@Gufderald sorry to kinda hijack this issue, but how are you runnign this under wayland (hyprland)? Whenever I start it via the included `.desktop` file / flags I get the typical desktop scaling issues that xwayland applications exhibit

**Comment by crschnick** [comment]
This is now communicated to users in the terminal settings. Any terminal that does not support tabs will have the option grayed out.
