### ISSUE TITLE
Clone connection requires 2 edits to successfully clone. 

### ISSUE THREAD

**Issue by di-org** [xpipe-io/xpipe#146]
I am running XPipe Desktop v1.7.12-202312282215, on Pop!_OS 22.04.

When I clone an SSH connection, then edit to make the "Host" and "Connection name" changes, after clicking finish, the "Connection name" changes but the "Host" remains the same.  If I right-click and select "Edit" a 2nd time and just click finish (no changes), the "Host" changes and it properly identifies the OS.

I have included 4 screencaps to show the steps above:

1 - Create the clone
2 - 1st edit of "Host" and "Connection name" change.
3 - After clicking "Finish" from the 1st edit (Note the "Connection name" and "Host" name.)
4 - The result after the 2nd "Edit", "Finish" (no changes).

I have performed the clone function 3 times with the same results.

Thanks,
A

![2023-12-30_clone_step_1](https://github.com/xpipe-io/xpipe/assets/41967712/f3a2f89b-25c2-4be4-b1cc-8c3ccea3b7f4)

![2023-12-30_clone_step_2](https://github.com/xpipe-io/xpipe/assets/41967712/934ffe5f-aa27-4c90-aefd-545dfbadb5cc)

![2023-12-30_clone_step_3](https://github.com/xpipe-io/xpipe/assets/41967712/9501e665-ed41-4fcc-b5d2-ff82450831bd)

![2023-12-30_clone_step_4](https://github.com/xpipe-io/xpipe/assets/41967712/49e0cfbf-44da-4ba3-ba7a-f6b4574e7442)

**Comment by crschnick** [comment]
It seems like the display info update did not trigger under every condition. The fix for that will be included in the next release

**Comment by crschnick** [comment]
This should be fixed in the latest release

**Comment by crschnick** [comment]
Closing this as completed
