### ISSUE TITLE
Consider publishing to Chocolatey/winget

### ISSUE THREAD

**Issue by atkulp** [xpipe-io/xpipe#15]
I'd love to be able to install without an MSI.

**Comment by crschnick** [comment]
Yeah, having it available in package managers would be nice. Although I have to see how to integrate that with the update mechanism. What is your main reason for not liking the msi? Is it just ease of installation or other reasons?

**Comment by atkulp** [comment]
You can actually distribute via msi for package managers. I just prefer a
simple command line install that's easily scriptable and ideally
updateable. MSI just feels heavy these days. Thanks for your great work
though!

**Comment by crschnick** [comment]
The tool currently used for releasing on GitHub is [jreleaser](https://jreleaser.org/guide/latest/reference/packagers/index.html), and it also supports releasing to a couple of package managers including chocolatey. So if anyone is interested in setting this up, this should definitely be doable. I have never released to chocolatey yet, so I'm a little bit overwhelmed about the whole process.

**Comment by atkulp** [comment]
I'm willing to look into it. I'll see what I can figure out.

**Comment by atkulp** [comment]
I'm using JDK 19.0.2 and Gradle 7.4.2 on Windows 11 but getting exceptions. I have a basic jreleaser yaml file created, but I'm stuck until I can run the tools. Any ideas?

```
.\gradlew dist 
FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\Users\arian\source\repos\xpipe\settings.gradle'

* What went wrong:
Could not compile settings file 'C:\Users\arian\source\repos\xpipe\settings.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 63

  java.lang.IllegalArgumentException: Unsupported class file major version 63

```

Versions:

```
java --version
openjdk 19.0.2 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-44)
OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
```

```
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          19.0.2 (Oracle Corporation 19.0.2+7-44)
OS:           Windows 11 10.0 amd64
```

**Comment by crschnick** [comment]
Ok that is kinda weird, but I looked into this. First of all, by using the gradle wrapper (gradlew), it should automatically download the appropriate gradle version (7.6), your local gradle installation is irrelevant there. But when I tried it myself on a new clone I also had similar issues even though the Java + gradle version should be compatible.
I experimented with gradle 8 and it seems to have fixed the issue, so I created a new branch called `gradle8`, which should build with `.\gradlew dist`. If the gradle build works, we can look into the release.

**Comment by aalmiray** [comment]
Additional information for publishing to [Chocolatey](https://jreleaser.org/guide/latest/reference/packagers/chocolatey.html):
1. You need a publication key. Create an account at https://chocolatey.org/
2. Package publication via `choco` command must happen on Windows. If running on other platforms then set `remoteBuild` to `true`. https://jreleaser.org/guide/latest/reference/packagers/chocolatey.html#_remote_build
3. Automatic publication to secondary Git repository (if it's GitHub) will add a GH workflow that can publish to chocolatey.org on push/new tag.

**Comment by crschnick** [comment]
Thanks for the information, seems like I have some set up to do then.

**Comment by crschnick** [comment]
I made some progress on this as I was able to push to the choco repository. Now it's about waiting for approval and setting up the workflow to work in an CI environment.

**Comment by atkulp** [comment]
That's awesome! I had started on the manifest, but the build problems stopped me. Is it much more effort to do Winget as well?

**Comment by crschnick** [comment]
I will look into other package managers once this is done. My main issue right now is to figure out how to make X-Pipe detect that it has been installed through a package manager to adapt its update check behavior.

**Comment by atkulp** [comment]
I would think you could pass a command line parameter to the installer that it could use to suppress built-in update checks.

**Comment by crschnick** [comment]
Alright I have come up with a solution in the https://github.com/xpipe-io/xpipe/tree/updater branch:
- X-Pipe can automatically detect now in which environment it is currently running (msi, choco, portable, etc.) without requiring any parameters or configuration.
- Based on that information, it will adapt on how it shows and executes available updates.
- This will make it very easy to add support for more package manages in the future

I guess we can test this once the choco package is approved.

**Comment by crschnick** [comment]
So the release is ready, I'm just waiting for the chocolatey package approval. I created a new repository at https://github.com/xpipe-io/xpipe_staging/releases to manage staging releases, so you can try out an early version there. The staging version still looks for regular updates so it will downgrade itself, but that way it's easy to test the updater.

Sadly, I can't test the choco updater from there as that would require the package to be available.

**Comment by crschnick** [comment]
Now I have no idea what is going on at chocolatey, but the package has been in review for over a week with no comments. I'm not sure whether this is a viable alternative if every single published version takes over a week to approve.

**Comment by aalmiray** [comment]
If this is the first publication to Chocolatey then please be patient. It took me 3 weeks IIRC the first time I published my first package.

**Comment by crschnick** [comment]
I interpreted the moderation notice I received as this process being the same for every new published version, that's why I was worried. At least I don't see anything in it that states that this is only a one time process. If that is not the case then it's fine.

**Comment by aalmiray** [comment]
In my experience it'll likely take 2 weeks or less for the next couple of releases. At some point the package becomes trusted in which case the admins turn auto verification on, thus taking just a few hours to publish the package.

I can only recommend patience for a few months.

**Comment by crschnick** [comment]
As of the latest release, it seems like that chocolatey finally has marked the package as trusted. So it seems like this can be finally closed now.
