### ISSUE TITLE
cannot use Hyper as terminal

### ISSUE THREAD

**Issue by devzwf** [xpipe-io/xpipe#150]
when i choose hyper (https://hyper.is/) as terminal for ssh  
the app crash.

Is there something i am doing wrong ?

tabby/ windows terminal seems to work

**Comment by crschnick** [comment]
How exactly did you choose hyper as a terminal and what error does it return?

To reason hyper is not supported by xpipe out of the box is that it is missing a CLI. Last time I checked there was no way to start hyper with a specified command to run.

**Comment by devzwf** [comment]
could be ... hosnestly , i just tried the direct way :)

i try with :
settings => terminal => custom => <path_to>\Hyper\Hyper.exe
i then get a "JavaScrip error occurred in the main process"
cannot create process, error code: 267

**Comment by crschnick** [comment]
Yeah that is due to hyper not supporting that. You can try lobbying them to think about supporting passing commands via the CLI but I doubt that that will happen.

So will sadly close this as non-fixable from my end.

**Comment by lgund** [comment]
I am using the Hyper terminal as well on MacOS cause the default Terminal does not have much highlighting. But I got the some Problem, that I can´t register the terminal currently. I tried `open /Applications/Hyper.app -e $CMD` but got this error:

```
#!/usr/bin/env zsh
unset ZDOTDIR
'/Applications/XPipe.app/Contents/MacOS/xpipe' terminal-register --request f8aa484a-34f1-4f1a-bdbd-753d1f2593c3
while true
do
'/Applications/XPipe.app/Contents/MacOS/xpipe' terminal-wait --port 21721 --request f8aa484a-34f1-4f1a-bdbd-753d1f2593c3
r=$?
if [ $r -ne 0 ]; then
  echo "Press [r] to restart or any other key to close this session ..."
read -rsk;PROMPT_KEY="$REPLY"
if [ "$PROMPT_KEY" = "r" ]; then
  unset PROMPT_KEY
  continue
fi
unset PROMPT_KEY

  exit $r
fi

SCRIPT="$('/Applications/XPipe.app/Contents/MacOS/xpipe' terminal-launch --port 21721 --request f8aa484a-34f1-4f1a-bdbd-753d1f2593c3)"
r=$?
if [ $r -ne 0 ]; then
  echo "Press [r] to restart or any other key to close this session ..."
read -rsk;PROMPT_KEY="$REPLY"
if [ "$PROMPT_KEY" = "r" ]; then
  unset PROMPT_KEY
  continue
fi
unset PROMPT_KEY

  exit $r
fi

if [ -f "$SCRIPT" ]; then
  . "$SCRIPT"
  echo "Press [r] to restart or any other key to close this session ..."
read -rsk;PROMPT_KEY="$REPLY"
if [ "$PROMPT_KEY" = "r" ]; then
  unset PROMPT_KEY
  continue
fi
unset PROMPT_KEY

  exit 0
else
  echo "Press enter to close this session ..."; read -sk
  exit 1
fi
done

```

Does have anyone some ideas?
