### ISSUE TITLE
file upload bug

### ISSUE THREAD

**Issue by brianshen0522** [xpipe-io/xpipe#151]
when I'm trying to upload multiple file via file browser, it will stuck, and I'll need to reopen xpipe.
and I can't find the new file I'm uploading when I refresh, but when I "ls" in cli, it's there.

**Comment by crschnick** [comment]
What system/shell are you uploading to? Also, do you have to restart xpipe as a whole or is it just sufficient to close and open a new tab?

**Comment by crschnick** [comment]
This problem should now be fixed in the latest release
