### ISSUE TITLE
SSH Key from Security Key Used Multiple Times

### ISSUE THREAD

**Issue by nmcbride** [xpipe-io/xpipe#155]
So I have SSH keys that are generated from a passkey on my security key.

I still have public and private files on my system the only difference is when SSH tries to use them, you have to touch the security key.

When I use it and SSH to a server it flashes I hit it once and then I am logged in.

However, XPipe seems to do it twice.

When I go to login it uses the security key and flashes for me to touch it first to just open the window, then it flashes again and has me touch it a second time to actually make the connection.

It would be nice if it worked like normal where you only have to touch it once.

**Comment by nmcbride** [comment]
Just a follow-up,

Even just telling it to find connections makes me use my security key twice.

**Comment by crschnick** [comment]
The first behavior you mentioned is kinda intended/unavoidable. Essentially, the first connection will be opened in the background to set everything up with init scripts etc. Then in the second connection, these init scripts and connections are actually opened in your terminal.

I plan to release an optimization that I'm working on soon to get this down to only one effective connection if the connection is not customized with custom environments or scripts. It's almost done, just needs a few fixes.

For the second thing you mentioned when it's trying to find connections, I have to investigate that as it should only connect once.

If I remember correctly, there should be a setting for most security keys to remember the last touch for a short period.

**Comment by crschnick** [comment]
This has now been somewhat addressed in 9.0. It will attempt to only use the security key when explicitly needed. It's not perfect but should work well enough.
