### ISSUE TITLE
I dont know if its real error from my OS or from xpipe.

### ISSUE THREAD

**Issue by AirMarty** [xpipe-io/xpipe#167]
hi,
i'm testing last version 1.7.13 who is complaining about too many open files, IDK if its real issue from my os ?

![image](https://github.com/xpipe-io/xpipe/assets/104483/d60aa475-5892-4bdf-9856-49a29741de7f)

THX !

**Comment by crschnick** [comment]
Hmm, does this happen immediately or only after a long time of usage? Every file you edit in the file browser creates a new temporary directory that is watched for changes. We don't put all files into the same directory to avoid conflicts when editing two different files with the same name. I can see this exhausting the limit after long usage.

**Comment by AirMarty** [comment]
Hi,
It happens just after new update/install and launch of xpipe ; the OS was running for certain time but not the app.

**Comment by crschnick** [comment]
Can you check what your inotify maximum is like this: https://stackoverflow.com/questions/32281277/too-many-open-files-failed-to-initialize-inotify-the-user-limit-on-the-total and then check how many watches are currently in use like this: https://stackoverflow.com/a/24994331/6477761?

**Comment by crschnick** [comment]
To this is now handled better by xpipe explaining that file watching will be unavailable when this error occurs. I don't think I can influence the inotify limits, that is an OS setting. So we will have to make the best out of it.
