### ISSUE TITLE
Error with dependencies in .deb package and others

### ISSUE THREAD

**Issue by acarrera-cenedin** [xpipe-io/xpipe#168]
I tried to install the package but it throws a message with dependencies for a package libgdk-pixbuf-2.0-0 and when install with previous version installer it just work

**Comment by crschnick** [comment]
Yes since the latest update the installer now reports all required dependencies. It didn't do that before, that is why it only happens now probably.

For the `.deb` package, does that still occur after you run `sudo apt update`?

**Comment by AirMarty** [comment]
Hi, same issue here after clicking on update version , happen on 2 different machine.
`Les paquets suivants contiennent des dépendances non satisfaites :
 xpipe : Dépend: libgdk-pixbuf-2.0-0 mais il n'est pas installable
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».
Update failed ...` result error at the end of automatic update.

**Comment by crschnick** [comment]
What OS version are you running? libgdk-pixbuf-2.0-0 is a standard debian package: https://packages.debian.org/bullseye/libgdk-pixbuf-2.0-0 that should be available basically everywhere. That problem still occurs then after you refresh with `sudo apt update` before?

**Comment by dragonlost** [comment]
Same problem here. It's my first installation of Xpipe. On Kubuntu 20.04 LTS (kernel 5.15.0-91)
I have exact same dependencies problem.
I checked I already installed this package.

**Comment by crschnick** [comment]
Let me investigate that then, I only tested on Ubuntu 22.04+

**Comment by dragonlost** [comment]
No problem for 1.7.12 version

**Comment by AirMarty** [comment]
I teested both :
`$ sudo dpkg -i xpipe-installer-linux-x86_64.deb 
(Lecture de la base de données... 502982 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de xpipe-installer-linux-x86_64.deb ...
Dépaquetage de xpipe (1.7.13-1) sur (1.7.13-1) ...
dpkg: des problèmes de dépendances empêchent la configuration de xpipe :
 xpipe dépend de libgdk-pixbuf-2.0-0 ; cependant :
  Le paquet libgdk-pixbuf-2.0-0 n'est pas installé.

dpkg: erreur de traitement du paquet xpipe (--install) :
 problèmes de dépendances - laissé non configuré
Traitement des actions différées (« triggers ») pour man-db (2.9.1-1) ...
Des erreurs ont été rencontrées pendant l'exécution :
 xpipe
`
Then : 
`$ sudo dpkg -i xpipe-installer-linux-x86_64.deb 
(Lecture de la base de données... 502982 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de xpipe-installer-linux-x86_64.deb ...
Dépaquetage de xpipe (1.7.13-1) sur (1.7.13-1) ...
dpkg: des problèmes de dépendances empêchent la configuration de xpipe :
 xpipe dépend de libgdk-pixbuf-2.0-0 ; cependant :
  Le paquet libgdk-pixbuf-2.0-0 n'est pas installé.

dpkg: erreur de traitement du paquet xpipe (--install) :
 problèmes de dépendances - laissé non configuré
Traitement des actions différées (« triggers ») pour man-db (2.9.1-1) ...
Des erreurs ont été rencontrées pendant l'exécution :
 xpipe
`

I stay with 1.7.12 ;)

**Comment by crschnick** [comment]
Note that dpkg does not support installing dependencies of installers. So even with correct dependencies it would not work like that if one of them had to be installed. You should use `sudo apt update && sudo apt install xpipe-installer-linux-x86_64.deb` for that once I fixed the issue.

**Comment by AirMarty** [comment]
Nope it doesnot work, it seems that apt not found my local file...?



    Lecture des informations d'état... Fait  
    46 paquets peuvent être mis à jour. Exécutez « apt list --upgradable » pour les voir.  
    Lecture des listes de paquets... Fait  
    Construction de l'arbre des dépendances  
    Lecture des informations d'état... Fait  
    E: Impossible de trouver le paquet xpipe-installer-linux-x86_64.deb

**Comment by crschnick** [comment]
I think it has to be `sudo apt ./install xpipe-installer-linux-x86_64.deb` to indicate a local file.

I just pushed a commit to fix the package issue, so there should be a PTB version available shortly that should fix this properly.

**Comment by crschnick** [comment]
Edit: I did not pay attention. It obviously has to be `sudo apt install ./xpipe-installer-linux-x86_64.deb`. The build to fix this issue is a little bit delayed due to the CI runner having problems right now.

**Comment by AirMarty** [comment]
ok no stress I use previous version till you release ;)

**Comment by crschnick** [comment]
Alright can you guys please try this build: https://github.com/xpipe-io/xpipe-ptb/releases/tag/1.7.14

If it works, I will create a full release soon as there are also a couple other breaking issues that need quick fixing.

**Comment by crschnick** [comment]
This is now fixed in 1.7.14 along with a couple of other important issues
