### ISSUE TITLE
[Feature Request] Flatpack Build

### ISSUE THREAD

**Issue by nmcbride** [xpipe-io/xpipe#169]
Please consider creating a flatpack build / putting it on flathub.
Looks like it would be fairly easy.

Thank you.

**Comment by crschnick** [comment]
This issue is more complex than it looks due to the flatpatk sandbox. With the current setup it is impossible to create a flatpak build. Once #165 is done, it might be possible.

**Comment by crschnick** [comment]
Alright so I spend some time experimenting and evaluating the possibility of sandboxed version. Sadly this is not possible without having to rewrite basically the entire application, so the sandbox and a flatpak is not going to happen. You can't open other applications or shells from the sandbox, so nothing would work.

Someone told me that it is possible in theory to reduce the level isolation of the sandbox via flatseal, but that would require the user to perform additional operations to make it even work. If it is not going to work out of the box, a flatpak version would not make a lot of sense.

**Comment by crschnick** [comment]
Closing this as sadly wont fix. Flatpak is just too restrictive of a platform for an application like xpipe that tries to integrate with other applications.
