### ISSUE TITLE
Cannot use tab in docker containers' shells

### ISSUE THREAD

**Issue by KyllianBeguin** [xpipe-io/xpipe#174]
Hi !
## The problem
I want to use shells in my docker containers, but I cannot use tab to autocomplete the files' name.
![ErrorShells](https://github.com/xpipe-io/xpipe/assets/50613619/6817c01a-443c-4419-8032-952a95275767)
*You'll notice in the gif that I firstly open a shell in the VM, in which tab is working*

## To reproduce
1. Open a docker shell
2. Write the beginning of a file's name
3. Use tab

**Comment by crschnick** [comment]
By default, XPipe opens a `sh` in your docker container. These usually don't support autocompletion and other features.

What you are looking for is probably bash. The reason XPipe defaults to sh is that containers very rarely come with more than just the bare essentials, which is sh.

You can fix this by right clicking the container -> Find available connections -> Select shell environments. If any other shell, such as bash, is installed that supports autocompletion it should be added there.

**Comment by KyllianBeguin** [comment]
Figured it today ! Thank you !
(Off topic) Should I consider start learning some sh? 😅

**Comment by crschnick** [comment]
Great.

If you're planning to frequently work with containers, getting familiar with sh itself and how it differs to bash might be a good idea. Because you will only find a variant of sh on many containers.

**Comment by crschnick** [comment]
I guess this can be closed then
