### ISSUE TITLE
FR: Support for Xshell terminal

### ISSUE THREAD

**Issue by alexdelprete** [xpipe-io/xpipe#175]
Hi,

could you add support for NetSarang Xshell? https://netsarang.com/en/xshell/

I added it as a custom terminal, and used the test feature, it correctly opened a local session, so I guess it supports invoking it via CLI. It also supports opening new tabs vs new windows.

Thanks a lot. :)

**Comment by crschnick** [comment]
It's just that to properly open any arbitrary connection in a terminal or other program like xshell, xpipe needs to be able to call the program via its CLI and pass all relevant options. It usually does it by creating and passing a temporary script to be executed that will open the connection.

But since xshell does not support that, we kinda have to choose the second best option and call it differently, in this case by manually passing the connection information like username, host, etc. This is however not a very good solution as you have to enter any passwords, keys, etc. in xshell again when launched because we can't pass that information. It's better than nothing though.

If it would support the same level of CLI interaction as for example you can do with [Windows Terminal](https://apps.microsoft.com/detail/9N0DX20HK701?hl=en-US&gl=US), then I could add full support.

**Comment by alexdelprete** [comment]
> It's just that to properly open any arbitrary connection in a terminal or other program like xshell, xpipe needs to be able to call the program via its CLI and pass all relevant options. It usually does it by creating and passing a temporary script to be executed that will open the connection.

Well, Xshell supports session profiles (.xsh files) in which it stores all the info needed to connect to a server. It can also open all sessions files contained in a path.

![image](https://github.com/xpipe-io/xpipe/assets/7027842/de23fff4-57cc-4533-9dcb-04566fc62fef)

So the script you mentioned could actually be that session file, but it should be in .xsh format, I have to check if it is documented, or I can pass you an example so you can check if it contains all needed parameters used by Xpipe.

**Comment by alexdelprete** [comment]
See here: https://netsarang.atlassian.net/wiki/spaces/ENSUP/pages/419957436/Xshell+Command+Line+Option

![image](https://github.com/xpipe-io/xpipe/assets/7027842/2a34b4e6-80b8-4661-ab69-c09cf85344e1)

**Comment by crschnick** [comment]
So I think there are two options here:
- Generate a xsh by ourselves to dynamically launch any connection
- Find an already existing xsh file in the sessions dir that matches the hostname/port/user and then launch that

I think option two would make more sense

**Comment by alexdelprete** [comment]
> I think option two would make more sense

I initially discarded the second because it would mean maintaining a link in case they are renamed or deleted, etc.

How would xpipe link to the .xsh? by name of the server? Could work, but it means the user has to have them named in a specific way.

**Comment by crschnick** [comment]
I can just scan all the .xsh for a certain hostname that is used in the xpipe connection and then call xshell with the found .xsh.

I.e. we would scan all .xsh files to find one that contains `Host=<hostname>`

**Comment by alexdelprete** [comment]
Wouldn't that be slow? It's cool though, dynamic and tight integration. :)

**Comment by crschnick** [comment]
Not really in terms of other standards. Searching the files for a fixed string should be quick

**Comment by alexdelprete** [comment]
That's the best solution then.

Be aware that in the Sessions folder there could be subfolders.

This is my sessions folder:

![image](https://github.com/xpipe-io/xpipe/assets/7027842/8f7c57e7-f7c3-47f3-a82f-0cfe44c20ea6)

And this is how I navigate it in Xshell (simple and efficient way):

![image](https://github.com/xpipe-io/xpipe/assets/7027842/4731ee6b-e8e1-4e4d-be32-380e30b2c417)

**Comment by pixitha** [comment]
I found this thread while I was trying to setup XPipe and Xshell as well, from a normal windows terminal I can just type:

```
xshell $hostname
or
xshell $sessionname
```

Can the shell function in xpipe just pass the "name" from the xpipe config to xshell, so when you hit the shell icon it just sends "xshell $objectname"?

**Comment by crschnick** [comment]
Yeah I forgot about this issue somewhat and now my xshell trial is over. I would need to first purchase it to test it locally.

Just calling `xshell <name>` would be possible although a bit basic.

**Comment by alexdelprete** [comment]
> my xshell trial is over. I would need to first purchase it to test it locally.

there's the new open beta for v8. you could use that. I just installed it.

I agree that calling xshell with the hostname is a bit basic. your initial proposal is much better.

**Comment by pixitha** [comment]
Oh it's free for home personal use now, fyi.

https://www.xshell.com/en/free-for-home-school/

**Comment by alexdelprete** [comment]
> Oh it's free for home personal use now, fyi.

it was always free for personal use, it had a session limitation of 8 initially (or 10, can't quite remember) but they increased that last year.

**Comment by crschnick** [comment]
Well I guess it's up to interpretation if this constitutes personal use.

But the beta looks to be a good idea as that is not limited for personal use.

**Comment by crschnick** [comment]
My initial proposal was of course much more work. Just adding a button to launch xshell with the specified connection name is very easy. And if you keep track on keeping your connection names consistent, that would work

**Comment by alexdelprete** [comment]
So we can have the easy thing quickly? :)

**Comment by crschnick** [comment]
So this simple launch functionality is implemented in https://github.com/xpipe-io/xpipe-ptb now

**Comment by crschnick** [comment]
So I worked on this more to introduce a general solution for external clients like xshell, mobaxterm, termius, and others.

Right now it can start up a local SSH server that will connect to any connection in xpipe. It is working fine so far, but with xshell I can't get it to launch properly. I'm running `"C:\Program Files (x86)\NetSarang\Xshell 8\Xshell.exe" -url ssh://"Christopher Schnick"@localhost:21722 -i "C:\Users\Christopher Schnick\.xpipe\ssh_bridge\identity"` to connect to that local server but xshell always asks me for a nonexistent passphrase:
![image](https://github.com/user-attachments/assets/fc6acd3a-2a01-4364-811a-307f65f5a661)

If I add the connection manually in xshell it works fine.

**Comment by crschnick** [comment]
All right I think I managed to implement support for xshell the best I can in the latest PTB: https://github.com/xpipe-io/xpipe-ptb

**Comment by alexdelprete** [comment]
> Alright I think I managed to implement support for xshell the best I can in the latest PTB

Is there still the passphrase issue of previous post?

**Comment by crschnick** [comment]
No, I figured it out. Xshell uses their own key storage and format so I had to work around that. It seems like it does not accept file paths for openssh keys in that cli.

The idea now is that you have to add the key with the right name to Xshell manually once to link it to xpipe, but after that everything should work automatically.

**Comment by alexdelprete** [comment]
> The idea now is that you have to add the key with the right name to Xshell manually once to link it to xpipe

I just tested it, and it works.

Here's the steps:

1. launch/open Xshell's `Xagent` (xshell's ssh agent)
2. click on `Manage Keys`
3. Import the private key from `%USERPROFILE%\.xpipe-ptb\ssh_bridge\xpipe_ptb_bridge`
4. Xagent creates the corresponding private key (in NSSSH format) in its data folder

![image](https://github.com/user-attachments/assets/48523471-8829-4567-b9e5-560972f29649)

**Comment by alexdelprete** [comment]
> It seems like it does not accept file paths for openssh keys in that cli

I noticed that importing private keys the resulting key is in NSSSH format, I wonder if maybe it was just a matter of using that kind of key.

**Comment by crschnick** [comment]
I guess the xagent works too, I just added the key to xshell itself.

**Comment by alexdelprete** [comment]
Yes I think they do the same thing.

**Comment by crschnick** [comment]
Alright so can I mark this as completed? Or is there anything else?

**Comment by alexdelprete** [comment]
Not yet. Didn't test with xshell connections yet.

So, this version doesn't "integrate" with existing Xshell connection files right?

So, how do I create a connection through Xshell, from scratch? I just configure a new terminal?

**Comment by crschnick** [comment]
I interpreted your original issue as adding support to use xshell as a terminal in xpipe. Then that discussion moved towards calling xshell connections from xpipe, mainly because the cli did not support what I initially planned and that was the second best option. When this was implemented properly, I removed the launch xshell connection button again,

**Comment by crschnick** [comment]
Do you also want the button to launch an existing xshell connection with the same name from xpipe?

**Comment by alexdelprete** [comment]
My original request was to have integrated support for Xshell, recognizing the existing connections configuration files when scanning the local machine (like for docker for example).

Now if I understood correctly, you implemented a general way that works with other terminal apps, and in order to work you need to create a config keeping the name of the session consistent with the one configured in Xshell, is it correct?

It would be cool if during the scan of the machine you recognize the Xshell data folder with the config files and show the existing connections "automagically" like it happens with Docker etc.

If that's too difficult, an easy way to add an Xshell connection with the name parameter that reflects the config file.

Under the "Local Machine" main entry, there's docker, kubernetes, SSH, it would be great to also have a terminal section: Xshell (or whatever other app is supported) with the existing connections right below it. :)

**Comment by crschnick** [comment]
The thing with essentially importing connections from xshell is that the available data that xpipe can use differs from the one xshell uses. It won't be possible to just seamlessly use all xshell connections without any user effort. Because xpipe handles ssh connections completely differently internally.

That is why I added a button to open a connection in xshell with the same config name. But then I removed it because I liked the terminal integration more. But I can readd the button.

**Comment by alexdelprete** [comment]
I would simply use a different icon representing the terminal app, but I still can't understand how to add a new connection. For me it's not so intuitive it seems. :)

**Comment by crschnick** [comment]
I added the button again in the latest ptb to open a connection with the same name in xshell

**Comment by alexdelprete** [comment]
Can you explain how to add/use this button? Can't find how to add an existing xshell connection to the UI:

![image](https://github.com/user-attachments/assets/175ee9f0-1b64-4627-903c-345aafd2600e)

**Comment by crschnick** [comment]
There is a button here that will launch an xshell connection with the same name. If you keep your server names consistent with xshell, this should work properly:
![image](https://github.com/user-attachments/assets/62ff1187-e804-48d2-aca4-e092eb992d5c)

**Comment by alexdelprete** [comment]
> There is a button here that will launch an xshell connection with the same name

Can't find that submenu with "Open in Xshell", where should I click to open it?

**Comment by crschnick** [comment]
The latest PTB should show that menu when right clicking any ssh connection. The idea is that you will probably add the same connection in both xpipe and xshell with the same name.

**Comment by alexdelprete** [comment]
> The idea is that you will probably add the same connection in both xpipe and xshell with the same name.

Ok, got you.

Is the "Name" field in Xshell the one to be configured in xpipe's connection "Connection Name" field? I ask because it's not working. When I launch from xpipe it opens xshell, but not the connection. Maybe it doesn't support spaces in the name?

![image](https://github.com/user-attachments/assets/f7aed6df-1d23-48d9-a470-837b0de6d53c)

![image](https://github.com/user-attachments/assets/be260362-30c6-4046-918c-61aba3f3e09b)

**Comment by crschnick** [comment]
Does the command `xshell "RPi4 Argon"` work for you in the terminal?

**Comment by alexdelprete** [comment]
Ok, it's the spaces in the name, now it opens the connection, but it doesn't login using xshell's configured connection. it seems like it simply connects to the host using xshell executable, but doesn't leverage the already configured connection with the same name.

![image](https://github.com/user-attachments/assets/44582700-3778-425a-a334-0f3408b32f6e)

**Comment by alexdelprete** [comment]
> Does the command `xshell "RPi4 Argon"` work for you in the terminal?

Nope.

**Comment by crschnick** [comment]
Sadly both my shell 7 and xshell 8 don't start up anymore and I don't know why.

If you find a working command to launch a xshell connection with a name (ideally also with spaces) from the command line, I can just implement that. Because right now it just runs ` xshell "RPi4 Argon"`

**Comment by alexdelprete** [comment]
Running `xshell -?` from cmd I see this:

![image](https://github.com/user-attachments/assets/4837753f-de75-466a-82f4-7114e3192986)

**Comment by crschnick** [comment]
what is the `session_path`?

**Comment by alexdelprete** [comment]
Just found out: it's the path to the session file of the specific connection.

This works perfectly and connects to my RPi4: `xshell "d:\WinFolders\Documents\NetSarang Computer\8\Xshell\Sessions\Links\HomeLab\rpi4argon.xsh"`

**Comment by crschnick** [comment]
Is there a way to automatically determine the folder? It looks like in your case it is a custom location

**Comment by alexdelprete** [comment]
Since xpipe is developed in java, here's how to get the default Documents folder path for the user: https://stackoverflow.com/questions/9677692/getting-my-documents-path-in-java

Under that, you have always this path for sessions folder:
`DOCUMENTS_FOLDER\NetSarang Computer\8\Xshell\Sessions`

**Comment by crschnick** [comment]
So the the thing with recreating the tree in xpipe is that it is possible in theory but would require quite a bit of work only to have very limited functionality. Because many people would probably interpret this as being able to completely import and use xshell connections which isn't really the case here.

I fixed the launch xshell button to use the absolute path in the documents directory in the latest PTB just released. That should work now at least.

**Comment by crschnick** [comment]
I still don't see the added value of completely mirroring the xshell connection tree. Why not use xshell directly for that? That is why am currently focusing on a small convenience button to quickly launch xshell if needed.

Does the launch at least work correctly in the latest PTB now?

**Comment by alexdelprete** [comment]
> Does the launch at least work correctly in the latest PTB now?

Yes it does. Tested also with spaces in the name. Good job.

> I still don't see the added value of completely mirroring the xshell connection tree. Why not use xshell directly for that?

One of the things I liked about xpipe is the discovery mechanism for Docker, existing ssh user config connections, etc.: having xshell part of the same discovery process with connections automatically show in their own Xshell section would be really great. But it's your call, that's just a user opinion. In theory, if possible, I would expect the same thing for all terminal apps integration.

If you want to generalize the approach: when creating an SSH connection, let user choose depending on which terminal app he set in the options, and adapt the configurable options to the specific app. Right now I have to create a dummy ssh user connection specifying None to authentication/key/etc. just to have a shortcut for the right-click "Open in Xshell". Not really clean/elegant, IMHO, and it requires maintenance on the user side when you change connections in Xshell.

**Comment by pixitha** [comment]
For me, it would make the most sense if xpipe could just call xshell like it works in a terminal or command prompt. I can just type `xshell $hostname` and it just opens xshell and connects just fine, including using my existing ssh keys?

**Comment by alexdelprete** [comment]
> I can just type `xshell $hostname` into terminal and it just opens xshell and connects just fine, including using my existing ssh keys?

It can't work like that: xshell has its own keys and configuration, it doesn't use OpenSSH keys, agent, etc.

**Comment by pixitha** [comment]
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\Kyle> xshell llm
```

Doing this in powershell/terminal opens xshell and connects me to my existing server, via DNS hostname, which xshell already has a ssh key setup for, so it autoconnects and everything. So why can't xpipe send this type of command ?

(my network has hostname/dns suffix configured, so I don't need the whole FQDN)

**Comment by alexdelprete** [comment]
If you check last 10-15 posts we have been discussing all this, and you'll see that xshell supports this from CLI:

![image](https://github.com/user-attachments/assets/4837753f-de75-466a-82f4-7114e3192986)

So tell me, in xshell you have a preconfigured llm.xsh containing key/password and other config options for that host? 

Can you please check if you have a session file called llm.xsh in `YOURDOCUMENTFOLDER\NetSarang Computer\8\Xshell\Sessions`?

Another test: xshell 192.168.5.1 (where the ip is the one for llm), does it work without asking for pw/key or whatever?

**Comment by crschnick** [comment]
I think I need to elaborate on a few things here. Xshell is a competitor of xpipe and my main goal is developing a project that is arguably better and has more features than xshell. Looking at the detailed features of xshell, I think xpipe can match almost all features now while also providing many that xshell doesn't have. Obviously it will never be perfect, everything is subjective, and for some users xshell might still be the better option if it comes to specific features. One of the main things that makes switching more difficult is the inherent inertia of switching to something new and the fact that xshell has a vendor lock-in with their proprietary key formats and other things. So the main goal here is to make migration easier.

The terminal launcher support for xshell is for users who migrated from xshell but still like the actual terminal features of xshell and maybe have a lot of things customized there which would make switching to another terminal difficult. The button to open a session file is intended to allow users who migrated from xshell to still quickly open a connection in xshell if they still need it for some reason. I would call them migration helpers more than actual features. Also if xshell's CLI wasn't lacking so much functionality, this implementation would have been much easier and better.

Being able to specify the exact terminal for every SSH connection might be useful in some cases like this, but I don't think it would be worth it to introduce another configuration option for that. If you create dummy connections just to launch xshell, I don't see why you have to create them in the first place. I mean you could just use xshell directly for that. That button is intended for cases when you have added the same connection to both xpipe and xshell.

If both the terminal launcher and the button to open a specific connection by name in xshell work, I would consider this as completed considering the circumstances.

**Comment by crschnick** [comment]
If there is any feature you would like to see in xpipe that prevents you fully from switching from xshell, feel free to open a feature request. I consider all feature requests.

But it is not the long term goal to fully integrate with xshell, the goal is to allow for a smooth migration considering the limitations of xshell's proprietary nature.

**Comment by alexdelprete** [comment]
> Xshell is a competitor of xpipe and my main goal is developing a project that is arguably better and has more features than xshell. Looking at the detailed features of xshell, I think xpipe can match almost all features now while also providing many that xshell doesn't have.

glad that you cleared this out. IMHO, I don't see Xshell as a competitor of xpipe, because I don't see xpipe as a full-blown terminal app like xshell, securecrt, etc. maybe I'm missing something, but the configuration options for a terminal session I see in those apps are not in xpipe yet.

I see xpipe like a sort of central hub for remote connections of various types: vnc, rdp, ssh, etc. but I don't see right now xpipe being the best app for each of those single domains. I hope it will become so, but that's not my perception right now. So for telnet/ssh/serial, I'll keep using xshell, even though I'd like to have xpipe as a central point of management of all connections.

Maybe I might be missing something, i just wanted to express my feeling as a user, and I thank you very much for the support and the fact you're open to discuss with users about xpipe developement, it shows you care about users, and that's an excellent thing.

**Comment by crschnick** [comment]
I would categorize Xshell as an SSH client with an integrated terminal. Up until now, pretty much all SSH clients had their own integrated terminal. But due to recent developments, e.g. the introduction of Windows Terminal and other terminals for Windows, XPipe was created without an integrated terminal. Because I would argue you can get a better experience with a dedicated terminal like Windows Terminal in combination with xpipe than something integrated as in xshell or others. Also makes my development life easier. Now I know that this might be subjective, but if you look forward into the future, every improvement that tools like Windows Terminal will receive over the years, also improve the overall user experience in combination with xpipe.

The same goes with other things like RDP and also X11-forwarding for SSH as you get with xmanager. XPipe can launch RDP connections by using the native Microsoft tooling for that and can X11-forward on Windows by using WSL as a native X11 server. So xpipe is also trying to create better solutions for graphical connections with more modern approaches than xmanager.

For serial, XPipe 11 will introduce serial support. This will take a while until it is stable as it is not really tested yet. So it will be more of a community effort by crowdtesting it. But once it is, serial should also be covered by XPipe.
And for others like telnet, you can create a feature request for that if you would like to see that. Because that could be implemented similar to the serial support.

But yeah in general it is the plan to improve the various features such that it is the best tool for the job.
Xshell and others are much older than xpipe, so there is some catching up to do in terms of development time.

**Comment by crschnick** [comment]
This is now released in XPipe 11: https://github.com/xpipe-io/xpipe/releases/

Feel free to report any issues if it does not work as expected.
