### ISSUE TITLE
Flatpak version of Wezterm not working with shell redirection.

### ISSUE THREAD

**Issue by ikidd** [xpipe-io/xpipe#177]
Command to run if Flatpak version installed is `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=wezterm org.wezfurlong.wezterm start --cwd .`

**Comment by crschnick** [comment]
Yeah that is true, the default implementation is not looking for a flatpak version of an application. I will have to see whether it is possible to add support for that.

Meanwhile, you can launch it manually like this:
![image](https://github.com/xpipe-io/xpipe/assets/72509152/4333d892-2b62-43c9-b18a-cd4bed11a4d4)

I just entered `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=wezterm org.wezfurlong.wezterm start` into the custom command.

**Comment by ikidd** [comment]
Sounds good, I'll use it that way for now.

**Comment by crschnick** [comment]
I experimented with support for flatpak applications and that is quiet cumbersome to implement. For now, I think this workaround will work fine.

Especially since almost no one uses flatpak terminals due to sandboxing issues, this should be acceptable.
