### ISSUE TITLE
Feature Request: Session Launch UI Tweaks

### ISSUE THREAD

**Issue by surfrock66** [xpipe-io/xpipe#178]
I am requesting several (hopefully) minor UI tweaks to allow session browsing and launching to have a slightly smoother workflow.  Coming from other tools like mRemoteNG, there is a very convenient workflow where from 1 pane with very minimal clicks you can launch the sessions you want from the sidebar.  Currently in xpipe, there is the following:

1) No sidebar view in the connections pane, so connections are listed in a tall bar and must be expanded to click, taking up a lot of vertical real estate.  As such, choosing a specific connection is a bit clunky.
2) The browser pane is a much better UI for having lots of connections, but still choosing non-default connections requires an extra click (either expanding the sidebar entry, or launching the file browser and clicking the terminal option.

My proposal would be to enable "tagging" connections to show up in small badge buttons in the sidebar of the Browser pane, possibly something like this:
![image](https://github.com/xpipe-io/xpipe/assets/1345467/6dfb07f6-7d9b-437b-bcb3-68f8dc46de07)

I say allow tagging as, for example, 3 shells show up in a default Ubuntu Install, but I only use Bash and wouldn't want them all in the sidebar.  If a far future feature like embedded terminal ever came into play, it would make the workflow for navigating connections much smoother.  A similar enhancement would allow those tagged connections to show up as additional buttons here in the connections pane:

![image](https://github.com/xpipe-io/xpipe/assets/1345467/ed4a0ad8-ca25-4f33-825f-965d3931d818)

**Comment by crschnick** [comment]
So I think in general, the main point is that the UI does not work very well when it comes to managing many connections as there is a lot of scolling and clicking involved.

I think I can add a condensed display mode for the connection overview where every connection would take up less vertical space, that can be done pretty easily.

The added buttons in the file browser sidebar make sense, but I'm not sure how well that would look like if I added buttons to everything. Would a right click context menu also work here? That way I can also put in more actions.

The tagging is an interesting idea, I have to experiment a bit on how to realize that the best way.

**Comment by crschnick** [comment]
So this is how the condensed mode would look like
![image](https://github.com/xpipe-io/xpipe/assets/72509152/9b34a68c-568e-45f3-9da0-a5e22a706961)

**Comment by crschnick** [comment]
So I implemented my solution to your request in https://github.com/xpipe-io/xpipe/releases/tag/8.2

Essentially, instead of tagging individual connections, there is now a context menu available to open connections without expanding. This should drastically reduce they required amount of expanding connections and scrolling.

I will close this issue for now, but you can share feedback here of what you think.
