### ISSUE TITLE
Windows version does not sync up with Git

### ISSUE THREAD

**Issue by rainrdx** [xpipe-io/xpipe#182]
Hi,

I was traveling for a quite and always used the mac version and the git syncs up very fine. But somehow the windows version, which I just returned to, does not sync us. It will still pull updates from Git, but it does not upstream anymore.

I tried uninstall xpipe and delete the entire .xpipe folder. Resync, and it pulls from Git very well. When I add a server (to a syncing category), nothing happens on Git. I can still close and reopen xpipe but just nothing syncs.

Regards,
Rick Shang

**Comment by crschnick** [comment]
Hmm, if it's pulling successfully that eliminates already a lot of potential causes.

For debugging, is this a general issue or repo specific? I.e. if you create a temporary test repository, maybe push a few connections from mac, does that also happen to not push from windows?

I assume that you using the latest version 1.7.16.

**Comment by rainrdx** [comment]
I have been using 1.7.16 but the same happened to 1.7.15. I just moved recently so I won’t be able to use my computer in the day. I will update you with more debugging information later today. Thank you!!

**Comment by crschnick** [comment]
I think someone else had a similar problem but I was unable to diagnose it, so this might not be an isolated issue.

For debugging, I think the only thing that you would need to do is start it up in debug mode, create a new connection in a category that is set to be shared, close xpipe, and send me the log somewhere.

**Comment by rainrdx** [comment]
Thank you. I turned on debug mode and turned out I did not set up global user name/email. Anyways user error and sorry about that. However, it is weird that when I choose restart in debug mode in the app, it will flash the prompt that this starts in debug mode, etc. and the app quits. I have to manually double click the .bat file to run the app in debug mode...

**Comment by crschnick** [comment]
Wait there is an error printed but there is no error popup in xpipe? There should be one if git is not configured correctly to push.

With regards to the debug mode, there might be a race condition. I have to test that.

**Comment by rainrdx** [comment]
> Wait there is an error printed but there is no error popup in xpipe? There should be one if git is not configured correctly to push.
> 
> With regards to the debug mode, there might be a race condition. I have to test that.

Correct. There is an error printed out but no error popup in xpipe. Thank you always for working on this.

**Comment by crschnick** [comment]
In the debug log, it should tell you with what exit code the git command that complained about missing user/email finished. If that returned 0 for you, I might have to adapt the handling of errors.

**Comment by rainrdx** [comment]
> In the debug log, it should tell you with what exit code the git command that complained about missing user/email finished. If that returned 0 for you, I might have to adapt the handling of errors.

Sorry I am heading out to work now so I will try to get it to you tonight. Always thank you for working on this.

**Comment by rainrdx** [comment]
This is the relevant part I believe:

`20:03:57:549 - trace: [proc] Read: 128END
20:03:57:549 - trace: [proc] Read stderr {
    output=
    | Author identity unknown
    |
    | *** Please tell me who you are.
    |
    | Run
    |
    |   git config --global user.email "you@example.com"
    |   git config --global user.name "Your Name"
    |
    | to set your account's default identity.
    | Omit --global to set the identity only in this repository.
    |
    | fatal: unable to auto-detect email address (got 'rdx@DESKTOP-7I2V6AD.(none)')
}
20:03:57:549 - info: [proc] Command finished {
    command=git commit -m "Update data" >NUL
    finishReason=NORMAL_FINISH
    exitCode=128
}`

**Comment by crschnick** [comment]
Ohh it is the commit that fails. I should be able to fix that

**Comment by rainrdx** [comment]
Thank you!!

**Comment by TSJasonH** [comment]
I just did a test of setting up xpipe on my Windows 10 machine and it only pulled part of my git repo, and also will not push changes back. Works fine from my linux machines.

**Comment by crschnick** [comment]
Does this happen even when you manually set the git author identity via ```
git config --global user.email "[you@example.com](mailto:you@example.com)"
git config --global user.name "Your Name"
```?

This issue should also be fixed by the way in https://github.com/xpipe-io/xpipe-ptb/releases/tag/8.0-3 as it should properly throw an error when the author identity isn't set.

**Comment by TSJasonH** [comment]
Ah yes, setting my global args seems to have resolved it. Thanks!

**Comment by crschnick** [comment]
This is now fixed in the latest release
