### ISSUE TITLE
Update did not succeed

### ISSUE THREAD

**Issue by RedVelocity** [xpipe-io/xpipe#184]
I'm unable to update the app from version 1.7.15 to 1.7.16 on Windows 11.

The installation window pops up and disappears in a few seconds. Relaunching the app starts up with "Update did not succeed" error. 

There's nothing in "show details" to debug this.

![image](https://github.com/xpipe-io/xpipe/assets/14160702/d7383118-8021-4ba7-ad41-41d667f2a9bd)

**Comment by crschnick** [comment]
That is actually a known issue and should be fixed in https://github.com/xpipe-io/xpipe/releases/tag/1.7.16. Now to update you have to do it manually. Just downloading the msi and installing it should work. There's no need to uninstall the old version.
