### ISSUE TITLE
Powershell on MacOS ?

### ISSUE THREAD

**Issue by heinowalther** [xpipe-io/xpipe#185]
Hi there

I am trying to add Powershell installed on MacOS.... but xPipe does not find it...
It is listed under avaliable shells, and I can start it with /opt/homebrew/opt/powershell/bin/pwsh
But how do I get it added as an option in xPipe?

**Comment by crschnick** [comment]
Yeah PowerShell on non-Windows systems is currently not supported.

I might add support for it in the future if it is not too complicated. It hasn't been added until now because I have not met someone yet who used PowerShell on Linux or macOS.

**Comment by crschnick** [comment]
How were you able to select PowerShell for your system? Anything that is not supported should not be selectable

**Comment by heinowalther** [comment]
![Screenshot 2024-02-01 at 15 05 26](https://github.com/xpipe-io/xpipe/assets/6001138/ea0daca8-b454-41d0-8324-6a88a5170d87)

**Comment by heinowalther** [comment]
Oh sorry, that was just a screenshot where I try to setup a new Powershell connection in the MacOS GUI...  So under Connections, I select "New Shell Environment..."

**Comment by crschnick** [comment]
Oh I see with the shell environments. I thought it was added automatically.

Yeah that might be an oversight, although we would have to verify what shells exist on the target system and what OS it is. Or that solution is not perfect. What I can do is throw an error when you select an unsupported combination and try to connect.

**Comment by heinowalther** [comment]
I would rather that it was possible to just add your own shell which was just "/opt/homebrew/opt/powershell/bin/pwsh" ;-)
It is listed in "/etc/shells"...

**Comment by crschnick** [comment]
Adding the shell is not the problem, the problem is that xpipe has to know how to talk to the shell. And since there are various differences between Windows and non-Windows powershell versions, it needs to be adapted. Otherwise half the features won't work

**Comment by heinowalther** [comment]
...I was able to add it as a Custom Command...  works for me :-)

**Comment by crschnick** [comment]
As a custom terminal command or custom shell opener command?

**Comment by heinowalther** [comment]
![Screenshot 2024-02-01 at 15 23 04](https://github.com/xpipe-io/xpipe/assets/6001138/abad43b3-4f5d-4e17-916f-75e88e493a96)

**Comment by crschnick** [comment]
Oh yeah sure that will just run any command in a terminal. In terms of proper support, I was talking more about using PowerShell as a proper shell environment that you can also use in the file browser for example.

**Comment by heinowalther** [comment]
Yeah that would be nice, if nothing else, than to just execute PS scripts via the filebrowser...

**Comment by crschnick** [comment]
I will have to experiment myself how much work is actually needed for that.

**Comment by crschnick** [comment]
This is now supported in 8.4
