### ISSUE TITLE
Update did not succeed

### ISSUE THREAD

**Issue by ldurand-it** [xpipe-io/xpipe#186]
![image](https://github.com/xpipe-io/xpipe/assets/123183205/fca1135f-1213-4e27-9c34-32d0cad1845e)

**Comment by crschnick** [comment]
That is actually a known issue in the Windows version and should be fixed in https://github.com/xpipe-io/xpipe/releases/tag/1.7.16. Now to update you have to do it manually. Just downloading the msi and installing it should work. There's no need to uninstall the old version.

**Comment by crschnick** [comment]
Alright nevermind it is probably not fixed yet. I will see what I can do to properly fix this in one of the next releases.

**Comment by vluz** [comment]
8.0.1 giving me same screen as above.

I've installed from build msi and it messed up connections.
Connections would not launch, asked for passwords and ultimately flash a terminal window and close.

Had to uninstall and revert to 1.7.16, all worked again.

Subscribing to this issue, to keep track.
Happy to answer any debug questions.

**Comment by crschnick** [comment]
This should be fixed now in 8.1 onwards. Sadly updating from a previous version will not work due to the updater being broken in older versions.

About the messed up connections, do you use the git synchronization?

**Comment by vluz** [comment]
I'm sorry, no I'm not but I should.
I just restored from a backup.
I use it at home on very small homelab, connections don't change for weeks or moths.

**Comment by crschnick** [comment]
I mainly asked because I was only aware of data corruption issues when using the git synchronization across multiple systems while upgrading.

Can you elaborate on the issues you were facing? If I understand correctly, the issue was mainly with the terminal not launching correctly anymore? Did other things work, e.g. the file browser?

**Comment by vluz** [comment]
After upgrade it asked me for su password but not user password for one of the connections.
After giving correct password the powershell windows would just flash and close.
Could not read any text as it was fast, it was the same for other non root connections to same server.

At the time I was working with a friend and had him waiting so I just restored from last night backup.

I can certainly try again, maybe I did something wrong.

In sequence these were the events:
1 - Open XPipe for the first time in that day.
2 - Had update so I did it, got screen above.
3 - Got a screen just like the one posted above.
4 - Clicked ignore error, came to repo and downloaded the msi for 8.0.1
5 - Installed ok, open and try to open one of the connections (friend was on the phone call now)
6 - Got asked for su password, entered it, it's shamefully not very complex.
7 - PS window open and closed
8 - Clicked on another connection, PS window flashed.
9 - Closed everything and open backup software, restore program and data dir from backup.

All worked and I could continue the call.

Again I might have pressed something wrong or any other mistake the I don't recall.
As soon as I have some free time I'll upgrade again.

**Comment by vluz** [comment]
> Out of curiosity, does your Windows username contains spaces?
I never do usernames with spaces, a practice from old days where it had all kinds of troubles.
Usernames are for me always one word, no spaces or underscores, not starting with numbers, no special chars.

I'm ok with testing live as I've got multiple working backups, can always revert in seconds.
I used to be a storage/backup guy, some practices stayed on.

**Comment by crschnick** [comment]
Ok so if that's not it, I would try with different terminals in the settings menu. Maybe it's something specific to powershell. Ideally I would recommend Windows Terminal if you don't have anything besides cmd and powershell installed.

**Comment by crschnick** [comment]
I fixed several issues with terminal launching in https://github.com/xpipe-io/xpipe/releases/tag/8.2. I also changed the launcher script to pause if an unexpected error occurs, so the terminal shouldn't close even if it errors out.

**Comment by crschnick** [comment]
Closing this as everything relating to this should be fixed
