### ISSUE TITLE
Rootless Docker

### ISSUE THREAD

**Issue by LGXerxes** [xpipe-io/xpipe#188]
:heart: Super nice program :heart: 

Reading the release notes I saw that you had encountered permissions issues on the docker socket.

But it seems to only try this on `unix:///var/run/docker.sock`, whereas if you install docker with rootless the docker socket is usually located at: `unix:///run/user/{UID}/docker.sock`

Perhaps I'm compleatly wrong, but as far as a I see it doesn't recognize docker containers which are not the "sudo docker" or default DOCKER_SOCKET.

Would be nice if you could set which docker socket should be used.

![image](https://github.com/xpipe-io/xpipe/assets/68999840/e1ddd038-8fcc-4114-a1ce-7aa4af778538)
container ran with sudo docker ^

user docker has 10 containers up

**Comment by crschnick** [comment]
I'm not super familiar with rootless docker setups, bud if XPipe would respect the `DOCKER_SOCK` variable, this issue would be fixed?

**Comment by LGXerxes** [comment]
> I'm not super familiar with rootless docker setups, but if XPipe would respect the `DOCKER_SOCKET` variable, this issue would be fixed?

The convention from the [docker manual](https://docs.docker.com/engine/security/rootless/#install) is to export `DOCKER_HOST`. 
I haven't seen `DOCKER_SOCKET` being used as an environment variable, usually when you need to enter it manually the socket path is given.

**Comment by crschnick** [comment]
Alright thanks for the link, that should be doable

**Comment by crschnick** [comment]
This is now implemented in xpipe 10
