### ISSUE TITLE
Xpipe does not scale properly in my 2560x1600 monitor

### ISSUE THREAD

**Issue by QuakeString** [xpipe-io/xpipe#189]
I'm using latest version of Xpiple in my Manjaro Linux KDE

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.12
Kernel Version: 6.6.10-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 12 × 12th Gen Intel® Core™ i5-12450H
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: TIMI
Product Name: Xiaomi NoteBook Pro

Xpipe not scalled properly.

here is the photo of comparison.
![image](https://github.com/xpipe-io/xpipe/assets/5375918/377b8a00-9e08-46c5-8e02-28d4b7bbd231)
![image](https://github.com/xpipe-io/xpipe/assets/5375918/428e0d02-fcdb-4e62-8ae1-2ceecf6c3db5)

**Comment by crschnick** [comment]
This is a known issue and will be fixed in the next 1.8 release.

In the meanwhile, you should be able to work around this issue by launching xpipe with `/opt/xpipe/app/bin/xpiped -Dglass.gtk.uiScale=1.5` or any other scale factor.

**Comment by crschnick** [comment]
A fix for this is now available in testing: https://github.com/xpipe-io/xpipe-ptb

**Comment by crschnick** [comment]
A fix for this is now released through a separate settings option.
