### ISSUE TITLE
Not Starting / Opening When System Startup Behavior is "Start in tray" + Close Behavior is "Minimize to tray"

### ISSUE THREAD

**Issue by yottoya** [xpipe-io/xpipe#191]
Operating System: 
- MacOS M1 arm64 16GB

Installation Method:
- Homebrew

Issue:

I downloaded xpipe on Windows and loved it.

So, I downloaded it on my Mac with Homebrew, and I just happened to change the settings in System for the Startup Behavior to be "Start in tray" and the Close Behavior to "Minimize to tray", and then when I closed xpipe, and restarted my computer, xpipe would show as having been started but every time I click the app, it wouldn't show the window.

So, to resolve this, I quite xpipe, made a back of `~/.xpipe`, and then re-opened xpipe to see if clearing this folder from my home directory would relaunch it and display the window and it did.

Note: I later went back to test if "Start in tray" and "Minimize to tray" work fine, and they do. So, no issues there.

Just wanted to bring this to your attention and for anyone else that might experience this. I can try to recreate the problem and show you via video if needed.

Thanks!
![Screenshot 2024-02-13 at 4 19 56 PM](https://github.com/xpipe-io/xpipe/assets/91698935/0dd536ec-4781-4841-a5dc-37891caa0a92)

**Comment by crschnick** [comment]
Hmm, so it didn't show up in the system tray for you like this initially?
![Screenshot 2024-02-14 at 08 31 36](https://github.com/xpipe-io/xpipe/assets/72509152/56a08ea0-b1cf-457a-88e3-464342ca025e)

But when you went back to test later, it suddenly does now?

**Comment by crschnick** [comment]
So I tried everything to reproduce this, but everything worked as expected.

Yeah if you're able to reproduce this, maybe with a video, that would be great. Also, the log file for the session in which it does not start in `~/.xpipe/logs` would be very helpful

**Comment by yottoya** [comment]
Hey @crschnick - Sorry, I'm such a noob... I didn't notice xpipe's icon on my mac's status bar at the top, and that in order to re-open xpipe, I need to click that. Since it is a dark logo, I didn't notice until I looked closer.

Sorry! Noob mistake

**Comment by crschnick** [comment]
So this has motivated me to look into other options. I think we can achieve more macOS specific behavior by not using any system status bar icons and instead you utilizing the dock as most other applications do it.

I will implement that in the next release.

**Comment by yottoya** [comment]
That could the way to mitigate confusion in the future!

But also, is it not possible to change the color of the xpipe icon to white when In dark mode? I think the tray feature is nice (because I also use windows, it's nice that windows apps have system tray options).

**Comment by crschnick** [comment]
Yeah technically the color can also be adapted, but I just went ahead and reworked the tray handling by using the dock now

**Comment by crschnick** [comment]
If you're interested in trying it out, the reworked dock support is in testing at https://github.com/xpipe-io/xpipe-ptb
