### ISSUE TITLE
MacOS: Stay running when windows closed

### ISSUE THREAD

**Issue by MitchTalmadge** [xpipe-io/xpipe#193]
Hey there! Love XPipe so far. I use it on both Windows and MacOS. When closing the window on MacOS, I would like to request an option to keep the app alive in the background, but not within the tray area. Most apps in MacOS act in this way by default where closing all the windows does not actually close the application. It's a different design philosophy from Windows where apps exist apart from the window, and a window is just "one part" of an app. It makes it so that opening the window is very fast. 

For example, if I close my Spotify window, the music keeps playing even though there are no windows open and Spotify is not in the menu bar (tray area). Instead, there's a dot underneath the Spotify icon on my dock: 
![image](https://github.com/xpipe-io/xpipe/assets/8848080/58b63b19-4f10-4a00-9dbb-3ad345669adf)

This indicates that Spotify is still running, just with no windows open. When I click on the Spotify icon, it opens a window very quickly because it doesn't have to do any of the startup work it would normally do.

What do you think?

**Comment by crschnick** [comment]
That is very convenient timing, I just implemented this one hour ago: https://github.com/xpipe-io/xpipe/commit/7bf5ef8afa4346ef41d12c8fd56fb751dd02345d

This will be included in the next release.

**Comment by MitchTalmadge** [comment]
Wow lol how about that. Thanks so much! You're awesome :)

**Comment by MitchTalmadge** [comment]
@crschnick I just played with the beta and it works great! This is exactly how I hoped it would be. You rock!
