### ISSUE TITLE
Show loading indicator while connecting to host

### ISSUE THREAD

**Issue by MitchTalmadge** [xpipe-io/xpipe#194]
Hiya! I would like to suggest adding some sort of loading indicator after clicking on a host while it is connecting and preparing to open a terminal. Right now there is no indication and if a host is slow to respond it can look like nothing happened, resulting in "retry clicks" and eventually multiple windows popping up.

Thanks!

**Comment by crschnick** [comment]
That problem has been addressed in XPipe 1.8 by changing how the terminal launch works., This is currently in testing at https://github.com/xpipe-io/xpipe-ptb

The latest build there also contains the macos tray rework if you're interested.

**Comment by crschnick** [comment]
This is now released
