### ISSUE TITLE
username to be optional in ssh records

### ISSUE THREAD

**Issue by tolgaulas** [xpipe-io/xpipe#196]
Pls provide the option 
 - not to store/choose the username because we don't use it as we use local key files + session-agent.
  and / or
 - not to store it in git since it shows in git, for team usage this may break up things when every user in team environment

**Comment by crschnick** [comment]
Alright yeah the customized SSH connection type is best made for this. 

Does that also solve the localized jumpboxes you mentioned? Because I wasn't 100% sure what exactly you meant by that, so you can elaborate on that if you want
