### ISSUE TITLE
"find available connection" to be optional at new ssh connection 

### ISSUE THREAD

**Issue by tolgaulas** [xpipe-io/xpipe#197]
When adding a lot records, the "find available connection" which is a button on the record and can be (re)run when needed, makes operation slow when we don't add any, but barebone connection. 

If you can make this discovery at creation an option, so those who want to skip that part at record creation can perform faster.

**Comment by crschnick** [comment]
Alright I see, that is a good idea.

**Comment by crschnick** [comment]
This is now implemented in https://github.com/xpipe-io/xpipe-ptb/releases/tag/8.0-9

**Comment by crschnick** [comment]
This is now released
