### ISSUE TITLE
XPipe does not parse extra SSH config options like RemoteCommand

### ISSUE THREAD

**Issue by xbufu** [xpipe-io/xpipe#206]
I am trying to have XPipe execute a command after it establishes connection or have it forward the agent, but it seems like the options from the SSH config just get ignored.

## SSH config

```
Host test
  HostName 192.168.70.2
  User root
  Port 22
  RemoteCommand tmux a || tmux
  ForwardAgent yes
  ForwardX11 yes
  RequestTTY yes
  TCPKeepAlive yes
```

## Expected Behavior

Executing the ssh command manually executes the command and launches a tmux session in the remote host if one does not exist already.

![image](https://github.com/xpipe-io/xpipe/assets/49696158/7a761b69-46fd-4c4d-b4e0-f0097e117b5b)

![image](https://github.com/xpipe-io/xpipe/assets/49696158/82de38f3-9f9b-4cd3-8dde-e28fcc2e1643)

## Actual Behavior

XPipe ignores the extra options and no command is executed. The issues occurs on both the latest release and public test builds.

![image](https://github.com/xpipe-io/xpipe/assets/49696158/9a96d0e4-8e79-4202-884b-6a5cd34cd485)

Command that XPipe will execute from *Insights*:

```
ssh "Invalid" -oStrictHostKeyChecking=accept-new -oRemoteCommand=none -oNoHostAuthenticationForLocalhost=yes -t -F "<temp config>"
```

![image](https://github.com/xpipe-io/xpipe/assets/49696158/e6b143a5-58ab-42fa-900a-85dfc9ed07d1)

**Comment by crschnick** [comment]
That is actually intentional. The RemoteCommand attribute is incompatible with any other commands passed inline, e.g. `ssh user@host bash` will not work when RemoteCommand is specified. That is why it executes `-oRemoteCommand=none`.

If you want to run a certain init command, you can use shell environments and/or scripts.

**Comment by xbufu** [comment]
Ah interesting, I did not know that. Is it the same for the other options like `ForwardAgent`?

**Comment by crschnick** [comment]
It should not touch any other options besides RemoteCommand

**Comment by xbufu** [comment]
Perfect, thank you! :)

**Comment by crschnick** [comment]
So I guess if everything else except the remote command works as expected, this can be closed.
