### ISSUE TITLE
[ERR] java.lang.IllegalStateException: Shell self-test failed for zsh:

### ISSUE THREAD

**Issue by decisivedevops** [xpipe-io/xpipe#208]
OS - macOS Sonoma 14.2.1 (23C71)
Device - Apple M1 Pro
XPipe version - 8.4

Getting this error on startup -

---

java.lang.IllegalStateException: Shell self-test failed for zsh:

This indicates that something is seriously wrong and certain shell functionality will not work as expected.

The most likely causes are:
- On Windows, an AntiVirus program might block required programs and commands
- The system shell is restricted or blocked

You can try to switch to the fallback shell by going to Settings -> Local Shell -> Enable Fallback Shell and restart.

---

java.lang.IllegalStateException: Shell self-test failed for zsh:

This indicates that something is seriously wrong and certain shell functionality will not work as expected.

The most likely causes are:
- On Windows, an AntiVirus program might block required programs and commands
- The system shell is restricted or blocked

You can try to switch to the fallback shell by going to Settings -> Local Shell -> Enable Fallback Shell and restart.

at io.xpipe.app.core.check.AppShellCheck.check(AppShellCheck.java:33)
at io.xpipe.app.core.mode.BaseMode.onSwitchTo(BaseMode.java:54)
at io.xpipe.app.core.mode.OperationMode.set(OperationMode.java:357)
at io.xpipe.app.core.mode.OperationMode.switchToSyncOrThrow(OperationMode.java:191)
at io.xpipe.app.launcher.LauncherCommand.call(LauncherCommand.java:148)
at io.xpipe.app.launcher.LauncherCommand.call(LauncherCommand.java:28)
at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
at picocli.CommandLine.access$1500(CommandLine.java:148)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
at picocli.CommandLine.execute(CommandLine.java:2170)
at io.xpipe.app.launcher.LauncherCommand.runLauncher(LauncherCommand.java:72)
at io.xpipe.app.core.mode.OperationMode.init(OperationMode.java:128)
at io.xpipe.app.Main.main(Main.java:22)
![CleanShot 2024-03-18 at 11 38 57](https://github.com/xpipe-io/xpipe/assets/95153836/9b5ccdc1-e30a-4444-9aed-5b978910d498)

**Comment by decisivedevops** [comment]
hey. yes, zsh is working correctly.



> Also, you can try going to Settings -> Local Shell -> Enable Fallback Shell and restart XPipe, that should use another shell. Maybe that will work.

is this done in XPipe settings? if yes, I cant seem to get to the settings itself. it gives me above error right when I open the app.

**Comment by crschnick** [comment]
Hmm so in theory it should continue to start up after that error message, but I can imagine that something else goes wrong when the shell integration does not work as expected. This is not really a case I accounted for.

What you can do is run the following script: `/Applications/XPipe.app/Contents/Resources/script/xpiped_debug.sh`. This will print out all commands it tries to run with the exit code. Some of the early commands must fail in your case. Maybe we can see what went wrong there.

**Comment by crschnick** [comment]
Ok so it seems to fail here:

```
20:03:34:636 - info: Starting command execution ... {
    baseCommand=cat << '05742545-f8f0-470c-9d49-519e7f3775aa' > '/var/folders/l7/fszgdtgj23d2nm72h2js_5f40000gn/T/exec-419538915.sh' && chmod 700 '/var/folders/l7/fszgdtgj23d2nm72h2js_5f40000gn/T/exec-419538915.sh'
    shellType=zsh
    elevated=false
    workingDirectory=null
}
20:03:34:636 - trace: Writing line {
    line=echo '779a1947-a4bd-4a75-8b7a-65ecae0e21d1';echo '6da21e9c-45d5-447e-b919-42f6586e09c1' 1>&2;cat << '05742545-f8f0-470c-9d49-519e7f3775aa' > '/var/folders/l7/fszgdtgj23d2nm72h2js_5f40000gn/T/exec-419538915.sh' && chmod 700 '/var/folders/l7/fszgdtgj23d2nm72h2js_5f40000gn/T/exec-419538915.sh';echo 'fa3f0e2e-3a7f-4d0c-9489-990721235c95'${?}END;echo 'e5650822-2ff1-4cc9-8d5c-c76f756ecbec' 1>&2
}
20:03:34:636 - trace: Writing line {
    line=
    | #!/usr/bin/env zsh
    | echo test
    | 05742545-f8f0-470c-9d49-519e7f3775aa
}
20:03:39:638 - info: Command finished {
    command=cat << '05742545-f8f0-470c-9d49-519e7f3775aa' > '/var/folders/l7/fszgdtgj23d2nm72h2js_5f40000gn/T/exec-419538915.sh' && chmod 700 '/var/folders/l7/fszgdtgj23d2nm72h2js_5f40000gn/T/exec-419538915.sh'
    finishReason=START_TIMEOUT
    exitCode=162
}
20:03:39:638 - trace: Stderr finished {
    finishReason=START_TIMEOUT
}
```

when we are trying to create the temporary script file. 

You can manually enable the fallback shell by either creating or modifying the file `~/.xpipe/settings/preferences.json` and inserting or changing the following value:

```
{
  "useLocalFallbackShell" : true
}
```

**Comment by decisivedevops** [comment]
thanks. after creating and updating `~/.xpipe/settings/preferences.json`, app worked.

**Comment by decisivedevops** [comment]
thanks. after creating and updating `~/.xpipe/settings/preferences.json`, app worked.

**Comment by crschnick** [comment]
Interesting, so something it did not work with zsh while the same works with sh here.

I will try to better handle these cases so users can automatically switch to the fallback shell without having to edit files.
