### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by freedbygrace** [xpipe-io/xpipe#209]
Amazing software! I totally will be supporting this project by purchasing.

I wanted to know if there are any plans to make this software something like a web based docker container? Almost like a guacamole alternative?! That would be amazing to have functionality like this from anywhere and any web broswer.

**Comment by crschnick** [comment]
So there was a discussion about this a while ago in #86, and the main hurdle was how to interact with other programs. E.g. if you launch a terminal connection from the web interface, you could not open a locally running terminal program. So it would have to implement a web-based terminal, which is some work. The same goes for text editors etc. Overall I currently save a lot of development time by just calling other programs.

So something like this would be technically possible, but it would require a lot of work to properly realize.

**Comment by crschnick** [comment]
I marked the referenced issue as help wanted, so maybe someone will come around. You can watch #86  issue to get notified about any updates.
