### ISSUE TITLE
Problem with xpipe / windows 11 

### ISSUE THREAD

**Issue by DrTableBasse** [xpipe-io/xpipe#217]
Hello,

When i want to start an ssh, docker whatever directly from xpipe i got this error 

[erreur 2147942402 (0x80070002) lors du lancement de `C:\Users\ARES\AppData\Local\Temp\exec-1700329468.bat']
(yeah it's french sorry)

I really dont understand why i have it because à my job i dont have this error but i have the same setup...

**Comment by crschnick** [comment]
Where is this error shown? In XPipe or in the terminal?

I would assume that there is some issue with cmd, maybe it is blocked by some antivirus or policy? You can go to the xpipe settings -> Local shell -> Enable fallback shell and restart to see whether it makes a difference.

**Comment by DrTableBasse** [comment]
Ok that was a Windows issue lmao...

So basically on Windows 11 23H2, if you have this error, just reinstall the update to 23H2.

This problem is kinda weird :-/ but i found a "solution" i guess.



I close this issue thx chris !
