### ISSUE TITLE
Features : Bookmarks and treeview

### ISSUE THREAD

**Issue by frankbret** [xpipe-io/xpipe#218]
Excellent software but could help to navigate faster to use a treeview on the left, like Windows Explorer, with multiple expanded folders to switch from one to another...
And also, a bookmark system wher we could remember the directories where things were left, ex. /usr/local/etc/php/conf.d/
thank you !

**Comment by crschnick** [comment]
Alright these are good points, I will see what I can do

**Comment by crschnick** [comment]
So I added a new quick access button to directories in 8.6. It's no persistent tree view, but should make navigation faster

**Comment by crschnick** [comment]
I think this can now be closed as the quick access menu has been reworked and improved. It should now be a good replacement for classical tree views
