### ISSUE TITLE
Add extra upload functionality

### ISSUE THREAD

**Issue by legoraft** [xpipe-io/xpipe#219]
When the upload jumps to 1 GB, there are no decimal numbers anymore, even though the total upload does have a decimal number. I would like to be able to see this if possible

I would also like to see the upload speed, currently I need to guess how long an upload will take, so having the speed there would be great if possible.

**Comment by crschnick** [comment]
The decimal numbers for GB will be an easy fix and included in the next release.

For the upload speed I have to see when I get that done, it is surprisingly difficult to get the time estimation right without it jumping all over the place.

**Comment by crschnick** [comment]
So the decimal upload progress should be fixed in 8.6

**Comment by legoraft** [comment]
great, which tool are you using for the upload? Because scp does have a speed thingy in there

**Comment by crschnick** [comment]
It does not use any specialized tool for file transfers, they are transferred manually.

I can definitely come up with a proper timer, it will just take a little bit of time and experimentation.
