### ISSUE TITLE
Add ability to open multiple tabs in kitty terminal - Linux

### ISSUE THREAD

**Issue by Punkado** [xpipe-io/xpipe#221]
Would be great to have the possibility to have multiple tabs in kitty, on Linux, or even in any other terminal on Linux, like Alacritty. 

As far as i tested, only Terminator have this function working.

**Comment by crschnick** [comment]
The reason this is not supported by xpipe is that these terminals do not support opening new tabs from their CLI. If any terminal has added that ability since the last time I checked, it can easily be implemented.

If I see correctly, you can only open new tabs in kitty via a keyboard shortcut, not a commandline option for example.

**Comment by Punkado** [comment]
In Tilix, for example, you can use "tilix -e" to open in a new sidebar ( is also possible to set tabs instead of sidebar, in the preferences)

**Comment by crschnick** [comment]
We already call tilix with -e: https://github.com/xpipe-io/xpipe/blob/3f01bb0028ab9976e7d06d657e5769dc945c7936/app/src/main/java/io/xpipe/app/terminal/ExternalTerminalType.java#L287

**Comment by kovidgoyal** [comment]
> If I see correctly, you can only open new tabs in kitty via a keyboard shortcut, not a commandline option for example.

Sure, you can

```
kitty --session <(echo 'new_tab\nlaunch\nnew_tab\nlaunch')
```

And in existing kitty instances via remote control: https://sw.kovidgoyal.net/kitty/remote-control/

**Comment by crschnick** [comment]
Oh that is good to know, I wasn't aware that you can do this. Let me try what I can do here

**Comment by crschnick** [comment]
Alright I was able to make a proper kitty integration with tabs work via the remote control. That will then be included in the next release.

@kovidgoyal is it possible to start a new kitty instance without any tabs open? Right now I manually close the first default tab that automatically opens when opening a new kitty window.

**Comment by kovidgoyal** [comment]
On Tue, Apr 02, 2024 at 09:31:06PM -0700, Christopher Schnick wrote:
> Alright I was able to make a proper kitty integration with tabs work via the remote control. That will then be included in the next release.
>
> @kovidgoyal is it possible to start a new kitty instance without any tabs open? Right now I manually close the first default tab that automatically opens when opening a new kitty window.

Opening kitty without arguments opens a single window, and no extra
tabs.

**Comment by crschnick** [comment]
Yes but that window starts up with one tab open running the default shell. I was wondering whether it would be possible to open a blank kitty window with 0 tabs open, i.e. without a shell session. In my use case I pass the command I want to open via remote control right after the window has opened. I mean it's not super important as I can just close the default tab via remote control as well, but would be convenient.

**Comment by kovidgoyal** [comment]
On Wed, Apr 03, 2024 at 12:07:37AM -0700, Christopher Schnick wrote:
> Yes but that window starts up with one tab open running the default shell. I was wondering whether it would be possible to open a blank kitty window with 0 tabs open, i.e. without a shell session. In my use case I pass the command I want to open via remote control right after the window has opened. I mean it's not super important as I can just close the default tab via remote control as well, but would be convenient.

If you are starting kitty from the command line you dont need remote
control, use a startup session. Or if you really want to use remote
control, use

kitty --session <(echo "launch --allow-remote-control path_to_you_remote_control_script)

This will create a window, which will close automatically after your
script exits, so you dont need to close it in your script and you dont
need to enable remote control globally.

**Comment by crschnick** [comment]
Alright thanks for the help, that should work

**Comment by crschnick** [comment]
This is now implemented in 9.0
