### ISSUE TITLE
Unable to download files with ' in the filename

### ISSUE THREAD

**Issue by rainrdx** [xpipe-io/xpipe#222]
Hi,

I am using XPipe 8.6 for windows. Whenever I have files with ' in the file name, the download would be stuck. Also it would be nice to have ways to pause or stop an ongoing download if this kind of situation happens. Thank you!

**Comment by crschnick** [comment]
Oh well, seems like I forgot to properly escape the file for the download command because that was redone recently. Will be fixed

**Comment by crschnick** [comment]
This should now be fixed in XPipe 9 at https://github.com/xpipe-io/xpipe-ptb

**Comment by crschnick** [comment]
This is now fixed in 9.0
