### ISSUE TITLE
homebrew cask no longer works

### ISSUE THREAD

**Issue by rainrdx** [xpipe-io/xpipe#223]
Hi,

for whatever reasons seems the brew cask is not available anymore after 8.6. I tried two different computers on two different networks, but the same error:

`brew install --cask xpipe-io/tap/xpipe
Warning: Cask 'xpipe' is unreadable: wrong number of arguments (given 1, expected 0)
==> Searching for similarly named casks...
Error: Cask 'xpipe' is unavailable: No Cask with this name exists.`

**Comment by crschnick** [comment]
Whoops this is now fixed. In 8.6 I added a dependency but used the wrong syntax for casks.
