### ISSUE TITLE
custom script naming convention

### ISSUE THREAD

**Issue by trickiegt** [xpipe-io/xpipe#226]
Trying out your software today - very nice!
Found an issue when naming a custom script with a '/' -- causes connecting to a shell to crash -- cant find script

Made a simple script that does apt-update and apt-upgrade -y ... called it update / upgrade
Enabled Bring to all compatible shells
Attempt connect to shell and get the following error

Process returned exit code 1:
-bash: line 20: /tmp/xpipe/root/scripts/bash/update_/_upgrade.sh: No such file or directory

renaming the file to update-and-upgrade fixes the error, just bringing it to your attention

**Comment by crschnick** [comment]
Whoops, yeah seems like I forgot about that part. I was primarily focused on escaping all characters properly that I didn't replace any file system incompatible ones. Will be fixed in the next release

**Comment by crschnick** [comment]
This is now fixed in 9.0
