### ISSUE TITLE
[REQUEST] Danish translation 🇩🇰

### ISSUE THREAD

**Issue by tacaly** [xpipe-io/xpipe#234]
I'd really like to have xpipe in danish. 
As per the documentation, I've requested it here.
(https://github.com/xpipe-io/xpipe/blob/master/lang/README.md)

lang code: da_dk / da
🇩🇰

**Comment by tacaly** [comment]
Saw the commit: https://github.com/xpipe-io/xpipe/commit/8a822b1f4cc877cb5af99a0b7020f46ab73479a1

I'll start to correct the files. Thanks 😊 @crschnick

**Comment by crschnick** [comment]
You can wait until a PTB build is available for that, then you can also see it in action. That makes it much easier as otherwise you don't have a lot of context for many strings

**Comment by tacaly** [comment]
I'll wait for the PTB then.

**Comment by crschnick** [comment]
You can try this: https://github.com/xpipe-io/xpipe-ptb/releases/tag/9.0-9
