### ISSUE TITLE
SSH Tunnel fails to connect when using ssh config from WSL2

### ISSUE THREAD

**Issue by sonst-was** [xpipe-io/xpipe#236]
Hi,

as already discussed in discord, I have the following setup:

-> Win11
--> WSL2
---> Ubuntu
----> SSH User Config
-----> server01
------> ssh tunnel

When trying to activate the ssh tunnel I get the following error message:
```
Shell opener command was unsuccessful:
Can't open user config file \\home\\user\\.ssh\\config: No such file or directory
```

Debug logs below:
[xpipe_debuglogs.txt](https://github.com/xpipe-io/xpipe/files/15093346/xpipe_debuglogs.txt)

**Comment by crschnick** [comment]
Fixed in 9.0
