### ISSUE TITLE
No matching key exchange

### ISSUE THREAD

**Issue by ALEXRUZI** [xpipe-io/xpipe#239]
Shell opener command was unsuccessful:
Unable to negotiate with 10.1.99.20 port 22: no matching key exchange method found. Their offer: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1

![xpipe_err](https://github.com/xpipe-io/xpipe/assets/16401335/50280dda-5649-46ca-87dd-7ba878868993)

In other SSH clients it works fine.

**Comment by crschnick** [comment]
Hmm, xpipe just calls your locally installed `ssh` client. If you click on edit for the SSH connection, on the bottom left there should be an insights button that tells you what command is getting executed.

Is there any kind of special configuration you use in your user SSH config?

**Comment by ALEXRUZI** [comment]
> Hmm, xpipe just calls your locally installed `ssh` client. If you click on edit for the SSH connection, on the bottom left there should be an insights button that tells you what command is getting executed.
> 
> Is there any kind of special configuration you use in your user SSH config?

ssh "admin@10.1.99.20" -p 22 -oStrictHostKeyChecking=accept-new -oRemoteCommand=none -oNoHostAuthenticationForLocalhost=yes -T

**Comment by crschnick** [comment]
Does that run if you paste it into a terminal?

**Comment by crschnick** [comment]
You should also be able to fix this by creating a custom connection that supports one of these key exchanges like this

![image](https://github.com/xpipe-io/xpipe/assets/72509152/fb10d97a-aa44-478d-bfc0-b3426f2d83e5)

**Comment by ALEXRUZI** [comment]
> You should also be able to fix this by creating a custom connection that supports one of these key exchanges like this
> 
> ![image](https://private-user-images.githubusercontent.com/72509152/326203014-fb10d97a-aa44-478d-bfc0-b3426f2d83e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNDQ5OTIsIm5iZiI6MTcxNDI0NDY5MiwicGF0aCI6Ii83MjUwOTE1Mi8zMjYyMDMwMTQtZmIxMGQ5N2EtYWE0NC00NzhkLWJmYzAtYjM0MjZmMmQ4M2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDE5MDQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZTA3ZTJiZjI4YWJkMWM5NjA4ZjViM2NlMWM1NmQ4YWQ0OTFjMDkxMjc2MGRmYmNkZDZhZjJjODQ3YjE5YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p8I3HWFQED0QipTFkdXBTJu9q5dgaUQ-kZ4hguMBKMs)

Thanks, this worked. And yeah I was also getting the same problem with the Win Terminal app. Also added HostKeyAlgorithms = +ssh-rsa to work.
