### ISSUE TITLE
UI modal clipped bug in XFCE

### ISSUE THREAD

**Issue by rizkyzhang** [xpipe-io/xpipe#246]
I found an issue with modal clipping on MX Linux 23.2 XFCE, I have updated xpipe to 9.1 latest version and it still persist, it likely to be only affecting XFCE, I have tested it on ubuntu 22.04 and it's fine.

![modal-bug](https://github.com/xpipe-io/xpipe/assets/41568558/e8693c58-ba5f-40ed-aabe-02f908fe5131)

**Comment by crschnick** [comment]
Yes this is a known JavaFX issue in xfce and i3. It will hopefully be fixed upstream soon, then I can include the fix as well.

**Comment by paradoxos** [comment]
is there any temporary fix we can try?

**Comment by crschnick** [comment]
This is now fixed in https://github.com/xpipe-io/xpipe/releases/tag/9.3
