### ISSUE TITLE
Enabled Pro Preview but a feature is greyed

### ISSUE THREAD

**Issue by meska** [xpipe-io/xpipe#250]
Hello, 
I enabled the Pro preview, because I will probably buy it , but I found this:

<img width="368" alt="image" src="https://github.com/xpipe-io/xpipe/assets/276923/5bd5f8dd-4d6c-4b6e-9fa6-07b31682d491">

does it nee the full license or is a feature not still enabled ?

**Comment by meska** [comment]
It's ok, I will buy it anyway, I find it very useful specially the containers management

**Comment by tacaly** [comment]
> It's ok, I will buy it anyway, I find it very useful specially the containers management

**Cool** @meska 😃 
I'll go ahead and close this issue, due to it being resolved by buying the "PRO" edition. Please don’t hesitate to contact us with any concerns.
