### ISSUE TITLE
First sync

### ISSUE THREAD

**Issue by meska** [xpipe-io/xpipe#251]
I installed xPipe on one Mac, configured git sync, later installed it on a second Mac, after enabling sync on the second newly installed Mac it failed because the fetch could not update the local repo due to files already present.
So I had to delete them first by hand from the shell and then relaunch xPipe as there is no function available to overwrite the local repository.

**Comment by crschnick** [comment]
A possible merge conflict is expected, but you should get something like this
![image](https://github.com/xpipe-io/xpipe/assets/72509152/1d3b13ee-d71e-46fe-8e63-cef1987e05d6)
with a few options to automatically resolve the conflict. Did that not happen for you?

**Comment by meska** [comment]
I have instead this:
<img width="621" alt="image" src="https://github.com/xpipe-io/xpipe/assets/276923/79267746-034b-4d94-aaa7-5e1ef34e5c9e">

<img width="307" alt="image" src="https://github.com/xpipe-io/xpipe/assets/276923/1652374b-4ec7-4168-9c19-80d877754fe0">

**Comment by crschnick** [comment]
Oh that is due to it not being in english, it currently only checks the error messages of git to determine what kind of error occurred. I might have to find an alternative here

**Comment by crschnick** [comment]
On the second mac, if you go into the storage directory and delete everything, including the .git, it should work.

**Comment by meska** [comment]
> On the second mac, if you go into the storage directory and delete everything, including the .git, it should work.

Yes, in the end that's what I did and now it works.

**Comment by crschnick** [comment]
That will be fixed in the next release

**Comment by tacaly** [comment]
Fixed in release version 9.2: https://github.com/xpipe-io/xpipe/releases/tag/9.2
