### ISSUE TITLE
[macOS] Getting jave exception when trying to launch ssh connection

### ISSUE THREAD

**Issue by TonyBostonTB** [xpipe-io/xpipe#253]
The error I get is
`java.io.IOException: Unable to launch terminal Kitty: Process returned exit code 1`
That is, I've got a popup first where I had to allow access to something which I did not allow. Now I believe this is related to XPipe being able to start kitty terminal but I'm not sure how to get asked again and give permissions.

**Comment by tacaly** [comment]
> The error I get is `java.io.IOException: Unable to launch terminal Kitty: Process returned exit code 1` That is, I've got a popup first where I had to allow access to something which I did not allow. Now I believe this is related to XPipe being able to start kitty terminal but I'm not sure how to get asked again and give permissions.

Got some things for you to try ☺️

Please test the terminal via XPipe -> Settings -> Terminal -> Press "Test". 

**Common MacOS Kitty issue:**
Check your privacy settings, specifically “Full Disk Access.” Add Kitty if it’s not already in there. If it’s already there try removing it and re-adding it. Sometimes it helps closing the terminal via the dock and reopen it.

Alternatively you can re-install the terminal.
https://sw.kovidgoyal.net/kitty/binary/

**Comment by TonyBostonTB** [comment]
Alright, Full Disk Access fixed it. I guess there should be an option within Xpipe to trigger that Permission setting again, right?

**Comment by crschnick** [comment]
That is a macOS thing, I don't think we can do that (probably for security reasons). I'm pretty sure you would have the same behavior with other apps as well.

**Comment by TonyBostonTB** [comment]
I meant to "trigger the request for Full Disk Access", not to set that permission. I know there are Apps that can do that, especially remote desktop apps. 
Maybe the following link sheds some light on it https://forums.developer.apple.com/forums/thread/107546

**Comment by crschnick** [comment]
The problem I see here is that xpipe it doesn't even know whether we already have full disk access. And according to threads like https://forums.developer.apple.com/forums/thread/114452?page=2 there is no easy way to determine that.
