### ISSUE TITLE
Strange WM_CLASS(STRING)

### ISSUE THREAD

**Issue by Gor-ets** [xpipe-io/xpipe#261]
Could you change WM_CLASS(STRING) to normal? Xpipe, for example.

![image_2024-05-08_22-44-33](https://github.com/xpipe-io/xpipe/assets/164275518/744500d8-909c-47c3-b5ef-6fba09d5c37b)

**Comment by Gor-ets** [comment]
I have other apps, only this has so strange name)

![image](https://github.com/xpipe-io/xpipe/assets/164275518/1d984388-492d-4745-8d0c-c73d6971826e)

**Comment by crschnick** [comment]
We already do that actually, but I think this was broken in 9.1 accidentally

**Comment by crschnick** [comment]
Also for you screenshot it looks like you're using a hdpi screen. There is a scaling options in the xpipe settings in that case if the text is otherwise too small for you.

**Comment by tacaly** [comment]
Added in: https://github.com/xpipe-io/xpipe/commit/05884660d7c6aaf19c6d5cf17907aa1daddd3723

**Comment by tacaly** [comment]
The fix has been released.
