### ISSUE TITLE
Tabby reports issue when connecting to Calix Router

### ISSUE THREAD

**Issue by isag33k** [xpipe-io/xpipe#264]
When attempting to connect to our Calix core router using Tabby, I receive the following error:

An error occurred: io.xpipe.core.process.ProcessOutputException: Process did not start up properly and had to be killed:
Shell did not respond on stderr within timeout interval. Does it have an stderr allocated?

XPipe requires the connection to provide a separate working stderr. Some connections, e.g. one that always allocate a tty/pty, merge all output into stdout only. If possible, try to make the connection not allocate a tty/pty or somehow fix other stderr issues.

I thought maybe I needed the Pro license, so I bought it . No issues there since Xpipe is a great product, but it did not resolve the issue. Any ideas on anything I can do on my side to work around this or is this something our network admin needs to change on the device side?

**Comment by crschnick** [comment]
Did you enable the option `Don't interact with system` for the SSH connection? This option is made for these systems that do not provide fully fledged shell connections

**Comment by isag33k** [comment]
Thank you! That has indeed resolved the issue. I appreciate the quick response as well! I am loving XPipe. Consolodating my connection and migrated from Termius.
