### ISSUE TITLE
Cannot sync through git repo in v9.2 on Mac

### ISSUE THREAD

**Issue by Phanquan** [xpipe-io/xpipe#268]
I installed v9.2 on my macbook with macos 14, intel chip, and got this error when trying to config Sync in the new v9.2, while the same config works correctly on v1.7.13

My configs are:
- Setup git repo for sync (private git repo)
- Used ssh key for auth (added to github ssh key setting)
- Provided passphase to perform git command

Then got this error:
```
Process returned exit code 128:
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
```

**Comment by Phanquan** [comment]
> Where does the X11R6 askpass come from? Do you have some X11 implementation installed on your system?
> 
> One way I can see this error happening is that your system has something set in the git config. You can inspect that with `git config --list`. Alternatively, there is some environment variable set such as `GIT_ASKPASS ` or `SSH_ASKPASS`.
> 
> Depending on what causes this, I can make the implementation more robust to these external influences. But this does not look like an xpipe problem by itself.

Well neither of them shows up, and I use the default SSH key for git actions, and "git@github.com:" for git repo.

And with those configs of mine show that error whenever I startup v9.2, then I uninstall v9.2 without deleting the data folder, reinstall v1.7 then xpipe runs correctly without further config.

**Comment by crschnick** [comment]
Alright so I tried to reproduce this issue on my mac.

The only way I can reproduce it is by setting `export SSH_ASKPASS=...`. The current implementation does not override that variable but it should do that ideally. I will fix this in the next release.

I think the problem in your case is that the key has a passphrase and it somehow uses an invalid askpass program. You can try opening a terminal session, set `export SSH_ASKPASS="/Applications/XPipe.app/Contents/MacOS/xpipe"`, and launch xpipe from there with `xpipe open`. That will apply the environment

**Comment by Phanquan** [comment]
Yup that fix the issue but reopen still get the bug.

**Comment by crschnick** [comment]
Yeah you would have to do that for every launch for now. This will be fixed in 9.3.

**Comment by Phanquan** [comment]
Atm, i will switch to use personal access token instead of ssh key

**Comment by crschnick** [comment]
This should now be fixed in https://github.com/xpipe-io/xpipe/releases/tag/9.3
