### ISSUE TITLE
Download speed release v9.3 xpipe-installer-linux-x86_64.deb is very slow

### ISSUE THREAD

**Issue by rizkyzhang** [xpipe-io/xpipe#271]
I just tried to download the specified deb version and the speed is only 40-50 kbps. I tried other version like arm64 type and v9.2, the download speed is fine. I am not sure if this is on my end because the other version is fine.

**Comment by rizkyzhang** [comment]
I see, it could be because of optimization, will try again later.

**Comment by crschnick** [comment]
Does it work now?

**Comment by rizkyzhang** [comment]
Sorry just see your reply, it is completely fine now, thank you so much for the update!
