### ISSUE TITLE
Enhancement: probe all connections in a group

### ISSUE THREAD

**Issue by coandco** [xpipe-io/xpipe#278]
I manage a fleet of 39 servers and keep all of their info in my SSH user config.  If I want to see at a glance which OSes the servers run, it's a laborious manual process of clicking on each of the servers one by one to force XPipe to probe them and store the OS data.  It'd be nice to have an action to probe all the servers in a category automatically, perhaps as one of the actions in the three-dots menu of the SSH User Config subheading.

![image](https://github.com/xpipe-io/xpipe/assets/6173436/675958e3-076f-4d15-891a-a324d052a5f1)

**Comment by crschnick** [comment]
So the thing is with these multi-system actions that the user usually wants to do more than just that. I also got an request to have the ability to run scripts on multiple systems.

XPipe 10 will come with an http api that would allow performing any actions from for example a scripting language of your choice. For the current status, you can find the openapi spec at https://github.com/xpipe-io/xpipe/blob/release-10.0/openapi.yaml.

When thinking about the future, I have two options:
- Build this probe ability into the GUI, which can become fairly complex at some point
- Refer to the http api. While obviously this is a little bit more difficult to get started with, it's more suited towards use cases where you want to systematically interact with many systems in xpipe

You can share your thoughts about which option would be more suited for your use cases.

**Comment by coandco** [comment]
Having an HTTP API would solve basically all my problems.  I can easily write quick automations to fix stuff up the way I want it, and the openapi spec will allow for easy generation of a Python module to interact with it.

**Comment by crschnick** [comment]
Alright, you can stay tuned for the public test build release of XPipe 10. That should hopefully happen soon
