### ISSUE TITLE
detection of macOS Warp.app config but without corresponding app

### ISSUE THREAD

**Issue by fragmede** [xpipe-io/xpipe#279]
Hi,

Warp is a macOS terminal app. I installed it and used it sometime in the past, but then stopped using it, but xpipe picked that up somewhere and tried to use it as a default on my system despite it no longer being installed on my system. I had to go into settings -> terminal and set that to the one I actually use to make xpipe work.

**Comment by crschnick** [comment]
Yeah it only performs the installation detection on first launch right now. I can fix that in the next release

**Comment by crschnick** [comment]
This is now fixed in xpipe 10
