### ISSUE TITLE
Title Bar color

### ISSUE THREAD

**Issue by julianbrennum** [xpipe-io/xpipe#281]
When running the software in darkmode on windows the title bar is still white. It does not follow the software's darkmode or windows theme. Would be nice if it would follow the windows theme or if it changed to black when the app is in dark mode.

![image](https://github.com/xpipe-io/xpipe/assets/9699246/e4428a23-8003-46ce-926f-389e8a6c02d6)

**Comment by crschnick** [comment]
Yeah that is a current limitation of JavaFX. I'm not sure whether I can implement that myself through a native call or whether I have to wait for JavaFX to officially support it.

**Comment by julianbrennum** [comment]
> Yeah that is a current limitation of JavaFX. I'm not sure whether I can implement that myself through a native call or whether I have to wait for JavaFX to officially support it.

I see, what about hiding the title bar and create a custom title bar within your JavaFX, effectively hiding the default system title bar and creating your own inside the app? By using undecorated style you can make the title bar follow the app's design language.

**Comment by crschnick** [comment]
Alright found a solution to this. If you are on Windows 11, you can try out the test build at https://github.com/xpipe-io/xpipe-ptb. I am primarily on Windows 10.

**Comment by julianbrennum** [comment]
Yes, it works perfectly! Running on W11. Great work, and thanks for the fast respond!

**Comment by julianbrennum** [comment]
Case closed, problem solved!
