### ISSUE TITLE
OpenAPI spec has minor validation errors

### ISSUE THREAD

**Issue by coandco** [xpipe-io/xpipe#283]
I'm trying to make a Python module off of the XPipe OpenAPI spec using https://github.com/openapi-generators/openapi-python-client, and it's complaining that the keys need to be strings instead of numeric (e.g. [this line](https://github.com/xpipe-io/xpipe/blob/9090c128e90249d5258c57729573cf4ad4a28bfd/openapi.yaml#L61)).  You can see that in the [official OpenAPI examples](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/api-with-examples.yaml#L11), numeric return codes are quoted so the YAML parser doesn't interpret them as numbers.

**Comment by crschnick** [comment]
I guess I can fix that but I checked with multiple openapi editors and they didn't complain about that. Is there anything else it complains about?

**Comment by crschnick** [comment]
So I fixed that even though it's a little bit weird that it complained in the first place
