### ISSUE TITLE
Renaming Folder Error: 'Target [foldername] does already exist' when substituting small letters for capitals

### ISSUE THREAD

**Issue by appiekap653** [xpipe-io/xpipe#287]
When you rename an existing folder name, leave the same name but change a letter from a small to a capital, it gives the error: 'Target [foldername] does already exist'

I had the error while using the File browser on a Windows machine, running Xpipe on the same Windows machine. 

Xpipe version: 10.0 community

to reproduce:

1. open Xpipe.
2. go to file browser.
3. open local machine file browser.
4. right click a folder.
5. click rename.
6. change an existing small letter to the same capital letter.
7. press enter.

**Comment by crschnick** [comment]
Yeah I see what goes wrong, I will have to think about how to fix it the best way.

**Comment by crschnick** [comment]
This is fixed in the latest release
