### ISSUE TITLE
ssh-agent doesn't work in Arch with Xpipe

### ISSUE THREAD

**Issue by Gor-ets** [xpipe-io/xpipe#296]
Hi) Could you help, please? I have installed and configured the ssh agent, ssh-agent gets ssh private keys from KeePassXC and then I am able to use them in my OS (in cli/xpipe/etc). I am able to use secrets from ssh-agent in cli and I connected to my host, but it doesn't work via Xpipe.

![image_2024-07-07_15-27-06](https://github.com/xpipe-io/xpipe/assets/164275518/611d6f78-3122-4f64-a872-d100cd680606)
![image_2024-07-07_15-27-06 (3)](https://github.com/xpipe-io/xpipe/assets/164275518/3670ec9e-5bfd-4ab9-bac8-60dc31b7a123)
![image_2024-07-07_15-27-06 (2)](https://github.com/xpipe-io/xpipe/assets/164275518/541ae227-4dee-4a90-8c83-ef48b997c490)

**Comment by crschnick** [comment]
Did you start xpipe with the SSH_AUTH_SOCK variable in its environment? You can try to run `xpipe open` in a terminal session where the variable is set.

Since this is in zsh, is zsh also your login shell?

**Comment by Gor-ets** [comment]
Oh, it's really works very strange) I open xpipe via sxhkd and it doesn't work: "Unable to fetch..."
```
# xpipe
alt + x
  xpipe open
```

But if I open it via cli, it works)

About zsh, I use only him, I don't have bash/other shells. I login via sddm

**Comment by crschnick** [comment]
If it works from a terminal, then your rc file configuration might not be applied when launching desktop applications.

Does your .zprofile or .zlogin source your .zshrc file?

**Comment by Gor-ets** [comment]
But I don't have .zprofile and .zlogin, I have only .zshrc and .alias_zsh, 

.zshrc:
```
#!/usr/bin/sh

export PATH=$HOME/.bin:$HOME/.config/rofi/scripts:$HOME/.local/bin:/usr/local/bin:$PATH
export HISTFILE=~/.zhistory
export HISTSIZE=10000
export SAVEHIST=10000
export TERM="xterm-256color"
export XDG_CONFIG_HOME="$HOME/.config"
export _JAVA_AWT_WM_NONREPARENTING=1
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

ZSH="/usr/share/oh-my-zsh"
ZSH_THEME="af-magic"
DISABLE_AUTO_UPDATE="true"
ZSH_DISABLE_COMPFIX=true
plugins=()
ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh

[[ ! -d $ZSH_CACHE_DIR ]] && mkdir -p $ZSH_CACHE_DIR
source $ZSH/oh-my-zsh.sh
source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

if [ $TILIX_ID ]  [ $VTE_VERSION ]; then
  source /etc/profile.d/vte.sh
fi

export EDITOR="$([[ -n $DISPLAY && $(command -v subl3) ]] && echo 'subl3'  echo 'nvim')"
export BROWSER="librewolf"

[[ -e "/usr/share/fzf/fzf-extras.zsh" ]] && source /usr/share/fzf/fzf-extras.zsh
export FZF_DEFAULT_COMMAND="fd --type file --color=always --follow --hidden --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS="--height 50% --layout=reverse --border --preview 'file {}' --preview-window down:1"
export FZF_COMPLETION_TRIGGER="~~"

[[ -f ~/.alias_zsh ]] && . ~/.alias_zsh
```

.xinitrc:
```
#!/bin/sh

usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

xset b off

# xset +fp /usr/share/fonts/local &
# xset +fp /usr/share/fonts/artwiz-fonts &
# xset +fp /usr/share/fonts/misc &
# xset +fp /usr/share/fonts/bitmap &
# xset +fp ~/.fonts &
# xset fp rehash &
# fc-cache -fv &

exec bspwm
```

**Comment by Gor-ets** [comment]
And I launched KeePassXC via sxhkd and it works without any issues)

**Comment by Senderman** [comment]
The problem here is that you launch SXHKD in environment where `SSH_AUTH_SOCK` variable is not defined, and you lauch your terminal emulator app where `SSH_AUTH_SOCK` is defined. The best practice is to define and calculate your user's global environment variables in `~/.zprofile` file, while leaving ZSH plugins and aliases initialization in `~/.zshrc` file. 
With this approach, if ZSH is defined as your login shell (see `/etc/passwd` file and `chsh` command), your user will always receive environment variables defined in `~/.zprofile`.

**Comment by Gor-ets** [comment]
thank you) I moved export `SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket" `to `~/.zprofile` and it works)
