### ISSUE TITLE
xpipe fails to launch when switching user

### ISSUE THREAD

**Issue by billmeyertpft** [xpipe-io/xpipe#298]
On Linux desktop (Kubuntu), installed xpipe on two workstations, both have same issue. 
When logging into different user xpipe don't start up. Only works for user that was used during installation.

**Comment by crschnick** [comment]
I think I see what goes wrong, some temporary files are not deleted / have the wrong permissions.

You should be able to fix that temporarily by cleaning /tmp or restarting. This will be fixed properly in the next release.

**Comment by crschnick** [comment]
This is now fixed in 10.1. Note that this will only apply once the temp directory is clean, otherwise old files from the previous version might still break it
