### ISSUE TITLE
Crash When Uploading File on a Server

### ISSUE THREAD

**Issue by Syrent** [xpipe-io/xpipe#299]
When I try to upload a file to any server, XPipe disconnects me from the SFTP window after the upload is completed, and I receive the error `Wait for process exit timed out`.

**Error details:**
```
io.xpipe.core.process.ProcessOutputException: Wait for process exit timed out
    at io.xpipe.core.process.ProcessOutputException.of(ProcessOutputException.java:53)
    at io.xpipe.ext.proc.c.close(SourceFile:107)
    at io.xpipe.ext.proc.dialect.e$1.close(SourceFile:279)
    at io.xpipe.ext.proc.a$2.close(SourceFile:120)
    at io.xpipe.app.browser.file.BrowserFileTransferOperation.handleSingleAcrossFileSystems(BrowserFileTransferOperation.java:263)
    at io.xpipe.app.browser.file.BrowserFileTransferOperation.execute(BrowserFileTransferOperation.java:127)
    at io.xpipe.app.browser.fs.OpenFileSystemModel.lambda$dropFilesIntoAsync$15(OpenFileSystemModel.java:376)
    at io.xpipe.app.util.BooleanScope.executeExclusive(BooleanScope.java:18)
    at io.xpipe.app.browser.fs.OpenFileSystemModel.lambda$dropFilesIntoAsync$16(OpenFileSystemModel.java:369)
    at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$1(ThreadHelper.java:42)
    at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)
    at java.lang.VirtualThread.run(VirtualThread.java:309)
```
![image](https://github.com/user-attachments/assets/c1a6d4b4-55f4-4d8c-bfd5-ad2a6e5d6e55)

**System details:**
- **OS:** Windows 11 version 23H2 (OS Build 22631.3810)
- **XPipe Version:** 10.0.4

**Hardware specifications:**
- **CPU:** 12th Gen Intel(R) Core(TM) i5-12600K (Virtualization: Enabled)
- **GPU:** AMD Radeon RX 6700 XT
  - Driver version: 31.0.24033.1003
  - Driver date: 5/8/2024
  - DirectX version: 12 (FL 12.1)

**Comment by Syrent** [comment]
I've tested this on multiple Ubuntu servers. Here is one example:
```
            .-/+oossssoo+/-.                                                                       r
        `:+ssssssssssssssssss+:`           -------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.4 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Kernel: 5.15.0-107-generic
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 45 days, 13 hours, 54 mins
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 1042 (dpkg), 5 (snap)
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 5.1.16
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Terminal: /dev/pts/0
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   CPU: AMD Ryzen 7 3800X (16) @ 3.900GHz
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   GPU: 22:00.0 ASPEED Technology, Inc. ASPEED Graphics Fami
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Memory: 30317MiB / 64184MiB
+sssshhhyNMMNyssssssssssssyNMMMysssssss+
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```

**Comment by crschnick** [comment]
Hmm I am aware of some rare issues on Windows of this but not on Linux systems. Does this happen every time or just sometimes? Also how large are the files you are dropping?

**Comment by Syrent** [comment]
When I upload any file larger than approximately half a megabyte from my local machine to a remote server, it crashes every time after the upload is complete. However, it works fine for smaller files, such as YAML configurations. The files I tested were usually around 2MB in size, with an average upload speed of 120KB/s.

**Comment by crschnick** [comment]
Let me think about how to debug this, I can release a build at https://github.com/xpipe-io/xpipe-ptb once it's ready.

**Comment by crschnick** [comment]
Alright, you can try out the latest PTB build. That one is intended to determine where the issue lies. For Windows systems, it now prefers pwsh to powershell when doing file io. So you can try to install pwsh core from https://github.com/PowerShell/PowerShell and do the same file transfer again. If it works then I know where the issue is.

If not, you can go to Settings -> Troubleshoot -> Launch in debug mode and send me the logs somewhere, e.g. email or discord, after the file transfer fails.

**Comment by Syrent** [comment]
It didn't work. Can you send me your discord id so I can share the debug log with you?

**Comment by crschnick** [comment]
There is a discord server that you can find me on: https://github.com/xpipe-io/xpipe?tab=readme-ov-file#more-links

**Comment by Syrent** [comment]
The issue has been resolved in the latest PBT version.
