### ISSUE TITLE
Display custom script's output when executed from file manager

### ISSUE THREAD

**Issue by FMotalleb** [xpipe-io/xpipe#304]
Thank you for developing Xpipe, a valuable free and open-source application. I appreciate the custom script execution feature in the SFTP mode. However, I've noticed a limitation: there's currently no way to view the output of these custom scripts directly in the file manager interface.

To work around this, I've been using the error reporting option as a makeshift solution to display script output. For instance, when running an MD5 checksum script, I've had to modify it like this:
```bash
find ${1:-$PWD} -type f -exec md5sum '{}' \; 1>&2
exit 1
```
This approach redirects the standard output to standard error (1>&2) and forces an error condition (exit 1) to trigger the error reporting display. While functional, this is not an ideal solution.

I'd like to request a feature enhancement: the ability to view the console output of custom scripts directly in the file manager interface or like the error handler (in a popup) after the execution is done. This would greatly improve the user experience and eliminate the need for workarounds that abuse the error reporting mechanism.

**Comment by crschnick** [comment]
That makes sense, I will have to think about how to implement that

**Comment by crschnick** [comment]
So now that I think of it, is there a case of not displaying command output? I could for example implemented like that to always show the command output if there was any on stdout

**Comment by crschnick** [comment]
Or are there cases in which you want your scripts to not show their output even though they probably print something to stdout?

**Comment by FMotalleb** [comment]
That's a good point. We could show output whenever stdout exists. If someone really wants to hide the output, they can always use `&>/dev/null` when running the script.

**Comment by FMotalleb** [comment]
currently, it will be good enough.
and it's normal behavior of a bash script tho.

**Comment by crschnick** [comment]
I'm currently working on some changes for scripts.

Would it also be ok to give the option to run the script in a terminal? That way you would get your output in a terminal an could also run interactive commands

**Comment by FMotalleb** [comment]
that's too good to be true.

**Comment by FMotalleb** [comment]
and another thing, could you add `/home` to the common section in the sftp view?

**Comment by crschnick** [comment]
yeah can do that

**Comment by crschnick** [comment]
You can try out an early version at https://github.com/xpipe-io/xpipe-ptb if you're interested. Also reworked other parts of the scripting system

**Comment by FMotalleb** [comment]
Thank you!

**Comment by FMotalleb** [comment]
Thanks for the update. Since the problem is solved, I think we can go ahead and close this issue.

**Comment by crschnick** [comment]
Feel free to continue using the PTB until the full release, I pushed another PTB update with a few more changes to scripts.
