### ISSUE TITLE
[FEATURE REQUEST] Add profiles so that you can use different git syncs.

### ISSUE THREAD

**Issue by zandercodes** [xpipe-io/xpipe#311]
It would be cool if you could add profiles.
So that you can use git sync differently for private or business purposes, for example.

**Comment by crschnick** [comment]
Right now, the best thing you could do is probably starting xpipe with different data directories with `xpipe open -d <dir>`. But yeah I will think about how to implement this properly

**Comment by crschnick** [comment]
This is now implemented in the latest PTB at https://github.com/xpipe-io/xpipe-ptb if you're interested in trying it out early

**Comment by zandercodes** [comment]
> This is now implemented in the latest PTB at https://github.com/xpipe-io/xpipe-ptb if you're interested in trying it out early

Thank you works fine 😄
