### ISSUE TITLE
[Feature Request] Follow XDG Base Directory specification

### ISSUE THREAD

**Issue by regalialong** [xpipe-io/xpipe#322]
Hey, loving the software so far, there's a little thing that bugs me.

XPipe's working directory is stored at `~/.xpipe`, which is fine but when everyone does this, it ends up cluttering my home folder with a lot of files and directories.

[XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/) specifies some directories to use instead and allows users to signal a preference for a different directory per environment variables.

This is obviously a pretty Linux-centric request, but I can't imagine this to be significantly different than `%%USERPROFILE%%`.

Thanks!

**Comment by crschnick** [comment]
I see, but I think that's difficult to implement retroactively without causing confusion. Also right now you will find the data directory at the same location on all systems, the user home directory (which is effectively %USERPROFILE%).

For now, you can run `xpipe open -d <dir>` to launch xpipe in another data directory. You could for example modify the .desktop file to do that as well.

**Comment by crschnick** [comment]
So I think I can close this as wontfix really, because it would be not feasible to change that retroactively now.

XPipe 11 now comes with workspaces so you can automatically create desktop shortcuts to open it in a different directory.
