### ISSUE TITLE
[Language Request] Add Vietnamese (vi)

### ISSUE THREAD

**Issue by xuantan97** [xpipe-io/xpipe#325]
Recently, I have used the software and found it very suitable. Please consider adding the Vietnamese language to make it more accessible to the Vietnamese developer community. Thank you!

**Comment by crschnick** [comment]
Sadly the translation API currently does not support that: https://developers.deepl.com/docs/resources/supported-languages#target-languages

When it supports that, it should be possible.

**Comment by crschnick** [comment]
This is now added in XPipe 18
