### ISSUE TITLE
Request: Browser column layout, please add 'owner' and 'group'

### ISSUE THREAD

**Issue by IgorKerstges** [xpipe-io/xpipe#330]
Hi!

Currently we get infromation about our browsing location in colums:

- Name
- Size
- Attributes
- Modified (date)

It would be greatly helpfull if also is displayed:
- Owner
- Group

If possible: depending on the logged-in session (sudo/user) it would be great if xpipe could also enable to re-configure owner and group for the given selection.

**Comment by crschnick** [comment]
Displaying owners/groups should be doable.

By your last statement you mean like a dropdown where you can set the owner/group out of all possible ones?

**Comment by IgorKerstges** [comment]
Currently, with right-click on the item, xpipe offers a choice of setting attributes. I was thinking of something similar. I assume that a dropdown might be challenging on servers with many accounts, maybe opt to show a list of possible choice whith an input-field where user can start typing a name for owner or group and the the dropdown list reduces correspondingly?..

**Comment by crschnick** [comment]
Yeah that is not going to be trivial as there are almost always many accounts available on a Linux system, most of them aren't relevant though. I just tested this by listing all available users and groups.

Maybe there is a possible way to only list somewhat relevant users/groups on a system using some kind of heuristic? Because using a manual text field there is going to be difficult.

**Comment by IgorKerstges** [comment]
Maybe identify system accounts based on their UIDs. when I look at: `getent group', I see the groupnames and their groupid. From what I see on my system and as per linux administration practise, accounts with id below 1000 can be considered 'system'-accounts. Aparently, also accounts with id above 60000 are considered 'system'-accounts, but I'm not sure for servers hosting nonroot containers (like podman); those apparently might spawn users with id higher than 60000 (I'm not an expert)

`awk -F':' '$3 < 1000 { print $1, $3 }' /etc/passwd`

might help getting to a filtered list?

**Comment by IgorKerstges** [comment]
You are right: my usecase would be to occasionally use my sudo-user to apply a change for owner/group to verify expected behavior or quick troubleshooting.

Even if just the first part of my request would be implemented (to display owner/group in 2 additional columns), that would be a great help!

**Comment by crschnick** [comment]
Two additional columns or would one merged one work with `user/group`? Also should the uids/gids be displayed?

**Comment by IgorKerstges** [comment]
I'd prefer to see both name and id, if in a single column it would be great to see someting like:

`user [id] , group [id]`

to look like:

`root [0] , root [0]`
or:
`podman-user [986] , podman-user [986]'

Mind: long names might need trimming to column-width. ;)

**Comment by crschnick** [comment]
alright I see. And maybe if user and group is the same, that can be merged together to make it shorter.

**Comment by crschnick** [comment]
Can you try the latest build at https://github.com/xpipe-io/xpipe-ptb to see if it works as expected for you?

**Comment by IgorKerstges** [comment]
Wow, thát's fast! I will see to give it a whirl in next hours, thanks!

**Comment by IgorKerstges** [comment]
I tried the portable version of latest build, the "/app/xpiped.exe" won't start on my system. I don't want to try on my current running sytem with installed and configured xpiped but I may give it a shot tomorrow on another laptop I have around..

**Comment by crschnick** [comment]
Thanks for the report, any issue detected in testing is better than when it's released.

There are two things to try here:
- in `app/scripts/xpiped_debug.bat` there is debug output in a terminal
- in `<User Home>/.xpipe-ptb/logs` there should be normal log output of when it didn't start up properly

You can try on a running system, the PTB build is completely separate from the release installation and does not interfere with it.

**Comment by IgorKerstges** [comment]
Hi, `app/scripts/xpiped_debug.bat` runs but doesn't help me (novice). I found the logs, today's logs are empty (3 tries). An older log of yesterday indicated a lock, I found the lock file and removed it. Launching a new instance sets the lock again but still doesn't launch into gui, logfile is empty. It's late here, will try to be available tomorrow again!

**Comment by crschnick** [comment]
Alright, whenever you have some free time.

It's interesting that it does not run for you at all, that is very unusual. You can share anything that is printed by the debug script, there isn't any sensitive information on startup. If the logs are empty, there must be some serious problem going on somewhere.

**Comment by crschnick** [comment]
The lock errors are about an internal mechanism to prevent multiple instances from launching. They should go away if you kill other stuck xpiped processes

**Comment by IgorKerstges** [comment]
The gui never shows.

**Comment by crschnick** [comment]
Alright interesting so it just didn't do anything after a while and you then pressed CTRL+C in the terminal to kill it?

**Comment by crschnick** [comment]
I think I see the issue. I reworked the command output parser and forgot to expect negative exit codes for some programs. In your case `wsl.exe` is returning a negative failure exit code probably because it is not installed.

Thanks for the report, I will fix that for the next PTB.

**Comment by IgorKerstges** [comment]
I ran it in elevated cmd-prompt and yeah, I had to kill with CTRL+C.. Good luck!

**Comment by crschnick** [comment]
https://github.com/xpipe-io/xpipe-ptb/releases/tag/11.0-16 should work

**Comment by IgorKerstges** [comment]
https://github.com/xpipe-io/xpipe-ptb/releases/tag/11.0-16 works for me..

Regarding changes:
- I now see 'Owner' in Filebrowser, check. The Owner is shown as username [uuid] --> the uuid is shown as a value (1k) but it should be shown as a id_number (1000).
- In the filebrowser, the 'Group' is not shown.

![image](https://github.com/user-attachments/assets/ab6f2b02-2c8f-4401-a4b6-f3501029d3a1)

**Comment by IgorKerstges** [comment]
I've been using this version for a couple days now, without issues..

**Comment by crschnick** [comment]
The 1k it was intentional to save some space, but I don't think it's necessary so I can change that.

The groups are only shown if user and groups differ for at least one file. If all are equal, they are collapsed into one.

**Comment by crschnick** [comment]
Do the chown/chgrp context menu actions work for you as expected? I.e. do all the relevant groups and users show up? Because I tried my best at filtering out the irrelevant ones.

**Comment by IgorKerstges** [comment]
For my use-cases, those chown/chgrp actions with the offered relevant groups work like a charm! The only minor observation is that changes don't immediately reflect in the explorer view, but they are shown after refresh which is fine for me..

**Comment by crschnick** [comment]
Yeah the refresh is the case with many operations. If it would refresh after every change, the UI would be blocked for a while while the files are updating. How long depends on how fast your system and connection is. I preferred not refreshing to that.

**Comment by crschnick** [comment]
This is now released in XPipe 11: https://github.com/xpipe-io/xpipe/releases/

Feel free to report any issues if it does not work as expected.
