### ISSUE TITLE
[Feature Request] S3 vault sync

### ISSUE THREAD

**Issue by jbmay** [xpipe-io/xpipe#333]
Currently the only way to sync data is configuring a git repository. I would like the option to configure syncing to an S3 compatible service (MinIO, Backblaze B2, Cloudflare R2, etc) instead.

**Comment by crschnick** [comment]
I'm not super familiar with all these storage services but do they also offer a detailed history like git? One advantage of git is having a detailed history of all changes.

If these services have some kind of git compatibility layer such that you can use them directly via git, that should also work. I was able to find something like https://metamug.com/article/productivity/jgit-host-git-repository-on-s3.html but that requires jgit and does not integrate with the normal git.

**Comment by jbmay** [comment]
They all implement (at least partially) the AWS S3 API so you can interact with them the same way you would with S3. Most of them support enabling file versioning and configuring lifecycle settings to manage version retention.

Looks like xpipe is written in Java and AWS provides a Java SDK that could be used for S3 interactions: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-s3.html

**Comment by jbmay** [comment]
S3 version history isn't as detailed as git history. Basically it just saves a new copy of a file whenever it is changed so you can access and restore old versions but it doesn't show diffs or anything natively like git does.

**Comment by crschnick** [comment]
Is there any particular reason why you would prefer that to a git repository? Or what kind of flexibility are you referring to exactly.

There is a more general aws integration planned on the horizon but that one will probably work through the AWS CLI. The AWS SDK for Java is one of these Java 8 enterprise library messes that has not been made with Java 9+ in mind. I would have to spend a considerable amount of time just getting that to work

**Comment by jbmay** [comment]
By flexibility I just mean having multiple options for syncing services rather than being locked to using the git repo method. The primary reason I would like it is that I already use s3 compatible storage for data storage and syncing for other applications, so being able to continue that pattern across apps would be nice.

S3 also gives you the ability to enable server side encryption on the entire bucket whereas storing files in a git repo requires files to be encrypted before committing and leaves unencrypted file history in the commits if something does get committed unencrypted.

Basically just having multiple options to provide greater control over where and how data gets stored/synced would be nice. Example would be how obsidian.md vaults can be synced with their official paid sync service, or by using an opensource sync plugin that allows syncing to different storage services including s3 or compatible, webdav, google drive, git, etc. I know supporting every possible storage backend is unfeasible for a solo dev, but s3 object storage is common enough that I could see more users than just me being interested in it.

Also I realized that I linked an older version of the AWS SDK for Java. They also have a version 2 that is in active development and some cursory searching (I am not a Java dev so I could be wrong) makes it sound like it should work with Java 9 out of the box: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/home.html

**Comment by crschnick** [comment]
No I looked at the latest SDK, that one is still stuck in Java 8 in terms of packaging. XPipe uses the latest Java modularity features which require libraries to provide some module metadata to work properly. That SDK doesn't do it, so it won't work unless I generate that metadata manually. For such a big library that is almost not possible.

Implementation-wise it would be possible to support more storage providers than just git. But then is also a matter of proper authentication and integration with the aws cli. Something like that can be implemented once general aws cli support has been added. I can't say for sure though when death will happen, but it is planned.

**Comment by crschnick** [comment]
If you're feeling adventurous, you can experiment with something like https://github.com/bgahagan/git-remote-s3. XPipe should support all kinds of git urls if they are set up properly.

**Comment by jbmay** [comment]
Gotcha. I didn't realize the Java sdk was so hard to work with.  That's unfortunate. Well whenever you get around to adding AWS cli support I would love to see syncing directly to s3 added and would love to beta test it. 

In the meantime I'll just use the git method and possibly try that git-remote-s3 tool out or maybe look at trying to use s3fs to mount an s3 bucket as a file system for the location that xpipe stores it's vault.

**Comment by crschnick** [comment]
I will be honest here, I think this will be pretty unlikely to be implemented. The current git vault implementation has grown more complex over time, mainly due to performance reasons. It has to optimize various different things because git is slow. It now uses several heuristics to determine whether it needs to run a commit command. And it took a long time to get here.

With other storage providers, this would also need specific optimizations and is not as simple as just synchronizing a directory with a remote. It is much more complex than that.

**Comment by crschnick** [comment]
I'm going to close this as not being planned at the moment. If at any point the aws integration is implemented and it turns out that this feature would be much easier to realize than I had assumed, this can be reconsidered.
