### ISSUE TITLE
Xpipe Linux - Change default shell ?

### ISSUE THREAD

**Issue by Marc-Harony** [xpipe-io/xpipe#339]
Hi, 👋🏻 

I've been using XPipe for a few days and was wondering if it was possible to change the default shell for the local connection.

It's set to bash and I'd like to use zsh.

When I open my terminal emulator directly, zsh opens, but when I launch it from XPipe, bash opens (bash -l).

Thanks for any help you can give me :)

**Comment by crschnick** [comment]
It's not possible to change the default shell but hopefully soon you can change the shell to login with for every system, see https://github.com/xpipe-io/xpipe/issues/288

**Comment by crschnick** [comment]
Effectively that is probably what you're looking for. It's just that even if you would switch to zsh that way, bash would still be used as a default for any background operations.

**Comment by Marc-Harony** [comment]
Good to know, thanks for your reply :)

**Comment by crschnick** [comment]
Meanwhile you can create a zsh shell environment manually and use that one

**Comment by Marc-Harony** [comment]
I'll try this, I haven't explored all the configuration options yet :)

**Comment by crschnick** [comment]
You can either search for connections automatically and enable the `available shells` option to get a zsh environment or create one manually at `New ...` -> `Shell environment`
