### ISSUE TITLE
Synchronization to gitea stopped working

### ISSUE THREAD

**Issue by manprinsen** [xpipe-io/xpipe#343]
Hi,

After upgrading to latest version of xpipe the Synchronization stopped working to my gitea repo. Before it worked using http and/or ssh url.

Anyone experiencing the same?

**Comment by crschnick** [comment]
From which version did you upgrade?

Is there any error message shown? Or does it just not sync and save anything?

**Comment by manprinsen** [comment]
`
Unable to fetch from remote repository http://100.0.0.20:3002/lemling/xpipe-connections.git

Please make sure that:
- You have the correct repository URL
- Your repository URL matches the rules regarding a .git suffix (Some remotes require a .git suffix, some require it to be omitted, others do not care)
- Your configured git user has the necessary access right via credentials or a token
- You have internet connectivity
`

There is not network issue on my lan. Also the repo works outside of xpipe.

**Comment by manprinsen** [comment]
> From which version did you upgrade?
> 
> Is there any error message shown? Or does it just not sync and save anything?

Sorry i cannot remember which version :/ But i have another computer running xpipe (11.1) and all works :)

**Comment by crschnick** [comment]
The only thing that was changed were the URL rules with regards to a .git suffix and ending slash. Before it tried to add a .git suffix automaticallybut that broke some URLs so this is no longer done. Maybe you can edit the URL in the settings menu. There is also a test button there now.

**Comment by crschnick** [comment]
> Ill try reinstall the app, one moment

Any updates on this?

**Comment by manprinsen** [comment]
> > Ill try reinstall the app, one moment
> 
> 
> 
> Any updates on this?

I tied on a fresh windows 11 vm. After installing 11.3; under Syncronisation I ticked the radio button, entered a git url using http, clicked on Test - which throws the error above.

**Comment by crschnick** [comment]
The test button essentially runs `git ls-remote <url>`. Does that work for you in a terminal?

**Comment by crschnick** [comment]
So I tested with a gitea setup and didn't encounter any issues. Not sure why it happens for you

**Comment by manprinsen** [comment]
> So I tested with a gitea setup and didn't encounter any issues. Not sure why it happens for you

It works for me also :)
`
┌──(tobiascarlbomTobiass-MacBook-Air)-[~]
└─$ git ls-remote http://192.168.0.20:3002/lemling/xpipe-connections.git
Username for 'http://192.168.0.20:3002': lemling
Password for 'http://lemling@192.168.0.20:3002': 
607faecbf074cb5462a85c189f82ae052f2e7621	HEAD
607faecbf074cb5462a85c189f82ae052f2e7621	refs/heads/main
`

**Comment by crschnick** [comment]
You said that the test button in xpipe fails for you with this repo. Is that still the case on your Windows VM? If so, can you post the full error message? There should be the original error printed below the common troubleshooting steps in the error handler dialog
