### ISSUE TITLE
[Feature Request] Minimize to tray

### ISSUE THREAD

**Issue by noone-silent** [xpipe-io/xpipe#344]
Allow xpipe to minimize to system tray. Ideally when clicking on close and run in background is selected.

**Comment by crschnick** [comment]
What OS are you on?

**Comment by noone-silent** [comment]
> What OS are you on?

I am on debian bookworm (12) using KDE Plasma

**Comment by crschnick** [comment]
Earlier versions of XPipe actually had tray support on Linux but that was removed because the tray didn't really work and look good in like half the desktop environments available.

**Comment by crschnick** [comment]
I think I can close this issue as not planned. I would actually like to have this as well, but the technical implementation of tray support on Linux across multiple desktop environments is difficult with the current stack.
