### ISSUE TITLE
[Feature Request] Provide Windows ARM64 version

### ISSUE THREAD

**Issue by IgorKerstges** [xpipe-io/xpipe#346]
I recently switched to a new laptop with Snapdragon X Elite and would like to install and run Xpipe native ARM64 on my laptop.

**Comment by crschnick** [comment]
Does the x86_64 version run on your system via the compatibility layer?

**Comment by IgorKerstges** [comment]
I tried with portable version xpipe-11.3. The application launches and i can tick to accept terms and conditions. My observations:

1) When the wizard to scan local connections, an error is raised:
![{375334EA-6C27-44EB-82CD-705630F88363}](https://github.com/user-attachments/assets/377c7195-d9c1-4d51-bbd1-382b6ae4e685)

Afterwards, powershell and git connections are found and can be launched, cmd shows error. When I try to run the cmd-connection anyway, the prompt shows: "'wmic' is not recognized as an internal or external command, operable program or batch file."

2) I tried adding en external connection, 'Simple SSH connection', when I try to browse to the file location of my private ssh-key, another error is raised:
![{21572EFE-FE9A-4F71-963D-276A51655851}](https://github.com/user-attachments/assets/a20e4c36-ad23-4506-9b74-4432ea92d4dc)

After closing the error, I was able to type the path to the file which was accepted. The scanning of connections on the remote site worked well, connections for bash and podman were identified and added in the location-connections.

Terminal connection open properly, remote file browsing works properly.

Here is the process view on my laptop:
![{E3CA4733-AEF8-4EDE-993C-368C1F027AC6}](https://github.com/user-attachments/assets/b0c8b40b-dbc3-49f9-8908-be3c53eac9ba)

Cheers, Igor

**Comment by IgorKerstges** [comment]
The application behavior of xpipe in translation-layer works reasonably well, still snappy. These are initial impressions, I will keep this in use in next days and report findings if any..

Cheers, Igor

**Comment by crschnick** [comment]
That issue is actually unrelated to ARM, it's just that the wmic tool it has been removed from windows in the latest versions.

https://github.com/xpipe-io/xpipe-ptb/releases/tag/12.0-1 has been transitioned away from wmic

**Comment by crschnick** [comment]
Also a native ARM build is probably not going to happen for at least half a year due to upstream dependencies being slow to add support for that.

**Comment by crschnick** [comment]
The wmic issues are now fixed in xpipe 12.

About the ARM build, that will be available when the dependencies allow it. I will close this issue, because I don't have any control over it. But you will get an ARM version when it's possible.

**Comment by crschnick** [comment]
There is now an ARM build in testing at https://github.com/xpipe-io/xpipe-ptb
