### ISSUE TITLE
[Feature Request] Proxmox VM port change

### ISSUE THREAD

**Issue by kolbacer** [xpipe-io/xpipe#352]
Hi XPipe team,

As far as I can tell, it's not currently possible to change the SSH port when connecting to Proxmox VMs. Many environments don't use the default port 22 for security reasons, which makes it difficult to connect via XPipe.

It would be great to have an option to set a custom SSH port in the connection settings.

![image](https://github.com/user-attachments/assets/7da949bb-2258-4bdb-a96e-0c6f0da6c164)

**XPipe version: 12.0**

Thank you for considering this feature!

**Comment by crschnick** [comment]
Yeah I can look into that

**Comment by crschnick** [comment]
you can try whether https://github.com/xpipe-io/xpipe-ptb/releases/tag/12.1-1 works for you

**Comment by kolbacer** [comment]
> you can try whether https://github.com/xpipe-io/xpipe-ptb/releases/tag/12.1-1 works for you

I gave it a try, but unfortunately it didn’t work as expected🙁. I tested several port configurations, and here are the results:

- SSH server port: 22 && XPipe SSH port: 22 -> just fine

![image](https://github.com/user-attachments/assets/e85f3618-5273-49ce-8c42-a9964a9b7cce)

- SSH server port: 22 && XPipe SSH port: 3333 -> shell not respond

![image](https://github.com/user-attachments/assets/c55ca2fe-e89e-49bd-82c4-4673d8711a3a)

- (SSH server port: 3333 && XPipe SSH port: 22) || (SSH server port: 3333 && XPipe SSH port: 3333) -> unable to start SSH

![image](https://github.com/user-attachments/assets/b17c8fa0-ece5-41f0-8800-7dff8901ef2a)

Also, **insights** shows port 22 anyway:

![image](https://github.com/user-attachments/assets/c4d6a92f-6e73-40b4-ac64-d4fb5de6ed53)

**Comment by crschnick** [comment]
Yeah the insights display is wrong, I forgot to update that. I think I also messed up the SSH server start logic, so it tried to start it at the wrong port. I will fix this.

**Comment by crschnick** [comment]
Should be fixed in https://github.com/xpipe-io/xpipe-ptb/releases/tag/12.1-3

**Comment by kolbacer** [comment]
Everything works great now, thank you!
