### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Bmoney2388** [xpipe-io/xpipe#355]
Process returned exit code 1:
error during connect: in the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect: Get "http://.pipedocker_engine/v1.46/version": open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by crschnick** [comment]
Hmm, is you docker installation configured to require Administrator privileges? If so, you need to launch XPipe as Administrator as well. If this is a remote system, you need to login as Administrator.

**Comment by crschnick** [comment]
I will close this issue as inactive for now
