### ISSUE TITLE
[Feature Request] Log terminal session

### ISSUE THREAD

**Issue by Pr1meSuspec7** [xpipe-io/xpipe#357]
Hi xpipe team,
I'm a network engineer and I love this app but I would like to have a feature like putty or secureCRT for save the terminal session to store the activity made on the device.

![image](https://github.com/user-attachments/assets/ac67886e-6342-434a-82f1-a8c6d582c248)

Thanks a lot
Mark

**Comment by crschnick** [comment]
For what purpose is that log? Like for security and auditing purposes or something else?

**Comment by Pr1meSuspec7** [comment]
Hi Chris, 
it's very useful to have a session log, especially when there is a remote vendor technician taking over your ssh session for troubleshooting. With the session log we can save all the commands issued by the remote technician, so we can share the output with him or another colleague, finally we can attach the log file to documentation or service request.

**Comment by crschnick** [comment]
The thing about the terminal sessions, they are actually not under control of XPipe. As soon as the terminal application launches, XPipe doesn't control the session anymore.

I could see two solutions here:
1. An option to set up session logging on the remote system like this https://serverfault.com/questions/559658/log-commands-executed-over-ssh, which would apply to any SSH sessions, including the ones launched by XPipe
2. An option to log everything on the client side like this: https://superuser.com/questions/909697/log-commands-run-over-ssh-on-client-side. But I'm not sure how well that would work on all platforms

**Comment by crschnick** [comment]
Actually I have thought about it, the client side logging can probably be implemented via Start-Transcript and `script`, that should cover all platforms.

I will see what I can do

**Comment by crschnick** [comment]
Can you try this: https://github.com/xpipe-io/xpipe-ptb/releases/tag/12.3-1 and let me know what you think

**Comment by crschnick** [comment]
Where would you store the files instead if you had the option to change the directory? I'm just trying to avoid introducing too many options. E.g. is there a case where creating a symlink to the session dir would not be enough?

The feature will be released in 12.3 some time this week. Although I have not decided yet if it will be available in the community edition or not as this is the kind of feature that is typically used by professional users.

**Comment by Pr1meSuspec7** [comment]
Yeah, a simlink can be enough. 
You can close this issue.

Thanks a lot

**Comment by crschnick** [comment]
This feature is now released. There were a few initial issues on release, but I pushed hotfixes for that.

I decided to release this feature in the professional plan as there was seemingly no demand from community users from the users I asked. It is also available in the community edition for two weeks after this release as a preview so that anyone interested can try it out.
