### ISSUE TITLE
Unable to connect to server using SSH Key

### ISSUE THREAD

**Issue by nixOS-daveslab** [xpipe-io/xpipe#358]
Hi! 
Very silly question, but  I cannot figure this out.

My Problem: Unable to connect to server using an SSH key, password authentication is working fine. 

The desktop I am using has the private key locally under /home/david/.ssh/id_rsa
The private key is password protected.

When connecting to the target server I am able to authentication without issues from my desktops terminal ( kitty ). This is with the ssh key

When connecting to the target server using xpipe I encounter the following error
"An error Occurred: Identity file /home/david/.ssh/id_rsa does not exist."

In Xpipe
I have configured the server with the following:
Guest user: david
User password: blank

Guest Identity
Identity file ( points to the local path of where the ssh key is located)
/home/david/.ssh/id_rsa

password:
private key password. 

I'm sure I am just missing something really small here, if so please feel free to smack my head in and provide the documentation.
I've also ensured on this local desktop that houses the key has  ssh forwarding enabled.

**Comment by crschnick** [comment]
Do you have a gateway configured for the SSH connection?

**Comment by nixOS-daveslab** [comment]
This is 100% user error and a misunderstanding of the GUI on my part. 

Missing details that actually mattered.
The remote server is a VM hosted on proxmox, i attempted to use my local ssh key running Xpipe on my local desktop wrongfully assuming it was going to forward my local SSH key. 

A quick peak in to the Auth logs on the guest clarified that for me real quick. As it wasn't my local system authenticating to the guest, but the proxmox host. I went ahead and generated a ssh from the host to the target system, and all is well. In the future I understand that I'd need to add the Guest VM's as an individual server, or maintain keys from the host / jump server.

**Comment by crschnick** [comment]
Yeah I can see the confusion. The VM key support is pretty new, so I didn't really consider that. But I can think about possible solutions. The problem is that technically the VM host doesn't have access to your local key files, so any solution to this is complicated.

**Comment by crschnick** [comment]
Would you say that this help text would have cleared up your confusion: https://github.com/xpipe-io/xpipe/commit/51d434c3e041e57cbcf7c16b7a87424cd63b275b#diff-2b4b180306f913fd6b507faad12a8beb49c76ae5d1a02008f03c08e84913fc1f

If so, I will add that help button to that SSH key option in the next update
