### ISSUE TITLE
connection to pve on macos

### ISSUE THREAD

**Issue by juliojmjc** [xpipe-io/xpipe#359]
java.lang.IllegalStateException: Unable to list agent identities via command ssh-add -l:
The agent has no identities.

Please check your SSH agent CLI configuration and the SSH_AUTH_SOCK variable. See https://docs.xpipe.io/ssh-agent-socket for details.

**Comment by crschnick** [comment]
Are you trying to connect to a Proxmox VM with an SSH identity? If so, note that right now, all identity options are used from the PVE host. That means that it is trying to use the agent installed on your PVE host, not your local machine.

This is a known issue like in #358 

Maybe I can find a solution to this

**Comment by crschnick** [comment]
This issue is now fixed in XPipe 13
