### ISSUE TITLE
"Shell opener was stuck in loop" when connecting from Windows 11 to Proxmox via SSH

### ISSUE THREAD

**Issue by bigsby-exe** [xpipe-io/xpipe#360]
When connecting via Windows 11 to Proxmox via SSH I get a connection but I get an error when trying to identify services with the following message:

```
Shell opener was stuck in loop:
Linux elliot 6.8.4-3-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-3 (202
Linux elliot 6.8.4-3-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-3 (2024-05-02T11:55Z) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.


[38;5;203m ������������������
```
This goes on like this for some time before ending in

```
[38;5;203m������������������������ ������������������  ������������������  ������   ������ ������������������������������   ������������������  ������   [38;5;63

-bash: line 2: $'\r': command not found
```

![image](https://github.com/user-attachments/assets/a38c3976-fbd0-468e-86c5-1e0589707558)

I have tried getting the command executed by via the 'Insights' button on the add connection dialog and pasting that into cmd.exe and this works fine 
![image](https://github.com/user-attachments/assets/ce83d96c-c7d0-4b47-ab53-d4f57fc3c367)
I have also tried setting the gateway to Powershell.exe

Any ideas where I am going wrong?

**Comment by bigsby-exe** [comment]
Just to add I have read #290 and it seems like a similar issue, the output of ssh-add -l for me is as follows:
```
bigsby > ssh-add -l
Error connecting to agent: No such file or directory
```
but sshing from PowerShell or cmd.exe prompt works fine (ssh user@host)

**Comment by crschnick** [comment]
So the issue I can see so far is that there are ANSI escape sequences in your terminal output. XPipe connects to your system without a tty, so there shouldn't be any. That might confuse XPipe and make it think that it is stuck in a loop. Are you using any kind of shell prompt or other shell configuration on your Proxmox system?

About the ssh-add issue, are you using the SSH agent for authentication? Because for the Proxmox system you showed it didn't use the agent. Or are we talking about a different system here?

**Comment by bigsby-exe** [comment]
You are completely correct I use [figurine](https://github.com/arsham/figurine) on all my systems. Weirdly xpipe didn't have an issue with it on the Ubuntu VM but did take issue to it on the Proxmox device however removing the config allows xpipe to work without any issues.
Thanks

**Comment by crschnick** [comment]
Can you share your figurine config that broke it? That way I can try to reproduce it

**Comment by bigsby-exe** [comment]
Sure I have a file at `/etc/profile.d/figurine.sh` with the contents

```shell
#!/bin/bash

echo ""
figurine -f "3d.flf" proxmox
echo ""
```

**Comment by crschnick** [comment]
You can keep using that as long as you make it respect common variables. In this case, if `$TERM` is `dumb`, you should not execute that command.

**Comment by bigsby-exe** [comment]
Just tested and this is a perfect fix, thanks

**Comment by crschnick** [comment]
I think I was able to fix the underlying issue. Could you try https://github.com/xpipe-io/xpipe-ptb/releases/tag/12.3-3 with your init scripts while not respecting $TERM again? It should work now in any scenario

**Comment by crschnick** [comment]
The fix for this is now released, so you shouldn't have to adjust your profile script at all
