### ISSUE TITLE
Some icons appear to be missing

### ISSUE THREAD

**Issue by HidYn** [xpipe-io/xpipe#361]
Hi,

The new icon feature is fantastic, but unless I'm missing something, it doesn't appear to have all the icons from https://selfh.st/icons/ available.

If I search for openmediavault on the site, I can see it's in the repository, but when I search in xpipe it's not found.

Might be something I'm doing wrong.

Thank you for such a great project.

**Comment by crschnick** [comment]
Yeah not every latest commit to the icons is reflected in the shipped icons, I need to update those regularly. Maybe I can set something up automatically for that.

**Comment by crschnick** [comment]
The icons have been updated in the latest release

**Comment by brad-charboneau** [comment]
many icons still missing.
maybe you could have it search the api or git repo for selfhst matching a user provided search term, if its not found in the preloaded icon set?
