### ISSUE TITLE
Syncing not working with 13.0.1

### ISSUE THREAD

**Issue by wisameldin** [xpipe-io/xpipe#376]
Previously I was relying on changing the vault to a shared directory Until the last update where the option to put in a location disappeared Though I'll try to use the Synchronization option where I spun up a gitea instance 
Created a repository and made it private copied the link via the HTTPS but it would not work I would get an error 

An error occurred: Cannot invoke "io.xpipe.app.terminal.TerminalView.findSession(long)" because the return value of "io.xpipe.app.terminal.TerminalView.get()" is null
error: unable to read askpass response from '/opt/xpipe/cli/bin/xpipe'
fatal: could not read Username for 'https://git.wisamrph.com': No such device or address
Unable to fetch from remote repository https://git.wisamrph.com/wisameldin/XPipe.git

Please make sure that:
- You have the correct repository URL
- Your repository URL matches the rules regarding a .git suffix (Some remotes require a .git suffix, some require it to be omitted, others do not care)
- Your configured git user has the necessary access right via credentials or a token
- You have internet connectivity

I am sure the username and password I inserted is correct and sometimes it would not load at all

Don't know what I am doing wrong

If you can guide me I would really appreciate it

**Comment by zamk-paw** [comment]
Same issues here, using selfhosted Gitea and sync doesn't work anymore

**Comment by crschnick** [comment]
Thanks for reporting that. This should be fixed in 13.1.1

**Comment by crschnick** [comment]
Can I close this as completed?

**Comment by wisameldin** [comment]
I applied the latest update and it work flawlessly thank you so much for everything
