### ISSUE TITLE
[Feature Request] Folder uploads

### ISSUE THREAD

**Issue by rainrdx** [xpipe-io/xpipe#387]
Hi,

Again and again thank you for maintaining this great project. I notice that when I drag a folder to the file manager, only an empty folder is created. Is it possible to recursively upload everything in the folder?

Regards and thank you!

**Comment by rainrdx** [comment]
> That sounds like a bug. But it does not happen for me on Windows
> 
> Can you maybe provide some details and whether you can reliably reproduce it?

My apologies this is really interesting. I just drop my folder in windows to a linux remote and it always creates just an empty folder.

**Comment by crschnick** [comment]
And that does happen for all folders?

**Comment by rainrdx** [comment]
I tried a number of different folders and yea

**Comment by crschnick** [comment]
What kind of Linux remote is that?

Does that also happen if you drop the folder into the local machine file browser?

**Comment by rainrdx** [comment]
It is Ubuntu. And the same happens to the local machine file browser

**Comment by crschnick** [comment]
And if you drag the folder from local machine file browser tab to the ubuntu file browser tab?

**Comment by rainrdx** [comment]
Thank you!!

**Comment by crschnick** [comment]
Can you try this:

You can go to Settings -> Troubleshoot -> Start in debug mode, drop your local files, and send the log output to crschnick@xpipe.io

**Comment by rainrdx** [comment]
Sent. and in testing, I found out that is likely an user error. Most of my working files are in an onedrive folder. It seems that other folders are fine, just that onedrive folder is uploaded in empty. I don't think you need to work on compatibility with all kinds of online drive services. Thank you!

**Comment by rainrdx** [comment]
I just sent over another log file from the current, release version. I moved over the "images" folder. All the content inside the folder is already downloaded and save on the hard drive. Still empty.

**Comment by crschnick** [comment]
Didn't get an email yet

**Comment by rainrdx** [comment]
Sent again. and always thank you for doing this.

**Comment by crschnick** [comment]
Oh it went to spam. Was the log generated with the build I sent? That looks like a normal release build

**Comment by rainrdx** [comment]
Sent again and thank you!

**Comment by crschnick** [comment]
So I see how OneDrive shows the files now, I might be able to fix that

**Comment by rainrdx** [comment]
Will do un a few hours thank you!

**Comment by rainrdx** [comment]
Everything works perfectly and thank you!

**Comment by crschnick** [comment]
That's good to know. Feel free to continue using the XPipe 14 PTB to try out the other new features
