### ISSUE TITLE
Terminal setting lost under Mac

### ISSUE THREAD

**Issue by rainrdx** [xpipe-io/xpipe#388]
With 13.4.1, I have a weird problem that every time I close XPipe and restart it, the terminal emulator setting is returned to "None."

The way to reproduce it on my end is fairly simple: close and reopen.

**Comment by crschnick** [comment]
There was a recent fix for terminal recognition, but I didn't see this failing like that.

Can you run `mdfind -name 'Terminal.app' -onlyin /Applications -onlyin ~/Applications -onlyin /System/Applications` vs `mdfind -name 'Terminal' -onlyin /Applications -onlyin ~/Applications -onlyin /System/Applications` in your terminal and show the outputs?

**Comment by rainrdx** [comment]
I have:

2024-12-05 07:48:09.995 mdfind[9576:180118] [UserQueryParser] Loading keywords and predicates for locale "en_US"
2024-12-05 07:48:09.995 mdfind[9576:180118] [UserQueryParser] Loading keywords and predicates for locale "en"

v.s.

2024-12-05 07:48:19.975 mdfind[9619:180313] [UserQueryParser] Loading keywords and predicates for locale "en_US"
2024-12-05 07:48:19.975 mdfind[9619:180313] [UserQueryParser] Loading keywords and predicates for locale "en"
/System/Applications/Utilities/Terminal.app

**Comment by crschnick** [comment]
That is bad, I assumed that this would not have unintended consequences.

What kind of macOS system is this?

**Comment by crschnick** [comment]
Regardless of what system it is, I have to change it somehow. What does `mdfind -literal "kMDItemDisplayName == Terminal.app" -onlyin /Applications -onlyin ~/Applications -onlyin /System/Applications` return for you?

**Comment by rainrdx** [comment]
I am running Sequoia 15.1.1

It returns nothing.

**Comment by crschnick** [comment]
And `mdfind -literal "kMDItemDisplayName == Terminal" -onlyin /Applications -onlyin ~/Applications -onlyin /System/Applications`

**Comment by rainrdx** [comment]
/System/Applications/Utilities/Terminal.app

**Comment by crschnick** [comment]
Can you run `mdls /System/Applications/Utilities/Terminal.app`

**Comment by rainrdx** [comment]
_kMDItemDisplayNameWithExtensions  = "Terminal.app"
kMDItemAlternateNames              = (
    "Terminal.app"
)
kMDItemAppStoreCategory            = "Utilities"
kMDItemAppStoreCategoryType        = "public.app-category.utilities"
kMDItemCFBundleIdentifier          = "com.apple.Terminal"
kMDItemContentCreationDate         = 2024-11-15 04:59:47 +0000
kMDItemContentCreationDate_Ranking = 2024-11-15 00:00:00 +0000
kMDItemContentModificationDate     = 2024-11-15 04:59:47 +0000
kMDItemContentType                 = "com.apple.application-bundle"
kMDItemContentTypeTree             = (
    "com.apple.application-bundle",
    "com.apple.application",
    "public.executable",
    "com.apple.localizable-name-bundle",
    "com.apple.bundle",
    "public.directory",
    "public.item",
    "com.apple.package"
)
kMDItemCopyright                   = "© 1991–2024 Apple Inc. All rights reserved."
kMDItemDisplayName                 = "Terminal"
kMDItemExecutableArchitectures     = (
    "x86_64",
    arm64
)
kMDItemFSContentChangeDate         = (null)
kMDItemFSCreationDate              = (null)
kMDItemFSCreatorCode               = ""
kMDItemFSFinderFlags               = (null)
kMDItemFSHasCustomIcon             = (null)
kMDItemFSInvisible                 = 0
kMDItemFSIsExtensionHidden         = (null)
kMDItemFSIsStationery              = (null)
kMDItemFSLabel                     = (null)
kMDItemFSName                      = "Terminal.app"
kMDItemFSNodeCount                 = (null)
kMDItemFSOwnerGroupID              = (null)
kMDItemFSOwnerUserID               = (null)
kMDItemFSSize                      = 7010601
kMDItemFSTypeCode                  = ""
kMDItemInterestingDate_Ranking     = 2024-11-15 00:00:00 +0000
kMDItemKind                        = "Application"
kMDItemLogicalSize                 = 7010601
kMDItemVersion                     = "2.14"

**Comment by crschnick** [comment]
Maybe you have some kind of setting enabled in macOS where it doesn't show the file extension? I should be able to fix that

**Comment by rainrdx** [comment]
From my end it’s all default but I can double check. It does happen on brand new Mac mini 4 which I haven’t gotten around to configure and my MacBook Air. Or maybe macOS just split into displayname and displaynamewithextension?

**Comment by crschnick** [comment]
Can you try the latest version

**Comment by rainrdx** [comment]
Sorry at work will do this later

**Comment by rainrdx** [comment]
Everything works perfectly now.
