### ISSUE TITLE
Windows Installer and chocolatey install fail prematurely

### ISSUE THREAD

**Issue by brad-charboneau** [xpipe-io/xpipe#390]
I am on Windows 11 23H2 trying to install and it is failing. Tried with both Admin and non Admin Credentials

Error in log from choco install with --install-arguments="'/l*v c:\xpipe_msi_install.log'" parameter:
`MainEngineThread is returning 1603`
When i searched for this Error it seems to be something Related to MSI Installer Custom Actions, However, the log is not returning the return value to find out which custom action is causing the issue, if any.

Error in MSI Install
![image](https://github.com/user-attachments/assets/a46e53bb-aac0-43ce-909e-e14fca18a17a)

**Comment by brad-charboneau** [comment]
Issue resolved after reboot, not sure why, no apps or windows updates were installed.

**Comment by crschnick** [comment]
The only thing I can think of is that maybe another installer had a lock and blocked other ones? You can only install one at the time and if another one is stuck somehow, this might happen. Especially if it's a background updater that you don't see.

If you figure it out, feel free to share
