### ISSUE TITLE
Question on PTB: Which track? 13.x or 14.x

### ISSUE THREAD

**Issue by tolgaulas** [xpipe-io/xpipe#395]
Hey, which PTB track should i be on? 13.x or 14.x.. 13.x updates can not be installed when 14.x is installed. 

Merci.

**Comment by crschnick** [comment]
Yeah that is just a disadvantage of having two branches with different versions that need to be tested. You can just ignore the v13 updates, in a few days there should be newer v14 PTB builds released.

**Comment by crschnick** [comment]
I fixed the update API, it should no longer return releases of a previous version if you are on a newer one.
