### ISSUE TITLE
[Feature Request] Add shared Authentication

### ISSUE THREAD

**Issue by HarunKilic** [xpipe-io/xpipe#397]
When using same authentication method on several connections, it's difficult to trace and change all of them once the eg. password is changed.

It would be nice to have some kind of shared authentication where it will be single source for changing the credentials.

**Comment by crschnick** [comment]
That is already targeted for XPipe 14

**Comment by HarunKilic** [comment]
Nice! Closing this request then.

**Comment by crschnick** [comment]
You can test https://github.com/xpipe-io/xpipe-ptb and share your feedback

**Comment by HarunKilic** [comment]
Will do!

**Comment by HarunKilic** [comment]
Will do!
