### ISSUE TITLE
Add support for fish shell

### ISSUE THREAD

**Issue by justin-luoma** [xpipe-io/xpipe#51]
When I try to add fish as a new shell command, it just says: Shell did not start up in time

**Comment by crschnick** [comment]
Yeah we can leave this open, this is definitely a valid issue. The reason there's no support to add arbitrary shells right now is that some small adjustments have to be implemented for every shell type in order for everything to work smoothly. So I don't think there will ever be the feature to add custom shell types, this problem will be solved by just adding explicit support for essentially all shell types out there, including fish in this case.

**Comment by crschnick** [comment]
Step 1 of the solution would be to first at least recognize all different shell types out there, so we can print a message that the type is not supported.
Step 2 would be actually fully supporting the shell type will all its idiosyncrasies.

**Comment by crschnick** [comment]
Fish support is put on hold until this issue is resolved: https://github.com/fish-shell/fish-shell/issues/9907

Without a solution to that, I can't implement anything

**Comment by crschnick** [comment]
I managed to find a workaround that isn't perfect and comes with a few small limitations, but at least it works in its basic form now. So you can use fish in release 1.5 now.

**Comment by crschnick** [comment]
Closing this as it is completed now (at least as much as possible)
