### ISSUE TITLE
Publish to more package manager repositories

### ISSUE THREAD

**Issue by crschnick** [xpipe-io/xpipe#52]
Especially on Linux it would be nice to have an xpipe package available in some package managers

**Comment by Go2Engle** [comment]
This should be pretty easy to get on Winget as well!

**Comment by crschnick** [comment]
yeah, the tool I use to manage releases even supports winget out of the box, so that should be doable.

**Comment by afermar** [comment]
I have created a [PR](https://github.com/microsoft/winget-pkgs/pull/117331) in the winget repo. So now it can be installed with `winget install xpipe`.

Maybe you can take the manifests as reference for the automation.

**Comment by crschnick** [comment]
Wow thanks, I haven't been able to set up the automatic winget publishing yet. But now that I see how the package file should look like, I can just take these and automate the generation of these for every release.

**Comment by crschnick** [comment]
Alright I think this can be closed now. There is now a choco package, AUR package, and homebrew package. A nixpkg is just waiting to be merged. Since XPipe is published in the Microsoft Store, you can install via `winget install xpipe --source msstore`, so there is no need anymore for a separate winget package.

Overall, I think these are enough package managers for now
