### ISSUE TITLE
user does not elevate when required by Docker

### ISSUE THREAD

**Issue by Keboose** [xpipe-io/xpipe#54]
My remote machine (Docker, on Ubuntu Server) has disabled root login, key auth required, but once logged in my user can elevate via `su`. I included my user password in the connection config even though it's not needed for the ssh session itself, so that it can elevate permissions when needed. Docker commands require root privileges on my machine, as it was installed via the system's package manager `apt`. The SSH session that XPipe started elevated correctly when my containers were first populated in the XPipe window. See attached screenshot that shows the list was populated correctly:
![Screenshot_20230708_091816](https://github.com/xpipe-io/xpipe/assets/5133146/c7756ad0-5270-4e50-9363-1cbc3019dfdf)
but when I try to inspect/stop/start a container in XPipe, I get this error (in this case my HomeAssistant container):
```
Process returned exit code 1:
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/HomeAssistant/json": dial unix /var/run/docker.sock: connect: permission denied
```

Stack trace:
```
io.xpipe.core.process.ProcessOutputException: Process returned exit code 1:
Got permission denied while trying to connect to the Docker daemon socket at docker.sock: connect: permission denied
at io.xpipe.core.process.ProcessOutputException.of(ProcessOutputException.java:33)
at io.xpipe.ext.proc.a.a(SourceFile:280)
at io.xpipe.ext.proc.a.readStdoutOrThrow(SourceFile:325)
at io.xpipe.ext.proc.store.g$a.execute(SourceFile:35)
at io.xpipe.app.comp.storage.store.StoreEntryComp.lambda$createContextMenu$17(StoreEntryComp.java:252)
at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$0(ThreadHelper.java:18)
at java.lang.Thread.run(Thread.java:1589)

```
This means I can effectively see my docker containers, but cannot interact with anything.

The correct behavior should be to catch the permission denied error and attempt to elevate, just like it did when it first populated the XPipe container list. Barring that, you could instead add a checkbox to the docker settings pop-up that toggles using `su` for shell commands.

**Comment by crschnick** [comment]
My own set up does not require an elevation for docker, so I first have to set up something to reproduce this. XPipe checks whether we need to elevate the any docker command with `id -nG \"$USER\" | grep -qw docker`, so I guess that is not sufficient? I haven't really looked into all cases of docker elevation.

As a workaround, you can delete the existing docker connections, create a new shell environment for the Docker VM ssh connection that elevates itself, and add the docker connections in that one.

**Comment by Keboose** [comment]
My apologies, I may have jumped the gun assuming it was the app at fault. On my system, `/run/docker.sock` is owned by `root:docker`, that is why I required elevation. I tried your workaround with the shell environment, and it worked fine, but I am uncomfortable having a whole shell running as root, even if the connection itself is secure. I decided it would be better to simply added my user to the docker group via `sudo usermod -a -G docker [user]`. I assume that was probably a required step in the docker help pages that I skipped over or something.

Understandable if you consider this issue closed now, but I think it would be good to add a bit of info in the error pop-up, along the lines of "user not in required group [group]"

**Comment by crschnick** [comment]
Hmm so if your user was not in the docker group previously, XPipe should have elevated the command though. What is the exit code of `id -nG "$USER" | grep -qw docker` when your user is not in the docker group vs when it is?

**Comment by Keboose** [comment]
when in the docker group, the command returns exit code `0`, when not in the group, code `1`. If the app is looking for a non-zero exit code to elevate, it makes sense that it should have caught that.

**Comment by crschnick** [comment]
Ok it seems like the logic for elevating is correct, yet is somehow doesn't get applied correctly. I will investigate

**Comment by crschnick** [comment]
Ok after some testing I'm now more confused than before. It seems like there's more to this issue that I thought about docker and elevation and some things I read about this on the internet somehow don't match up with my results

**Comment by crschnick** [comment]
So I settled on the solution of testing with the following command `test -S /var/run/docker.sock && test -w /var/run/docker.sock` to check if we currently have write access to the socket and we don't have to elevate.

The `-S` test is to check wherever the socket file exists. I know that you can move the location of the socket file but I don't think I will be able to determine where it is located. So if we can't find the socket at a default location, we will just always elevate.

**Comment by crschnick** [comment]
I pushed a staging release that hopefully fixes your issue: https://github.com/xpipe-io/xpipe_staging/releases/tag/1.3.1 . You can just use the portable version from there, the installer replaces your current installation and that is not what you want

**Comment by crschnick** [comment]
This bug should be fixed in: https://github.com/xpipe-io/xpipe/releases/tag/1.3.1

**Comment by crschnick** [comment]
Seems like I forgot to close this issue
