### ISSUE TITLE
Feature Request: Launch RDP connections

### ISSUE THREAD

**Issue by Go2Engle** [xpipe-io/xpipe#56]
Would be cool\nice to be able to launch into an RDP session for windows hosts! I could fully see myself switching over to xpipe from mRemoteNG!

**Comment by crschnick** [comment]
As someone who does not often use RDP connections, how would you imagine such a support would look like? Someone else already suggested this: https://www.reddit.com/r/selfhosted/comments/14ttg5o/comment/jr6d22q/?utm_source=share&utm_medium=web2x&context=3 . Is this would you also are looking for or do you have any other ideas?

**Comment by Go2Engle** [comment]
nope that was not me. But the way I would invision it is when clicking the `Add Remote Host` button id get an option for like `RDP`, `Windows RDP` or something along those lines.  Then when the host is added on the main screen a single click would just dump you into an RDP session of that host. 

Now added functionality I know may take more time and could be though more down the road is tabbed sessions kinda like you have in your file browser. So when connecting to more then one host you can use the tabs to switch back and forth. If you take a look at mRemoteNG youll see what im talking about there. This tabbed functionality could carry over into shell sessions also if you wanted to!

**Comment by crschnick** [comment]
Alright, I think I can visualize that now. I will have to see when there's some time to experiment with an implementation for this

**Comment by c0dingnoobi** [comment]
any updates on this one?

**Comment by crschnick** [comment]
They are essentially two options for this:
- Implementing all the RDP support yourself, including rendering etc., which is a lot of work. This is currently not feasible in a one man project as the required amount of work is way too much. The library landscape for this is also not that rich, so you indeed have to implement much by yourself.
- Delegating this to installed RDP clients, which is easier and more in line with what XPipe does. I tested with various RDP clients and a problem is that most of them lack proper CLI support, so there's only so much that XPipe can do here to create some additional value for RDP users

**Comment by xbufu** [comment]
Just researched a bit more and it seems it would be sort of (?) cross-platform. Remmina supports rdp files, and you can parse the connection information from the rdp file using bash, so it would be usable at least on linux too (https://askubuntu.com/questions/337441/using-windows-exported-rdp-file-from-ubuntu).

I think the main benefit would not be the launcher itself but the fact that you can have all your rdp connections in one place and organized how you want it, just like with shell connections. Having a full custom, cross-platform implementation would of course be very nice, but the biggest benefit would still be achieved via the simple rdp file method. At least that would be it for my use case, as I have a quite some Windows VMs in my lab and having all connections in one place, with one button would be amazing.

**Comment by crschnick** [comment]
Ok I see, I have to experiment with that.

The few other people interested in this issue discussion could also weigh in on whether such a launcher implementation would be sufficient or if they are looking for something different.

**Comment by crschnick** [comment]
Ok so I implemented basic RDP launcher support.

Passing passwords is doable on Windows with the password 51 option. But on Linux, it would still require an application specific implementation to pass passwords to the selected RDP client. I'm not sure whether it is possible to guarantee a smooth workflow on all platforms.

**Comment by xbufu** [comment]
Very nice, Looking forward to testing it soon!

As for the workflow on Linux, CLI RDP programs like freerdp/xfreerdp support passing the password as an argument, while Remmina (what most people seem to be using) can take a .remmina or a .rdp file. One could create temporary config files similar to the temporary SSH config files for connections right?

**Comment by crschnick** [comment]
So I tested with remmina and there are two problems:
- It does not allow to store passwords for temporary .rdp connections. It only stores and accept passwords for connections that are managed in remmina itself.
- The .reminna files do not contain the passwords. They are stored with libsecret. In theory we can access that, but there's no point if it does not accept the passwords for temporary rdp files

For other clients it will also be probably very context specific, so not easy. I had originally envisioned to designate such a feature, if it would happen, as a professional edition feature. But looking at it now, I don't you can sell this with such a thin implementation. So maybe I can add some special integrations, e.g. SSH tunnel support or it will be included in the community edition and in the open source core if there's nothing of value I can add.

**Comment by crschnick** [comment]
So this is now supported in XPipe 9 at https://github.com/xpipe-io/xpipe-ptb. Is not perfect yet and pretty basic but it will get there.

VNC support it was much easier to add and could also be built in, but RDP is another level of complexity to integrate with XPipe itself, so a launcher is the best I can do for now.

**Comment by crschnick** [comment]
This is now implemented in 9.0. For any issue reports or feature request, you can open new issues in this repository
