### ISSUE TITLE
Add remote host from SSH config

### ISSUE THREAD

**Issue by singiamtel** [xpipe-io/xpipe#60]
I keep all my SSH machines in my ``~/.ssh/config`` file, would it be possible to have a way to import them into the app?

```
Host mymachine
	User batman
	IdentityFile ~/.ssh/key3.pem
	HostName 1.2.3.4
```

Thanks for the great project!

**Comment by crschnick** [comment]
Yes that is already on my TODO list.

The main challenge is the variability in ssh configs, there are many different types of rules and configuration options possible in an ssh config, your example is pretty tame. Also the current ssh system needs to know whether there should be a password passed beforehand and from a config it is not apparent whether that is needed or not.

So this will be implemented in conjunction with my planned rework of the ssh support in general.

**Comment by crschnick** [comment]
This is now implemented in the latest release. I only was able to test it with a pretty basic configuration file, but in theory it should work for arbitrary ones.
