### ISSUE TITLE
BitDefender marks Xpipe as a virus when attempting to launch a WSL shell

### ISSUE THREAD

**Issue by donnielrt** [xpipe-io/xpipe#61]
BitDefender intercepted my attempt to launch a shell through Xpipe and marked the attempt as an infestation. 

![image](https://github.com/xpipe-io/xpipe/assets/1524374/93061e43-70cc-4357-8199-f355b56c4e2f)

I know that Windows SmartScreen marks the installation as dangerous because of the lack of an EV certificate, but the BitDefender detection is worrying. Is this a known issue? What is the reason for the detection?

**Comment by crschnick** [comment]
I'm actually not sure what the reason is for the detection. I guess launching shell processes and executing commands in them is always treated as suspicious activity by some antivirus programs. Maybe in the future, when I manage to sign it with an EV certificate, some antivirus programs will look at that more leniently.

As part of the CI pipeline, all artifacts of xpipe are uploaded to virustotal.com and there haven't been any issues. If you want to make sure, you can upload the release you downloaded yourself there, it should instantly show results as all files have been already analyzed beforehand.

If I install bitdefender myself, is there any way to get some details about the reason of the detection?

**Comment by donnielrt** [comment]
Thanks for the quick response, @crschnick. It's not unheard of for these antivirus programs, especially the ones that use heuristics to flag legitimate programs as suspicious, so that might be what's happening.

You should be able to see the application being flagged if you install BitDefender, please enable the "Advanced Threat Defense" option if you do. I got the detection when I was trying to scan my local WSL connections.

I've also filed a false positive with BitDefender, I'll update this issue if they respond.

**Comment by donnielrt** [comment]
For reference, this is what the notification log looks like:

![Screenshot 2023-07-10 223843](https://github.com/xpipe-io/xpipe/assets/1524374/8c7cf7df-42d0-49f4-84c1-7e8a6049c888)

Almost seems like it's tagging cmd.exe as the malicious application!

![Screenshot 2023-07-10 223907](https://github.com/xpipe-io/xpipe/assets/1524374/1a34b795-5cd9-4ba4-bb0e-a8a8a5bc7dc6)

**Comment by crschnick** [comment]
Haha, let's hope that it doesn't isolate or delete cmd.exe here. I guess technically cmd.exe is the one making all the suspicious calls. XPipe doesn't execute anything except the shell process itself, all execution is done by feeding the commands into cmd.exe

**Comment by donnielrt** [comment]
Haha, yeah, I would have bigger problems if it blocked cmd.exe! 

This is what Xpiped shows when it is blocked:

![Screenshot 2023-07-11 132027](https://github.com/xpipe-io/xpipe/assets/1524374/f11cbca9-fd66-4498-891f-b3202ddf1bf5)

**Comment by crschnick** [comment]
So I looked at this in more detail there's nothing I can do from my end except reporting false positives to vendors in case this becomes a more widespread problem.

I updated the security page to include a note on this issue: https://github.com/xpipe-io/xpipe/commit/50e3dffd9b94659cb5b618e578915ff07821cd55

**Comment by donnielrt** [comment]
Fair enough, hopefully BitDefender updates their detection library after investigating my false positive report. I think I should be able to add Xpipe to the exceptions list until then.

Thanks for looking into this!

**Comment by crschnick** [comment]
Oh my god it actually happened for me, bitdefender quarantined cmd.exe while testing.
![image](https://github.com/xpipe-io/xpipe/assets/72509152/8407137b-d50b-4f2f-b577-7561f943c5c5)

I can't run cmd anymore, I have to see I can restore that. I got reports from other people as well that bit defender did not like xpipe, so I thought why not think about a better solution to this.

**Comment by crschnick** [comment]
From what I have seen so far, I would never trust Bitdefender to do anything right with detection rules that bad.

**Comment by crschnick** [comment]
One thing I could implement is checking whether bitdefender is installed on your system prior to running any shell process. That way I have a chance to display a warning about rough times ahead in the application itself, not in the documentation.

**Comment by piperoc** [comment]
I have the same issue today with MCAfee

**Comment by crschnick** [comment]
@piperoc Do you have exactly the same issue, i.e. it flags it as malware because it opens a shell program or immediately on startup?

**Comment by piperoc** [comment]
@crschnick  the error looks different, but also I was doing something different:
Launched XPipe --> MCAfee complained about (but I couldn't catch the offending exe, and they don't have log files by default).
I disabled MCAfee but still see the error. 
Chances are that some files got quarantined. I will try to uninstall/reinstall when I find some time and try to replicate the behavior because now MCafee does not complain anymore but XPipe does not work. Thanks

**Comment by crschnick** [comment]
I might consider looking into properly signing the xpipe executables with an EV certificate assuming that this would fix the issue. (I don't think it will also block executables from recognized publishers)

However this would be a big commitment as you are required to do this as a formal company, so I would have to create one first

**Comment by crschnick** [comment]
How would something like this look to you?

![image](https://github.com/xpipe-io/xpipe/assets/72509152/3918649a-22a4-413f-b640-ef9bd17a802f)

**Comment by donnielrt** [comment]
I think that's a reasonable warning 👍 if you'd like, you could also link to the VirusTotal results page.

**Comment by donnielrt** [comment]
> I might consider looking into properly signing the xpipe executables with an EV certificate assuming that this would fix the issue. (I don't think it will also block executables from recognized publishers)
> 
> However this would be a big commitment as you are required to do this as a formal company, so I would have to create one first

That's unfortunate :( seems like MS and co are pushing for validation as a means of coercement into their paid programs.

**Comment by crschnick** [comment]
> I think that's a reasonable warning 👍 if you'd like, you could also link to the VirusTotal results page.

The CI workflow action actually gives me the Virustotal links for all analyzed files, however I'm not sure where to put and link them properly.

Also, I think that this would not really be convincing as you would have to manually check whether the linked analysis actually corresponds to the file you downloaded anyway. And the best way of doing that is uploading the files manually.

**Comment by donnielrt** [comment]
Ah ok. Might be fine just mentioning it, although people might ask for the link. I agree that it's not particularly convincing for the reasons you mentioned 🤷‍♂️

The warning and popup LGTM! 👍

**Comment by crschnick** [comment]
You can test out this feature in the new staging test version: https://github.com/xpipe-io/xpipe_staging/releases/tag/1.5.0

Essentially, it now checks whether a problematic antivirus is installed and shows this message on first startup. So if everything works correctly, you should see this warning message when bitdefender is installed.

**Comment by crschnick** [comment]
Alright this warning is now live in the latest release. If you're interested in how it looks like for you, you can go to the settings menu under `troubleshoot` -> `Delete caches` and restart. This is necessary as it only will show on first startup.

**Comment by crschnick** [comment]
Closing this as I think the solution to this is satisfactory
