### ISSUE TITLE
[Feature] TMUX on remote host

### ISSUE THREAD

**Issue by ashleysommer** [xpipe-io/xpipe#66]
My usual workflow involves SSHing to a remote host then immediately executing `tmux attach` to jump onto the active tmux session.
This is such a common operation that I have shell scripts saved on my desktop that launches ZSH on the remote hosts, launches tmux, or if there is no active session, it creates a new tmux session and joins it:
```
ssh -i ~/.ssh/id_rsa me@example.org -t "/bin/zsh -c \"/usr/bin/tmux attach || /usr/bin/tmux new\""
```
Or if you don't want to rely on the default tmux socket, or want to use a non-default socket for this auto-join, I do this:
````
ssh -i ~/.ssh/id_rsa me@example.org -t "/bin/zsh -c \"/usr/bin/tmux -S /home/me/.tmux.sock attach || /usr/bin/tmux -S /home/me/.tmux.sock new\""

**Comment by ashleysommer** [comment]
Note, the ohmyzfs plugin manager has a TMUX plugin for ZFS, that allows auto-create and auto-connect capability out of the box. On some remote hosts that I know have ZFS with the TMUX plugin, my script looks like this:

```
ssh -i ~/.ssh/id_rsa me@example.org -t "env TERM=xterm-256color ZSH_TMUX_AUTOSTART=true ZSH_TMUX_AUTOCONNECT=true /bin/zsh -ic \"_zsh_tmux_plugin_run\""
```

**Comment by ashleysommer** [comment]
Actually, this can probably be closed.

For the first example: This can be easily replicated using the Remote Command feature, it doesn't need to be a new feature built into XPipe.

For the second example using ZSH plugin: I realized this functionally can be easily achieved using the "Custom Shell Environment" feature.
I simply choose the ZSH shell on the remote host, then add to the init commands:
```
export ZSH_TMUX_AUTOSTART=true
export ZSH_TMUX_AUTOCONNECT=true
```
Then it simply works

**Comment by crschnick** [comment]
Maybe I could add an option to create a new empty shell environment to the automatic connection detection window that pops up when you add a new connection, to emphasize that it is possible to customize the login environment via that.
