### ISSUE TITLE
FR: Ability to change the order of connections

### ISSUE THREAD

**Issue by Lockszmith-GH** [xpipe-io/xpipe#68]
With the number of connection growing - I'm missing the ability to reorder the connection list.

Wither a keyboard based one, or a drag-n-drop one, or even just a right-click Move Up/Top like option is missing.
Maybe an 'edit mode' where it's separate from functionality - whatever you find most convenient to implement.

And let's not forget the option to sort the connections (by name, by hostname, by last access time - if that metadata exists, etc....)

In the meantime, may I ask if there is a manual / configuration editing hack to achieve this?

**Comment by crschnick** [comment]
Yes, I can definitely see the need for that. In earlier versions, the connections were automatically ordered by last access date, however I removed that as that caused issues with frequent jumping around of connections.

There isn't really a way to manually achieve a custom order, at least it's not worth the effort.

I will see what I can come up with here.

**Comment by crschnick** [comment]
https://github.com/xpipe-io/xpipe/assets/72509152/5a5c9c5a-5a16-4ba7-9e64-ff0d3c29370a

Something like this?

**Comment by Lockszmith-GH** [comment]
The sorting is great, yes!
This way if I name using some numeric prefix, I can controll the order.

Is the sorting persistent? As in, once set, the list remains sorted?

**Comment by crschnick** [comment]
Yes. In fact, you can try it out here: https://github.com/xpipe-io/xpipe_staging/releases/tag/1.5.1

**Comment by Lockszmith-GH** [comment]
I'll try it out tomorrow - thanks!

**Comment by Lockszmith-GH** [comment]
Finally got to test this (I think you already deployed this).
Thank you for taking the time to implement this, this makes things much more managable.

I did notice that although I have the name sorting on, after renaming a connection, the order didn't change.
I'm find with that, just wanted to make sure you are aware in case you had a different design in mind.

**Comment by Lockszmith-GH** [comment]
Fair enough, just wanted to make sure you are aware. I really appreciate the work.

**Comment by crschnick** [comment]
I guess this can be closed unless you come up with more sorting orders or find an issue.
