### ISSUE TITLE
Fully self-contained portable

### ISSUE THREAD

**Issue by crschnick** [xpipe-io/xpipe#72]
Add the option to save all data within the location of a portable installation.

**Comment by furious** [comment]
Just found this in the source code:
https://github.com/xpipe-io/xpipe/blob/e63d0443130b91e47dcd2bf0b7866aefbb7a4b7a/app/src/main/java/io/xpipe/app/core/AppProperties.java#L81

Basically you can add this property at `app/app/xpiped.cfg` under the `[JavaOptions]` with any path you want to save the data, for example:

```
java-options=-Dio.xpipe.app.dataDir=./data
```

This will write all data in the same path as the executable is in a folder "data"

I hope this helps you...

**Comment by crschnick** [comment]
Yeah that is true that this option exists, but it's not really exposed and documented.

Note that you can also pass properties by launching `app/xpiped.exe -Dio.xpipe.app.dataDir=./data` or `app/bin/xpiped -Dio.xpipe.app.dataDir=./data`

**Comment by crschnick** [comment]
You can now launch xpipe in a given directory via the CLI executable `xpipe open -d "<dir>"`
