### ISSUE TITLE
Can't find a an option to change Local Machine default from cmd to PowerShell (or PowerShell Core)

### ISSUE THREAD

**Issue by Lockszmith-GH** [xpipe-io/xpipe#76]
I tried removing and readding as well.

**Comment by crschnick** [comment]
What exactly are you trying to accomplish with a switch?

**Comment by Lockszmith-GH** [comment]
When I interact with my local Windows system, I prefer working with PowerShell, not cmd.
Wanted that to be the default.

**Comment by crschnick** [comment]
Can't you just click on the Powershell connections then to open in your terminal and in the file browser?

The actual reason why cmd is designated as the default on Windows is that Powershell takes forever to start up. All connections that are children of the local machine entry always have to start up the local machine shell first and if that would be Powershell, every action to open any connection would take around one second longer.

**Comment by crschnick** [comment]
> May I ask if implementing a 'default sub connection' might be an option.
This would be a more generic approach, in which on clicking on parent connection, you can choose a child that will be executed instead.

I guess if you don't want to use the desktop shortcut functionality for a connection, I could also implement some sort of favorite system where you can mark certain connections as favorites and they are listed somewhere prominently.

**Comment by Lockszmith-GH** [comment]
Put it on the bottom of the list, this looks like it goes against the grain of the design. Drop it until someone else makes a better argument for this.

**Comment by crschnick** [comment]
Do you make use of the `create desktop shortcut` functionality for connections?

**Comment by Lockszmith-GH** [comment]
No, I do not use desktop shortcuts at all - for anything. My screen is usually covered with windows anyway, never found it convenient.
At rare occasions I create shortcuts that I launch using Start Menu / Launcher / PowerToys Run or pin to the taskbar, but mostly I find how to customize the applications I use to do the job I want.

**Comment by crschnick** [comment]
Another aspect to consider is that right now I don't think it would be technically possible to replace cmd with powershell as it is required to launch cmd first anyways to properly configure the UTF8 CHCP mode that will then be used by powershell.

So I will close this issue then
