### ISSUE TITLE
Modifiable ConnectionTimeout 

### ISSUE THREAD

**Issue by Samurai1201** [xpipe-io/xpipe#78]
I really love the project, it makes my work of managing multiple nodes way easier.

One gripe i have, is that some of my nodes, when put under heavy load, seemingly dont respond properly in time to not be timed out by the 5 second timeout window.

Thats why i would love a feature that lets me modify the parameters that are added to the shell command 

Thanks for your work

**Comment by crschnick** [comment]
Yeah I can definitely see the need for that. The current timeout was somehow determined arbitrarily.

**Comment by crschnick** [comment]
Can you try whether this works for you: https://github.com/xpipe-io/xpipe_staging/releases/tag/1.5.3 . I decided to go for a global setting for now as adjusting that on a per connection basis is quite tedious.

**Comment by Samurai1201** [comment]
Yeah that seems to work nicely for me
Thanks a lot
