### ISSUE TITLE
About version

### ISSUE THREAD

**Issue by Fusion** [xpipe-io/xpipe#79]
Hello again!

A nitpick, and I have no idea if it has to do with updating or what not... but anyway version 1.5.2, the About dialog shows 1.4.17, which happens to be the version I already had installed.

**Comment by crschnick** [comment]
That seems more like an updating issue then, the version string should be correct. How did you upgrade to v1.5.2?

**Comment by Fusion** [comment]
I downloaded the 1.5.2 installer and ran it.

**Comment by crschnick** [comment]
Hmm, maybe something went wrong. macOS .pkgs do not come with an uninstall functionality out of the box, so the contents are just overridden without getting deleted. You can try to execute `/Applications/XPipe.app/Contents/Resources/scripts/uninstall.sh` to properly delete the app and then try to and install it again. (That will preserve your you is your userdata)

**Comment by Fusion** [comment]
I just did and the result is the same.

![image](https://github.com/xpipe-io/xpipe/assets/28699/4ceccff6-1fa9-4843-82ae-6ee6bf615888)

Even after ensuring that /Applications/Xpipe.app did not exist anymore, and re-installing:

![image](https://github.com/xpipe-io/xpipe/assets/28699/7eb7b3a0-c3c5-42d5-a438-d2e3fb36dc9e)

**Comment by crschnick** [comment]
Ohh you were talking about that about page, I thought we were talking about the settings page one:
![image](https://github.com/xpipe-io/xpipe/assets/72509152/af78cb80-85b5-49bb-9922-8451c3c8aca9)

That was my mistake, I never checked that about dialog. It seems like I just forgot to include the version number as a variable, that should be an easy fix.

**Comment by crschnick** [comment]
So I was able to fix that, but I do not know yet whether it is possible for me to modify the text displayed on the about page. I have seen other apps do that, but I'm not sure how achieve that.

**Comment by crschnick** [comment]
Fixed in 1.5.3
