### ISSUE TITLE
Tree/groups of connections

### ISSUE THREAD

**Issue by M-Ahall** [xpipe-io/xpipe#81]
It would be really useful to have a tree structure to group connections into.
For example, Customer → Geographical location → Building → [...] → connections.

Groups would come some way, but a user-defined tree structure would be absolutely fabulous.

**Comment by crschnick** [comment]
I can definitely envision that, the connection overview can get crowded and unorganized. It would also fit pretty well into the bottom left corner there, that one is still empty.

**Comment by M-Ahall** [comment]
A kind of expandable sidelist, pinnable open/autoclosing, could be an idea too.

Possibly an option to display only the connections in the group chosen or all connections contained in all children to the chosen group.

Simple use case:
1. Work with customer X, troubleshoot something that requires access to five different services.
2. Start xpipe.
3. Expand tree from side (if not always in UI).
4. Navigate to customer top level.
5. All company resources are displayed, regardless of further organization, enabling one to quickly jump between different types of servers/resources.
6. If customer has too many resources, toggle showing only resources in the selected group.

**Comment by crschnick** [comment]
So I implemented your suggestion in the latest staging test release: https://github.com/xpipe-io/xpipe_staging/releases/tag/1.6.0. 

Essentially, you now have a category tree that works exactly how you described it.

**Comment by crschnick** [comment]
This feature is now released in 1.6
