### ISSUE TITLE
VSCode version support

### ISSUE THREAD

**Issue by camjac251** [xpipe-io/xpipe#84]
Would it be possible to support dynamic detection of VSCode versions? I am using VS Code Insiders and it has a slightly different path
`%localappdata%\Programs\Microsoft VS Code Insiders\bin\code-insiders.cmd` although I am using `"%localappdata%\Programs\Microsoft VS Code Insiders\bin\code-insiders" $FILE` with `custom` instead.

**Comment by crschnick** [comment]
Yes, I can add that easily

**Comment by crschnick** [comment]
Can you try whether this version works for you: https://github.com/xpipe-io/xpipe_staging/releases/tag/1.5.4

**Comment by crschnick** [comment]
Closing this as it is released now in 1.6
