### ISSUE TITLE
OPNSense terminal not handled

### ISSUE THREAD

**Issue by clienthax** [xpipe-io/xpipe#89]
OPNSense requires an additional option to be entered to get a shell,
xpipe currently says the shell took too long to spawn

<img width="316" alt="image" src="https://github.com/xpipe-io/xpipe/assets/1056270/4d7fbfa2-9222-4f2c-b807-73a11358426d">

![image](https://github.com/xpipe-io/xpipe/assets/1056270/a1bb3d27-a445-43a2-b063-9cab58ef6e0b)

**Comment by crschnick** [comment]
Oh I see the problem. As someone who doesn't use OPNSense, is there no way to automatically select this option by passing a command-line argument or setting an environment variable?

**Comment by clienthax** [comment]
It seems you can bypass it by calling the shell directly
```
ssh -t root@192.168.1.1 csh -l
root@OPNsense:~ #
```

**Comment by crschnick** [comment]
I'm thinking of the best way of handling this.
Are these options numbered the same way for everyone? Or might it be possible that the shell option is not 8? Otherwise I probably need some regex to get the proper option number.
Then I can just write that option into the stdin of the connection, that should be pretty easy.

**Comment by crschnick** [comment]
Anyways I just hardcoded the 8 for now, you can try it out in the [PTB version](https://github.com/xpipe-io/xpipe-ptb)

**Comment by clienthax** [comment]
No luck,

```
Shell did not start up in time:
*** OPNsense.localdomain: OPNsense 23.7.5 ***

 LAN (igc1)      -> v4: 192.168.1.1/24
 WAN (igc0)      -> v4/DHCP4

  0) Logout                              7) Ping host
  1) Assign interfaces                   8) Shell
  2) Set interface IP address            9) pfTop
  3) Reset the root password            10) Firewall log
  4) Reset to factory defaults          11) Reload all services
  5) Power off system                   12) Update from console
  6) Reboot system                      13) Restore a backup



*** OPNsense.localdomain: OPNsense 23.7.5 ***

 LAN (igc1)      -> v4: 192.168.1.1/24
 WAN (igc0)      -> v4/DHCP4:

  0) Logout                              7) Ping host
  1) Assign interfaces                   8) Shell
  2) Set interface IP address            9) pfTop
  3) Reset the root password            10) Firewall log
  4) Reset to factory defaults          11) Reload all services
  5) Power off system                   12) Update from console
  6) Reboot system                      13) Restore a backup



*** OPNsense.localdomain: OPNsense 23.7.5 ***

 LAN (igc1)      -> v4: 192.168.1.1/24
 WAN (igc0)      -> v4/DHCP4:/22


  0) Logout                              7) Ping host
  1) Assign interfaces                   8) Shell
  2) Set interface IP address            9) pfTop
  3) Reset the root password            10) Firewall log
  4) Reset to factory defaults          11) Reload all services
  5) Power off system                   12) Update from console
  6) Reboot system                      13) Restore a backup

Checking whether we are in fish

*** OPNsense.localdomain: OPNsense 23.7.5 ***

 LAN (igc1)      -> v4: 192.168.1.1/24
 WAN (igc0)      -> v4/DHCP4: /22

  0) Logout                              7) Ping host
  1) Assign interfaces                   8) Shell
  2) Set interface IP address            9) pfTop
  3) Reset the root password            10) Firewall log
  4) Reset to factory defaults          11) Reload all services
  5) Power off system                   12) Update from console
  6) Reboot system                      13) Restore a backup



C:\Users\clienthax>

8: Command not found.
8: Command not found.
FISH_VERSION: Undefined variable.
```

**Comment by crschnick** [comment]
Oh well, then the solution isn't that straightforward and I have to experiment with opnsense myself, especially how it handles in a dumb terminal environment.

So I will see when I can find some time to set up opnsense and maybe properly fix this.

**Comment by crschnick** [comment]
Alright I installed it myself in a VM and fixed the issue caused by `opnsense-shell` being different to most other shells with its login and exit procedure. While doing that I also implemented a few fixes for bsd systems in general as I didn't really test these before.

You can test whether it works now with the latest PTB release I pushed.

**Comment by clienthax** [comment]
Works, thanks!

**Comment by crschnick** [comment]
Great
