### ISSUE TITLE
Feature Request: Connection agent to manage multiple connections on remote device

### ISSUE THREAD

**Issue by Mardis** [xpipe-io/xpipe#90]
Hey there, this is a neat tool but I was thinking it would be great if there was an agent I could install on a remote server which has multiple containers running on it so that I can auto-discover/tunnel from my local to each of the remote containers with minimal effort. I  was imagining this would work by installing some kind of daemon on the remote device which would handle local (to the remote server) discovery and then when I run the desktop app it would either automatically find the agent broadcasting on my network or I could provide the server address+port for the connection. 

Keep up the awesome work!

**Comment by crschnick** [comment]
What exactly do you mean by `auto-discover/tunnel` ? Do you mean automatically detecting when new containers are launched or their state changes?

**Comment by Mardis** [comment]
No, though that would be great. I was more referring to simplifying access to the containers on the remote host by using an agent on the remote host (as an option) rather than having to add each container as a separate connection manually. My friend mentioned this tool can discover local docker instances and setup connections for you. I was just thinking a simple way to do the same for remote containers where you have access to the underlying host would be helpful, especially for home setups. Does that make sense?

**Comment by crschnick** [comment]
Yes, I see what you mean but I'm a little bit confused as what you describe (accessing containers on the remote host) works exactly the same on any host, it is not limited to your local machine.

Once you added your remote host via for example SSH, you can then discover and access all docker containers automatically through the `add automatically` functionality, assuming that everything went well and the docker daemon is running etc.

**Comment by crschnick** [comment]
So if there aren't any more questions I'm closing this as completed. I hope you were able to figure out how to add remote containers
