### ISSUE TITLE
Unable to open Windows Terminal

### ISSUE THREAD

**Issue by Dominiquini** [xpipe-io/xpipe#92]
I have the Windows Terminal installed and working on my system, but I get this message when I try to use it:

java.io.IOException: Unable to launch terminal Windows Terminal: Process returned exit code 9009:
'wt' is not recognized as an internal or external command,
operable program or batch file..
Maybe try to use a different terminal in the settings.

Thanks

**Comment by crschnick** [comment]
Is the executable present in the PATH? I.e. can you launch `wt` from a terminal?

**Comment by Dominiquini** [comment]
> Is the executable present in the PATH? I.e. can you launch `wt` from a terminal?

It's in the User Variables PATH, but not in the System Variables PATH! It wok in some terminal, but not in others.
I fix this on my side.

Thanks.

**Comment by crschnick** [comment]
If you don't want to modify any PATH, you can also set the terminal type to custom in the xpipe settings menu and insert the absolute path like `"<location>\wt.exe"`.
